### ISSUE TITLE
How to change augmentation's parameters?

### ISSUE THREAD

**Issue by Danielgol** [Deci-AI/super-gradients#1003]
Hello!

How can i change the augmentation's parameters? I need to make some experiments where flip probability is equals to 0.

I saw that there is a "transforms" options on colab notebook, but I don't know how to change it.

Thanks

**Comment by rohith033** [comment]
I think you can find them in dataset params [yolo_nas_dataset_params](https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/recipes/dataset_params/coco_detection_yolo_nas_dataset_params.yaml)

**Comment by Danielgol** [comment]
Thanks @rohith033 and @Louis-Dupont ! it worked (I've modified it directly from train_dataloader variable on notebook) ! :)
