### ISSUE TITLE
AssertionError: /dfs/data/anaconda/envs/yolonas/lib/python3.8/distutils/core.py

### ISSUE THREAD

**Issue by yukaizhou** [Deci-AI/super-gradients#1006]
### To Reproduce
1. Train recipe '...'
2. Change param '...'
3. See error

### Screenshots
<img width="652" alt="1684138666120" src="https://github.com/Deci-AI/super-gradients/assets/38181468/b0a67e98-f44e-4cc2-83c8-ddd3c26025a6">
### Environment:
 - OS [e.g. uname -s -r -m]
 - Relevant HW info, GPU + CUDA [e.g. nvidia-smi]
 - Super Gradients version
 - Python environment [e.g. pip freeze]

**Comment by Louis-Dupont** [comment]
@yukaizhou please follow issue template and share:
- code snippet
- Full exception (your screenshot missed the last line)
- run pip freeze and copy/paster the result

Without this we cannot really help you :)

**Comment by yukaizhou** [comment]
> 
1: code snippet:

2: Full exception:
<img width="744" alt="1684141387766" src="https://github.com/Deci-AI/super-gradients/assets/38181468/9b66bc28-1aa7-4ef5-bb7d-b2dc17753942">

3:pip freeze:
(yolonas) root@workspace:/dfs/data/code_python/detection_2d/yolo_nas# pip freeze
absl-py==1.2.0
addict==2.4.0
alabaster==0.7.13
antlr4-python3-runtime==4.9.3
anyio==3.6.1
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.0.5
attrs==22.1.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.1
black==22.6.0
bleach==5.0.1
boto3==1.26.133
botocore==1.29.133
build==0.10.0
cachetools==5.2.0
certifi @ file:///opt/conda/conda-bld/certifi_1655968806487/work/certifi
cffi==1.15.1
charset-normalizer==2.1.0
click==8.1.3
cmake==3.25.2
colored==1.4.3
coloredlogs==15.0.1
commonmark==0.9.1
coverage==5.3.1
cycler==0.11.0
Cython==0.29.32
debugpy==1.6.2
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.13
deprecation==2.1.0
descartes==1.1.0
docutils==0.17.1
einops==0.3.2
entrypoints==0.4
executing==0.9.1
fastjsonschema==2.16.1
filelock==3.9.0
fire==0.4.0
flake8==5.0.4
flatbuffers==2.0
fonttools==4.34.4
future==0.18.3
gitdb==4.0.10
GitPython==3.1.31
google-auth==2.18.0
google-auth-oauthlib==1.0.0
grpcio==1.54.2
h5py @ file:///tmp/abs_4aewd3wzey/croots/recipe/h5py_1659091371897/work
humanfriendly==10.0
hydra-core==1.3.2
idna==3.3
imageio==2.21.1
imagesize==1.4.1
importlib-metadata==4.12.0
importlib-resources==5.9.0
iniconfig==1.1.1
ipykernel==6.15.1
ipython==8.4.0
ipython-genutils==0.2.0
ipywidgets==8.0.0rc2
jedi==0.18.1
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.1.0
json-tricks==3.16.1
json5==0.9.9
jsonschema==4.9.1
jupyter==1.0.0
jupyter-client==7.3.4
jupyter-core==4.11.1
jupyter-packaging==0.12.2
jupyter-server==1.18.1
jupyterlab==3.4.4
jupyterlab-pygments==0.2.2
jupyterlab-server==2.15.0
jupyterlab-widgets==3.0.0rc2
kiwisolver==1.4.4
lit==16.0.0rc1
llvmlite==0.31.0
lxml==4.9.1
lyft-dataset-sdk==0.0.8
Mako==1.2.1
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.5.2
matplotlib-inline==0.1.3
mistune==0.8.4
mkl-fft==1.3.1
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626186064646/work
mkl-service==2.4.0
mmcv-full @ file:///dfs/data/3rdparty/mmcv_full-1.3.18-cp38-cp38-manylinux1_x86_64.whl
mmdet==2.14.0
mmsegmentation==0.14.1
mpmath==1.2.1
mypy-extensions==0.4.3
nbclassic==0.4.3
nbclient==0.6.6
nbconvert==6.5.0
nbformat==5.4.0
nest-asyncio==1.5.5
networkx==2.2
notebook==6.4.12
notebook-shim==0.1.0
numba==0.48.0
numpy==1.23.0
nuscenes-devkit==1.1.9
oauthlib==3.2.0
omegaconf==2.3.0
onnx==1.13.0
onnx-simplifier==0.4.5
onnxruntime==1.13.1
onnxruntime-gpu==1.12.0
open3d==0.11.0
opencv-python==4.6.0.66
packaging==21.3
pandas==1.4.3
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
pip-tools==6.13.0
pkgutil_resolve_name==1.3.10
platformdirs==2.5.2
plotly==5.9.0
pluggy==1.0.0
plyfile==0.7.4
polygraphy==0.38.0
prettytable==3.3.0
prometheus-client==0.14.1
prompt-toolkit==3.0.30
protobuf==3.20.3
psutil==5.9.1
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools==2.0.4
pycodestyle==2.9.1
pycparser==2.21
pycuda==2022.1
pyDeprecate==0.3.2
pyflakes==2.5.0
Pygments==2.12.0
pyparsing==2.4.5
pyproject_hooks==1.0.0
pyquaternion==0.9.9
pyrsistent==0.18.1
pytest==7.1.2
python-dateutil==2.8.2
pytools==2022.1.12
pytz==2022.1
PyWavelets==1.3.0
PyYAML==6.0
pyzmq==23.2.0
rapidfuzz==3.0.0
requests==2.28.1
requests-oauthlib==1.3.1
rich==12.5.1
rsa==4.9
s3transfer==0.6.1
scikit-image==0.19.3
scikit-learn==1.1.2
scipy==1.9.0
seaborn==0.11.2
Send2Trash==1.8.0
sentry-sdk==1.14.0
shapely==2.0a1
six @ file:///tmp/build/80754af9/six_1644875935023/work
smmap==5.0.0
sniffio==1.2.0
snowballstemmer==2.2.0
soupsieve==2.3.2.post1
Sphinx==4.0.3
sphinx-rtd-theme==1.2.0
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
stack-data==0.3.0
stringcase==1.2.0
# Editable install with no version control (super-gradients==3.1.1+master)
-e /dfs/data/code_python/detection_2d/yolo_nas
sympy==1.10.1
tenacity==8.0.1
tensorboard==2.13.0
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorrt @ file:///dfs/data/3rdparty/TensorRT-8.2.0.6/python/tensorrt-8.2.0.6-cp38-none-linux_x86_64.whl
termcolor==1.1.0
terminado==0.15.0
terminaltables==3.1.10
thop==0.1.1.post2207130030
threadpoolctl==3.1.0
tifffile==2022.8.8
tinycss2==1.1.1
tomli==2.0.1
tomlkit==0.11.2
torch @ file:///dfs/data/3rdparty/torch-1.10.0%2Bcu113-cp38-cp38-linux_x86_64.whl
torchmetrics==0.8.0
torchvision @ file:///dfs/data/3rdparty/torchvision-0.11.0%2Bcu113-cp38-cp38-linux_x86_64.whl
tornado==6.2
tqdm==4.64.0
traitlets==5.3.0
treelib==1.6.1
trimesh==2.35.39
triton==2.0.0a2
typing_extensions==4.3.0
uff @ file:///dfs/data/3rdparty/TensorRT-8.2.0.6/uff/uff-0.6.9-py2.py3-none-any.whl
# Editable install with no version control (ultralytics==8.0.58)
-e /dfs/data/code_python/detection_2d/yolov8
urllib3==1.26.11
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.3
Werkzeug==2.2.1
widgetsnbextension==4.0.0rc2
wrapt==1.15.0
yapf==0.32.0
zipp==3.8.1

**Comment by Louis-Dupont** [comment]
@yukaizhou it looks like it's not directly related to SuperGradients.
This seems to be due to [setuptools](https://stackoverflow.com/questions/71027006/assertionerror-inside-of-ensure-local-distutils-when-building-a-pyinstaller-exe), you can try to run `pip install setuptools==59.8.0`  and try again after

**Comment by yukaizhou** [comment]
> pip install setuptools==59.8.0

Thank you very much for your guidance, using pip install setuptools==59.5.0  solved the problem
