### ISSUE TITLE
Post Training Quantization and Quantization Aware Training Notebook for object detection

### ISSUE THREAD

**Issue by beratersari** [Deci-AI/super-gradients#1011]
Could you provide a notebook for Post Training Quantization and Quantization Aware Training in object detection topic?

**Comment by Louis-Dupont** [comment]
Hi @beratersari ,
We have a documentation page specifically on [PTQ/QAT](https://docs.deci.ai/super-gradients/documentation/source/ptq_qat.html#post-training-quantization).
FYI, we are currently working on new methods to simplify this process. This will not be a breaking change, but just a wrapper around this logic to help people with lower proficiency using it.
