### ISSUE TITLE
Kornia augmentations integration 

### ISSUE THREAD

**Issue by edgarriba** [Deci-AI/super-gradients#102]
Hi guys, very nice repository— congratulations!

We were wondering whether we can help you guys to integrate [kornia.augmentations](https://kornia.readthedocs.io/en/latest/applications/image_augmentations.html) in your framework.

We have special containers to automate the case for augmenting for detection, segmentation, videos, etc.
- https://kornia.readthedocs.io/en/latest/augmentation.container.html#kornia.augmentation.container.AugmentationSequential

An example of a similar integration can be found here from ms-torchgeo team after further collaboration 
- https://github.com/microsoft/torchgeo/blob/main/torchgeo/transforms/transforms.py

let us know so that our augmentations team can assist you in case 0f missing features /cc @shijianjian @twsl

**Comment by oferbaratz** [comment]
Hi Edgar,
Thanks for this issue!
Indeed it seems very interesting - we are checking it out and will be in touch soon.
