### ISSUE TITLE
Run YOLO-NAS on Mobile Phones and Edge Devices

### ISSUE THREAD

**Issue by M-Anees99** [Deci-AI/super-gradients#1020]
This is just an expression of our admiration for the outstanding performance of your open-source YOLO-NAS model. I am writing this on behalf of "EdgeStore", a company that specializes in enabling users to run AI models on mobile phones and edge devices.

Since deploying machine learning models on mobile and edge devices can be challenging, we have developed software development kits (SDKs) to make it easy for users to harness the power of your YOLO-NAS model on any mobile phone and edge device.

We would be delighted to provide you with a demonstration of our SDKs and would love to schedule a call or meeting to discuss further. Please let me know your availability and the best time and channel for us to connect.  Thanks.

**Comment by Shani-Perl** [comment]
Hello, we extend ou gratitude for your active involvement and response. We are eager to arrange a conversation with you to discuss the SDK and explore potential pathways forward. To facilitate this, we kindly request you to reach out to Yaniv Tager via email at yaniv.tager@deci.ai. Your consideration is greatly appreciated.
