### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by CuarteroAlvaro** [Deci-AI/super-gradients#1023]
Hello, I would like to know if the data augmentation is implemented within the Trainer itself or is it necessary to do it outside the training. If so, is there any documentation to consult to modify the parameters of such data augmentation? I have searched for information on the subject and, although I think it is not implemented, I would like to make sure! 

Thank you very much in advance!

**Comment by NatanBagrov** [comment]
Hello, @CuarteroAlvaro, data augmentation is done in the level of the data (Dataset).
You can modify the augmentation via the dataset parameters yaml file (called Transforms).
See the docs for the [DetectionTransforms](https://docs.deci.ai/super-gradients/docstring/training/transforms.html#training.transforms.transforms.DetectionHSV) available out of the box

**Comment by CuarteroAlvaro** [comment]
Thank you so much for the information!

**Comment by NatanBagrov** [comment]
I'm closing this issue, reopen it if you have further questions :)
