### ISSUE TITLE
Semantic segmentation with PP-Lite-T and cityscapes dataset - error with mask

### ISSUE THREAD

**Issue by vogloblinsky** [Deci-AI/super-gradients#1036]
### 💡 Your Question

Hi,

I tried to adapt this tutorial (https://github.com/Deci-AI/super-gradients/blob/master/tutorials/SuperGradients%20How%20To%20Use%20a%20model%20to%20Predict.ipynb) to use PP-Lite-T with cityscapes dataset

```! wget "https://deci-pretrained-models.s3.amazonaws.com/ppliteseg/supervisely/pplite_t/ckpt_best.pth"```

was adapted to

```! wget "https://deci-pretrained-models.s3.amazonaws.com/ppliteseg/cityscapes/pplite_b_seg75/average_model.pth"```

and model loading

```
model = models.get("pp_lite_t_seg",
                   num_classes=1,
                   checkpoint_path='ckpt_best.pth')
```

to

```
model = models.get("pp_lite_t_seg75", pretrained_weights="cityscapes") 
```

when i tried to adapt the mask i got this error

```
mask = torch.sigmoid(mask).gt(0.5).squeeze()
mask = transforms.ToPILImage()(mask.float())
```

`ValueError: pic should not have > 4 channels. Got 19 channels.`

**Comment by BloodAxe** [comment]
I'm confused. So did you load model like `model = models.get("pp_lite_t_seg75", pretrained_weights="cityscapes")` or like `model = models.get("pp_lite_t_seg", num_classes=1,)`?

For the error it looks like you loaded model with 19 classes.

**Comment by vogloblinsky** [comment]
With `model = models.get("pp_lite_t_seg75", pretrained_weights="cityscapes")` ; i miss `, num_classes=1`. 

The error disappear, thanks.
