### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ahmadmustafaanis** [Deci-AI/super-gradients#1037]
### 🐛 Describe the bug

```
frame_001330_003.PNG was no found. Please make sure that the dataset was downloaded and that the path is correct
```
The dataloader should automatically handle if a image does not exist for a label and ignore it instead of stopping the training.

### Versions

L1i cache:                       64 KiB
L2 cache:                        512 KiB
L3 cache:                        45 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.13.1
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.14.1
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi

[12:38](https://redbuffer.slack.com/archives/D03U1GHTBQV/p1684395503690789)
Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A
OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31
Python version: 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1032-gcp-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.4.152
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 470.182.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn.so.8.2.4
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.4
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.4
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.4
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.4
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.4
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A

**Comment by Louis-Dupont** [comment]
Can you please share the code snippet to see what dataset you are using and how you instantiate it?

**Comment by merryHunter** [comment]
actually, it 's a good question, I believe there should be a way to suppress filenotfound errors and continue training instead of interruption, what do you think?

**Comment by BloodAxe** [comment]
> The dataloader should automatically handle if a image does not exist for a label and ignore it instead of stopping the training.

I'm certain that it should not. It is the user responsibility to provide valid, uncorrupted dataset. If there is annotation file present, but the image is missing - that's clearly not SG responsibility to correct these mistakes.

Maybe the issue related to some misconfiguration of the dataset. @ahmadmustafaanis can you please share more details what dataset, how you instantiate it and how you downloaded it?

**Comment by ahmadmustafaanis** [comment]
No. It was related to a corrupt Image. It is the user's responsibility but not every time t, but a library should be able to handle all the edge cases. It should easily be doable by using PIL, which I eventually did. And I had no idea about the dataset, Just wanted to do a few experiments.
Assign this issue to me if you're unable to do so.
