### ISSUE TITLE
ValueError: 'map050' is not in list

### ISSUE THREAD

**Issue by okanegemen** [Deci-AI/super-gradients#1049]
### 🐛 Describe the bug

[2023-05-21 15:46:58] INFO - sg_trainer.py - Using EMA with params {'decay': 0.9, 'decay_type': 'threshold'}
The console stream is now moved to /content/checkpoints/firstYoloNasRun/console_May21_15_46_58.txt
[2023-05-21 15:47:01] INFO - sg_trainer_utils.py - TRAINING PARAMETERS:
    - Mode:                         Single GPU
    - Number of GPUs:               1          (1 available on the machine)
    - Dataset size:                 4144       (len(train_set))
    - Batch size per GPU:           8          (batch_size)
    - Batch Accumulate:             1          (batch_accumulate)
    - Total batch size:             8          (num_gpus * batch_size)
    - Effective Batch size:         8          (num_gpus * batch_size * batch_accumulate)
    - Iterations per epoch:         518        (len(train_loader))
    - Gradient updates per epoch:   518        (len(train_loader) / batch_accumulate)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-44-cd19d4a2fd3d> in <cell line: 1>()
----> 1 trainer.train(model=model,
      2               training_params=train_params,
      3               train_loader= trainData,
      4               valid_loader=valData,
      5 

4 frames
/usr/local/lib/python3.10/dist-packages/super_gradients/training/utils/utils.py in fuzzy_idx_in_list(name, lst)
    224     :return: int, index of name in lst in the matter discussed above.
    225     """
--> 226     return [fuzzy_str(x) for x in lst].index(fuzzy_str(name))
    227 
    228 

ValueError: 'map050' is not in list

### Versions

train_params = {
    "silent_mode" : True ,

    "average_best_models" : True ,

    "warmup_mode" : "linear_epoch_step" ,

    "warmup_initial_lr" : 1e-6 ,

    "lr _warmup_epochs" : 3 ,
    
    "initial_lr" : 5e-4 ,
    
    "lr_mode" : "cosine" ,
    
    "cosine_final_lr_ratio" : 0.1,
    
    "optimizer" : "AdamW",
    
    "optimizer_params" : {"weight_decay": 0.0001} ,
    
    "zero _weight_decay_on_bias_and_bn" : True ,
    
    "ema" : True ,
    
    "ema_params" : {"decay": 0.9, "decay_type": "threshold"} ,

    "max_epochs": 200,
    "mixed_precision": True,
    "loss": PPYoloELoss (
        use_static_assigner=False,
        num_classes = 3,
        reg_max = 16 ),
    #"train_metrics_list": [Accuracy(), Top5()],
    "validation_metric_list" :[
        DetectionMetrics_050(
            score_thres=0.3,
            top_k_predictions=300,
            num_cls=3,
            normalize_targets=True,
            post_prediction_callback= PPYoloEPostPredictionCallback(
                score_threshold = 0.01,
                nms_top_k=1000,
                max_predictions=300,
                nms_threshold=0.7
            )
        )
        
    ],
    "metric_to_watch": "mAP@0.50"
    #"greater_metric_to_watch_is_better": True
    
}
this is a code to set train params and when I assign "metric_to_watch" param as "mAP@0.50" I always get ValueError like shown

**Comment by shaydeci** [comment]
valid_metrics_list instead of validation_metric_list in training_params and it should work.

**Comment by okanegemen** [comment]
thanks, it worked
