### ISSUE TITLE
What is the cleanest way of getting NMS:ed model outputs of the shape (x, y, x, y, conf, cls)?

### ISSUE THREAD

**Issue by mikel-brostrom** [Deci-AI/super-gradients#1054]
### 💡 Your Question

I am working on implementing tracking functionality for YOLO-NAS in my [repository](https://github.com/mikel-brostrom/yolov8_tracking). What is the cleanest way of getting NMS:ed model outputs of the shape (x, y, x, y, conf, cls)?

I have tried:

```
from super_gradients.common.object_names import Models
from super_gradients.training import models


rgb = torch.rand(1, 3, 640, 640).to("cuda:0")
model = models.get(Models.YOLO_NAS_S, pretrained_weights="coco").to("cuda:0")
preds = model(im)
preds = model(im)
print(len(preds))
print(preds[0].shape)
print(preds[1].shape)
print(preds[2].shape)
print(preds[3].shape)
print(preds[4].shape)
```

which gives me 

```
6
torch.Size([1, 6300, 80])
torch.Size([1, 6300, 68])
torch.Size([6300, 4])
torch.Size([6300, 2])
```

I am confused by the outputs and can't find information about my issue in the documentation...

### Versions

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.13.1
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.14.1
[pip3] triton==2.0.0

**Comment by Louis-Dupont** [comment]
Hi @mikel-brostrom , we have a [documentation page](https://docs.deci.ai/super-gradients/documentation/source/ModelPredictions.html) about the `model.predict(...)` method which, from what you described, should cover your need

**Comment by mikel-brostrom** [comment]
I have this:

```pyhton
preds = model.predict(im, iou=0.5, conf=0.7)
preds = list(preds._images_prediction_lst)
preds = np.concatenate([
    preds[0].prediction.bboxes_xyxy,
    np.expand_dims(preds[0].prediction.confidence, axis=1),
    np.expand_dims(preds[0].prediction.labels, axis=1),
], axis=1)
print(preds.shape)  # (1, 6)
```

Feels very convoluted to me. Is there a better way to achieve this?

**Comment by Louis-Dupont** [comment]
You can simplify the code slightly like here:
``` python
prediction = next(iter(model.predict(IMAGES, iou=0.5, conf=0.7))).prediction # Returns a generator of the batch, which here is 1
concat_preds = np.concatenate([prediction.bboxes_xyxy, prediction.confidence[:, np.newaxis], prediction.labels[:, np.newaxis]], axis=1)
```

Note that in the master branch we fixed a bug where `preds._images_prediction_lst` was a generator and not a list. You can access directly index it
``` python
prediction = model.predict(IMAGES, iou=0.5, conf=0.7)[0].prediction
concat_preds = np.concatenate([prediction.bboxes_xyxy, prediction.confidence[:, np.newaxis], prediction.labels[:, np.newaxis]], axis=1)
```

**Comment by mikel-brostrom** [comment]
Thanks! This looks much better! I guess you will hear from we soon again regarding  yolo-nas tracking capabilities. Than you for your time :smile:
