### ISSUE TITLE
An issue with DetectionCollateFN(): gives an error on images with varying number of bboxes in the same batch

### ISSUE THREAD

**Issue by angelinager** [Deci-AI/super-gradients#1056]
### 🐛 Describe the bug

In your tutorial on [how to connect custom dataset](https://github.com/Deci-AI/super-gradients/blob/master/tutorials/SuperGradients_Object_Detection_How_to_Connect_Custom_Dataset.ipynb) you use a generated toy dataset where each image has the same number of bounding boxes and it works just fine. However, when I try to use my custom Dataset constructed according the following tutorial but with images having different amount of boxes, it gives the following error: 

```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/super_gradients/training/utils/detection_utils.py", line 667, in __call__
    batch = default_collate(data)
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 143, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 172, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/angelina/cargo_xray/super_gradients/supergrad/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 163, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 5] at entry 0 and [2, 5] at entry 2
```
I tried to randomly change the number of boxes (between 1 and 5 instead of fixed 5) in the [tutorial](https://github.com/Deci-AI/super-gradients/blob/master/tutorials/SuperGradients_Object_Detection_How_to_Connect_Custom_Dataset.ipynb) as well, and this error is also reproducible there.

Here's the code for my custom data loader class:

```
import torch
from torch.utils.data import Dataset
from torchvision import transforms, utils

import json
import os
from PIL import Image
import numpy as np

class MyCustomDataset(Dataset):

    def __init__(self, data_folder):
        
        self.image_folder = os.path.join(data_folder, "images")
        self.annot_folder = os.path.join(data_folder, "labels")
        
        # Read data files
        self.images = os.listdir(self.image_folder)
        # Read annotation files
        self.annotations = os.listdir(self.annot_folder)
        
    def __len__(self):
        return min(len(self.images), len(self.annotations))

    def __getitem__(self, i):
        
        # Read image and label
        image_filename = self.images[i]
        annot_filename = image_filename.split('.tif')[0] + '.txt'
        
        if annot_filename in self.annotations:
            image_path = os.path.join(self.image_folder, image_filename)
    
            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            image = cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)
            image = cv2.resize(image, (640, 640))
            image_tensor = torch.tensor(np.array(image, dtype=np.float32)).permute(2, 0, 1).float()
        
            labels_path = os.path.join(self.annot_folder, annot_filename)
            labels = np.loadtxt(labels_path, delimiter=' ')
                
            if labels.ndim == 1:
                labels = np.reshape(labels, (1, -1))
            
            return image_tensor, labels
```
And how I use it further for creating a DataLoader object:

```
from torch.utils.data import Dataset, DataLoader
from super_gradients.training.utils.detection_utils import DetectionCollateFN

train_dataset = MyCustomDataset(my_train_dir)
train_dataloader = DataLoader(train_dataset, batch_size=4, shuffle=True, num_workers=2, collate_fn=DetectionCollateFN()) 
```

### Versions

Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 510.108.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          16
On-line CPU(s) list:             0-15
Thread(s) per core:              2
Core(s) per socket:              8
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           113
Model name:                      AMD Ryzen 7 3700X 8-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         2200.000
CPU max MHz:                     4426,1709
CPU min MHz:                     2200,0000
BogoMIPS:                        7186.46
Virtualization:                  AMD-V
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2 cache:                        4 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0-15
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.13.1
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.1.243             h6bb024c_0  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] pytorch                   1.13.1             py3.10_cpu_0    pytorch
[conda] pytorch-mutex             1.0                         cpu    pytorch
[conda] torchvision               0.14.1                py310_cpu    pytorch

**Comment by Louis-Dupont** [comment]
Hi @angelinager ,

We handle it in our transforms by adding a padding step. You can try this piece of code, which takes the targets of one image (of varying first dim) and forces it to be of shape (max_targets, 5). Just make sure to take `max_targets` big enough to include all your targets. 
``` python
def pad_targets(targets: np.ndarray, max_targets: int) -> np.ndarray:
    padded_targets = np.zeros((max_targets, targets.shape[-1]))
    padded_targets[range(len(targets))[: max_targets]] = targets[: max_targets]
    padded_targets = np.ascontiguousarray(padded_targets, dtype=np.float32)
    return padded_targets
```

**Comment by angelinager** [comment]
Hi @Louis-Dupont,

Adding the padding step did the job, thank you!
