### ISSUE TITLE
How to access predictions?

### ISSUE THREAD

**Issue by mexicantexan** [Deci-AI/super-gradients#1058]
### 💡 Your Question

I have this code:
```
image = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
if image.shape[0] != 640 or image.shape[1] != 640:
    image = cv2.resize(image, (640, 640))

# make sure that the image is 3 channel rgb
if len(image.shape) == 2:
    image = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
elif image.shape[2] == 4:
    image = cv2.cvtColor(image, cv2.COLOR_RGBA2RGB)
detect_net = models.get(Models.YOLO_NAS_M, pretrained_weights="coco")
detect_net.eval()
pred = detect_net.predict(image)
```
I can't seem to access the prediction in the variable `pred`, but if I substitute that line with: `detect_human_net.predict(image).show()` the output is shown. I'm just trying to access the predictions, nothing too dramatic. I've tried using `draw()` but that doesn't seem to be an option for the class that is returned from the predict call.

**Comment by Louis-Dupont** [comment]
Hi @mexicantexan , if I understood correctly, you should find what you are looking for in this [page](https://docs.deci.ai/super-gradients/documentation/source/ModelPredictions.html).
Is it what you were looking for?


*Notes*
- You can, but don't need to load with cv2.imread, the `model.predict()` method does it.
- You don't need to call `detect_net.eval()`, it is also done as part of the predict.

**Comment by mexicantexan** [comment]
Yes, that worked perfectly! Sorry, just saw this :)
