### ISSUE TITLE
Accessing prediction results by index whilst providing the model only one image for inference.

### ISSUE THREAD

**Issue by sobek1886** [Deci-AI/super-gradients#1060]
### 💡 My Question:
#  How do I access the prediction results when running ``` model.predict() ``` on only one image?

## I'm trying to access bounding box coordinates of objects detected by YOLO-NAS.
I'm following [this tutorial](https://docs.deci.ai/super-gradients/documentation/source/ModelPredictions.html#detect-objects-in-multiple-images).

### Trying to access the predictions using ``` images_predictions[0] ```   gives me an error when I provide the model with only 1 image for inference.

```  
from super_gradients.common.object_names import Models
from super_gradients.training import models
import torch

model = models.get(Models.YOLO_NAS_L, pretrained_weights="coco")
model = model.to("cuda" if torch.cuda.is_available() else "cpu")

IMAGES = [
    "/content/devices.jpg"
]

images_predictions = model.predict(IMAGES)

print(type(images_predictions[0]))
 ```
out: ``` TypeError: 'generator' object is not subscriptable ```

### It works well when I give the model 2 or more images for inference.
```  
from super_gradients.common.object_names import Models
from super_gradients.training import models
import torch

model = models.get(Models.YOLO_NAS_L, pretrained_weights="coco")
model = model.to("cuda" if torch.cuda.is_available() else "cpu")

IMAGES = [
    "/content/devices.jpg",
    "/content/devices.jpg"
]

images_predictions = model.predict(IMAGES)

print(type(images_predictions[0]))
```  
out: ```  <class 'super_gradients.training.models.prediction_results.ImageDetectionPrediction'> ```  

### for reference, this is how I'm trying to access and store the bbox coordinates
```  
detected_objects = []
image_prediction = images_predictions[0]

labels = image_prediction.prediction.labels
confidence = image_prediction.prediction.confidence
bboxes = image_prediction.prediction.bboxes_xyxy

for i, (label, conf, bbox) in enumerate(zip(labels, confidence, bboxes)):
    detected_objects.append(bbox)
```

**Comment by Louis-Dupont** [comment]
Hi @sobek1886 , this is a known issue (https://github.com/Deci-AI/super-gradients/issues/956).
It was fixed in the master branch (`pip install git+https://github.com/Deci-AI/super-gradients`) and will be part of the next release :)
