### ISSUE TITLE
ImportError Unable to import super_gradients

### ISSUE THREAD

**Issue by Gaurav2912** [Deci-AI/super-gradients#1062]
### 🐛 Describe the bug

from super_gradients.training import models

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-11-9f6f98514aad>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import super_gradients

13 frames
[/usr/local/lib/python3.10/dist-packages/PIL/ImageFont.py](https://localhost:8080/#) in <module>
     36 from . import Image
     37 from ._deprecate import deprecate
---> 38 from ._util import is_directory, is_path
     39 
     40 

ImportError: cannot import name 'is_directory' from 'PIL._util' (/usr/local/lib/python3.10/dist-packages/PIL/_util.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by spsancti** [comment]
Hi!
Please, restart runtime after installing if you are running it in Google Colab.

**Comment by Louis-Dupont** [comment]
Hi @Gaurav2912 , it's a duplicate issue from https://github.com/Deci-AI/super-gradients/issues/950, please check the proposed solution, and if it doesn't solve your problem please reply in this other thread to centralize all the information in the same thread :)

**Comment by Gaurav2912** [comment]
Thanks,
