### ISSUE TITLE
Support training with multi-scale

### ISSUE THREAD

**Issue by dFuong** [Deci-AI/super-gradients#1064]
Does Yolo-nas support training with multi-scale ?

**Comment by shaydeci** [comment]
Training in SG generally supports multi-scale.
For YoloNAS, you will need to pass DetectionMultiscalePrePredictionCallback through the "pre_prediction_callback"training parameter. See its docs [here](https://docs.deci.ai/super-gradients/docstring/training/datasets.html#training.datasets.datasets_utils.MultiscalePrePredictionCallback).
