### ISSUE TITLE
Model outputs negative values

### ISSUE THREAD

**Issue by mikel-brostrom** [Deci-AI/super-gradients#1069]
### 🐛 Describe the bug

I ran Yolo-NAS on an image

```python
rgb = cv2.imread("path/to/image.png")
prediction = model.predict(rgb, iou=0.5, conf=0.7)[0].prediction
concat_preds = np.concatenate([prediction.bboxes_xyxy, prediction.confidence[:, np.newaxis], prediction.labels[:, np.newaxis]], axis=1)
```

Outputs this:

```
[[     20.721      325.82      639.41      473.77           2     0.38735          59]
 [   -0.68298      1.0351      600.07      474.49           1        0.96           0]]
```

Notice the negative value in the second row. The clipping should happen inside the model IMO.

### Versions

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==1.13.1
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.14.1
[pip3] triton==2.0.0

**Comment by shaydeci** [comment]
Closing this down after this issue has been discussed [here](https://github.com/Deci-AI/super-gradients/issues/1137).
