### ISSUE TITLE
How to get losses and predictions out of a YOLO-NAS model with different classes?

### ISSUE THREAD

**Issue by xtquinn** [Deci-AI/super-gradients#1070]
### 💡 Your Question

I am looking to create a YOLO-NAS model with fewer classes than the pretrained models.

 `ObjectDetection.md` references using the `YoloPostPredictionCallback` in `DetectionMetrics`, however there is not that much information on how to use this.

Some of the documentation says that this can be used in the below method:

```
model0 = models.get(model_name="yolo_nas_s", pretrained_weights="coco")
model0.replace_head(new_num_classes=4)
YoloPostPredictionCallback(conf=0.001, iou=0.6, classes=4)(model(input))
```
However, this returns an error, and seems as if it would not provide loss values.
```
--> 249     candidates_above_thres = prediction[..., 4] > conf_thres  # filter by confidence
    250     output = [None] * prediction.shape[0]
    252     for image_idx, pred in enumerate(prediction):

IndexError: index 4 is out of bounds for dimension 1 with size 4
```
`prediction` in this case is the first element of the raw output of the model, which has size `torch.Size([1, 9072, 4])`
As the last dimension in this output is the same as the number of classes, `prediction[..., 4] > conf_thres` seems like it would not work for fewer classes than 5.

Are there any examples demonstrating how to fold in nms and loss into a YOLO-NAS model with a replaced head?

**Comment by BloodAxe** [comment]
For YoloNAS you want to use `PPYoloEPostPredictionCallback` or (better) call `model0.get_post_prediction_callback(conf, iou)` to get the right type of post-prediction callback

**Comment by mazatov** [comment]
@xtquinn, did you work it out. I was wondering the same?
