### ISSUE TITLE
infery error,  NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968

### ISSUE THREAD

**Issue by beratersari** [Deci-AI/super-gradients#1077]
### 💡 Your Question

![image](https://github.com/Deci-AI/super-gradients/assets/56562278/ee782487-f601-496b-a0f8-68498d01149f)

**Comment by mmax3** [comment]
This solves the error

import locale
locale.getpreferredencoding = lambda: "UTF-8"

 but raises:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement infery (from versions: none)
ERROR: No matching distribution found for infery

**Comment by shaydeci** [comment]
We have updated our notebooks to not be using infery any more. Closing this one for now.
