### ISSUE TITLE
How much GPU RAM is being used?

### ISSUE THREAD

**Issue by Tsardoz** [Deci-AI/super-gradients#1082]
### 💡 Your Question

I have been training with YOLOv5 and am trialling YOLO-NAS/Super-gradients.

In YOLOv5 I increase the batch size until the GPURAM used is below the maximum.
How do I do this with Super-Gradients?
The output seems very sparse. It just tells me when the best checkpoint has been overridden.
No epoch by epoch results that I can see.
I am following
https://colab.research.google.com/drive/1q0RmeVRzLwRXW-h9dPFSOchwJkThUy6d#scrollTo=t5sKiaH9efp-

How can I get epoch by epoch results, with various results (similar to yolov5) but with at least GPURAM used?
Thanks.

**Comment by harpreetsahota204** [comment]
Hi @Tsardoz In the linked notebook, training is running in `silent_mode`. You can toggle this in `train_params` by setting `'silent_mode': False`
