### ISSUE TITLE
Polygonal Object detection

### ISSUE THREAD

**Issue by Rohinivv96** [Deci-AI/super-gradients#1088]
### 💡 Your Question

I am seeking to identify polygonal objects through employment of the YOLO-NAS model. 
My attempts at applying this model to a custom dataset have yielded highly satisfactory outcomes. 
However, when faced with tilted or misaligned objects, the YOLO-NAS model struggles to detect them. 
I had previously undergone training with YOLOv5 for comparable objectives. I am curious to know if it is feasible to train the YOLO-NAS model for detecting polygonal objects.
Thanks in advance.

**Comment by armine105** [comment]
Hello
How are you?
I want to detect a quadrangular polygon object such as a pool table below.

![image](https://github.com/Deci-AI/super-gradients/assets/135291100/c7682272-452e-41dc-ae0b-9692e3ea62f3)

Is it possible to do it using yolo-nas?
The "Polygon-Yolov5" project (https://github.com/XinzeLee/PolygonObjectDetection) supports this.
