### ISSUE TITLE
YOLO-NAS Architecture

### ISSUE THREAD

**Issue by shbkukuk** [Deci-AI/super-gradients#1096]
### 💡 Your Question

I am wondering about architecture of YOLO-NAS. Which YOLO (YOLOv5...,YOLOv8) architecture used based for developing YOLO-NAS  ? And also which anchor approximation does use ? Anchor free or directly use anchor ?

**Comment by taofuyu** [comment]
me too

**Comment by shbkukuk** [comment]
I search on the web about YOLO-NAS i found Kaggle post that talk about YOLO-NAS. ([https://www.kaggle.com/general/406701](link)) 
Furthermore, i joined the official discord server of super-gradient for asking  this question to developers. He said that they used anchor free.
