### ISSUE TITLE
Minimum example for custom model inference

### ISSUE THREAD

**Issue by mikel-brostrom** [Deci-AI/super-gradients#1099]
### 💡 Your Question

Could you provide an example for running inference on a custom YOLO-NAS model? Couldn't find a minimum example for this in the docs. If this exists in the docs you could just send the link to its location :smile:

**Comment by BloodAxe** [comment]
See "Quickstart" section of  https://github.com/Deci-AI/super-gradients/blob/ac21534a5505da1e2758acddd7dead0e7ac19dad/YOLONAS.md
