### ISSUE TITLE
Suggestion for ClearML integration improvement

### ISSUE THREAD

**Issue by wematan** [Deci-AI/super-gradients#1113]
### 🚀 Feature Request

The current clearml integration with SG fits a basic usability pattern, one needs to provide project/experiment name and the task is initialized by SG with default parameters.
But since advanced usages might include applying other arguments to ClearML task create/init functions, for example: docker arguments, execution specific arguments and more, this is currently not supported.

### Proposed Solution (Optional)

Add functionality to sg clearml logger which enables "setup"ing the logger from a pre-initialized task.
A good option would be passing an initialized task hash id so that the logger object could be queried from clearml without init'ing a task.

**Comment by BloodAxe** [comment]
This sounds like a good improvement. Yes, current ClearML logger do provide a basic set of features but nothing "extra".
Unfortunately we are out of capacity to extend support of ClearML using our available resources. However we are open for external contributions for this feature.
