### ISSUE TITLE
CUDA versions and inference on TensorRT

### ISSUE THREAD

**Issue by lpkoh** [Deci-AI/super-gradients#1127]
### 💡 Your Question

Hi, I wish to clarify on the exact requirement for CUDA versions for inference in Tensorrt.

So I see on the requisites that you require:
![image](https://github.com/Deci-AI/super-gradients/assets/48631399/8b2a5b50-4ff9-4f3b-9d29-e122382aca45)
for training.

May I know if these are required for inference as well? This is because I am using a different machine for training and inference, and the inference environment is running older Nvidia drivers. One of them is an edge device as well, so upgrading Cuda is inconvenient. Possible to train in CUDA 11.2, then infer in CUDA 10.2 with nvidia driver 418?

**Comment by BloodAxe** [comment]
Hi there. 

> Possible to train in CUDA 11.2,
Definitely yes.

>  infer in CUDA 10.2 with nvidia driver 418?
Not sure about that but you can give it a try. I imagine version of If TRT engine for 10.2
