### ISSUE TITLE
DetectionVerticalFlip

### ISSUE THREAD

**Issue by LukeAI** [Deci-AI/super-gradients#1161]
### 🚀 Feature Request

In https://github.com/Deci-AI/super-gradients/blob/a43cfcd70072c7be1231f9183b1a717c136ff657/src/super_gradients/training/transforms/transforms.py#LL815C1-L815C1

There is `DetectionHorizontalFlip` but no `DetectionVerticalFlip` which would be a useful augmentation to have for my dataset, it would be trivial to implement and I'd be happy to open a PR if it would be accepted?

**Comment by NatanBagrov** [comment]
Hello, PRs are welcome 🥇

**Comment by LukeAI** [comment]
@NatanBagrov  have implemented https://github.com/Deci-AI/super-gradients/issues/1161

**Comment by harpreetsahota204** [comment]
Hi @LukeAI -

Thanks for opening an issue for SG. I'm gathering some feedback on SuperGradients and YOLO-NAS.

Would you be down for a quick call to chat about your experience?

If a call doesn't work for you, no worries. I've got a short survey you could fill out: https://bit.ly/sgyn-feedback.

I know you’re super busy, but your input will help us shape the direction of SuperGradients and make it as useful as possible for you.

I appreciate your time and feedback. Let me know what works for you.

Cheers,

Harpreet

**Comment by LukeAI** [comment]
yeah a call is fine

**Comment by harpreetsahota204** [comment]
@LukeAI -  Great! Feel free to find sometime here:https://calendly.com/harpreet-sahota/30min

**Comment by LukeAI** [comment]
Hi Harpreet,

Sorry to let you down short notice but I'm not going to be able to make the 11.30 call, something has come up. I can reschedule.

Luke
________________________________
