### ISSUE TITLE
Missing keys when loading from checkpoint

### ISSUE THREAD

**Issue by ikin5050** [Deci-AI/super-gradients#1163]
### 💡 Your Question

I have finetuned a model based on yolonas_l. When I attempt to load this model using the following code:

 `model = models.get(
    model_name='yolo_nas_l',
    checkpoint_path='checkpoints/yolo_nas_l/Person_ckpt_best.pth',
    num_classes=5
).to(device)`

I get the error message:

`RuntimeError: Error(s) in loading state_dict for YoloNAS_L:
	Missing key(s) in state_dict: "backbone.stem.conv.branch_3x3.conv.weight", "backbone.stem.conv.branch_3x3.bn.weight", "backbone.stem.conv.branch_3x3.bn.bias", "backbone.stem.conv.branch_3x3.bn.running_mean", "backbone.stem.conv.branch_3x3.bn.running_var", "backbone.stem.conv.branch_1x1.weight", ...`

Could anyone explain what I am doing wrong in loading the checkpoints here?

**Comment by whittenator** [comment]
@ikin5050 I am also getting the same issue!

**Comment by nrepesh** [comment]
@ikin5050 I am also getting the same issue.

**Comment by BloodAxe** [comment]
Try updating SG to latest release, where we fixed the issue of loading checkpoints and retrain your model. This should go away
