### ISSUE TITLE
 "python setup.py egg_info did not run successfully." i am trying to install super-gradients in my pycharm using pip, but i keep getting this error, and it seems it is not the fault of the pip command, can someone help me get throughh T_T

### ISSUE THREAD

**Issue by malasoren** [Deci-AI/super-gradients#1171]
### 💡 Your Question

 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\HP\AppData\Local\Temp\pip-install-txjybkht\onnx_c6d58deb48ff4b42baa245fc73569753\setup.py", line 81, in <module>
          assert CMAKE, "Could not find cmake executable!"

**Comment by ofrimasad** [comment]
Can you please provide some information on the environment?
Looks like it is working as expected on my Ubuntu machine:
```
/super-gradients/setup.py egg_info
running egg_info
writing src/super_gradients.egg-info/PKG-INFO
writing dependency_links to src/super_gradients.egg-info/dependency_links.txt
writing requirements to src/super_gradients.egg-info/requires.txt
writing top-level names to src/super_gradients.egg-info/top_level.txt
reading manifest file 'src/super_gradients.egg-info/SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'src/super_gradients.egg-info/SOURCES.txt'

Process finished with exit code 0
```

**Comment by BloodAxe** [comment]
Can you confirm that if you run installation as follows it works: `pip install super_gradients` ?

**Comment by BloodAxe** [comment]
Closing as stale
Some things that you may try if you still encounter this issue:
- Always try latest SG release
- If on windows - most of the time the problem comes from `pycocotools` dependency than must be compiled on target machine. Ensure you have build tools available. Or install matching version of pycoctools from conda if manual build is impossible
