### ISSUE TITLE
super-gradients examples for amazon sagemaker

### ISSUE THREAD

**Issue by espseongsm** [Deci-AI/super-gradients#118]
Hello, I am mainly working with amazon sagemaker for building a model. Do you have any examples or tutorial for aws? Please let me know if you have.

**Comment by oferbaratz** [comment]
Hi Soonmo,
Great question! We are working on SuperGradients integration with professional tools - one of them is Amazon SageMaker.
We will update and post an example of how to integrate once it is done.

**Comment by RamShiraziAB** [comment]
Where can i find this documentation?

**Comment by Stijnp** [comment]
Also curious to whether there is any updates on this?
