### ISSUE TITLE
How can I change the value of iou_threshold and confidence_threshold while export to onnx model?

### ISSUE THREAD

**Issue by David-19940718** [Deci-AI/super-gradients#1180]
### 💡 Your Question

As ↑ point.

**Comment by BloodAxe** [comment]
These parameters are irrelevant for ONNX export because as of now NMS is NOT part of the exported model.
However since 3.2 there will be a possibility to export model with NMS: https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/models_export.md
