### ISSUE TITLE
Training recommendations for QAT

### ISSUE THREAD

**Issue by lpkoh** [Deci-AI/super-gradients#1189]
### 💡 Your Question

The notebooks:
https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/qat_ptq_yolo_nas.md
https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/ptq_qat.md
https://colab.research.google.com/drive/1yHrHkUR1X2u2FjjvNMfUbSXTkUul6o1P?usp=sharing
describes a normal training -> PTQ -> QAT pipeline. Do you have recommendations for 'normal training' and 'QAT'? I observe it uses the same datasets. But should we have same epochs? Should the first stage of normal training use relatively fewer epochs?

**Comment by spsancti** [comment]
Hi!
Please check out `QATRecipeModificationCallback`, its default parameters implement rules of thumb on how to perform QAT given you have a "normal" training recipe.

**Comment by lpkoh** [comment]
Where can I find QATRecipeModificationCallback?

**Comment by harpreetsahota204** [comment]
Hi @lpkoh -

Thanks for opening an issue for SG. I'm gathering some feedback on SuperGradients and YOLO-NAS.

Would you be down for a quick call to chat about your experience?

If a call doesn't work for you, no worries. I've got a short survey you could fill out: https://bit.ly/sgyn-feedback.

I know you’re super busy, but your input will help us shape the direction of SuperGradients and make it as useful as possible for you.

I appreciate your time and feedback. Let me know what works for you.

Cheers,

Harpreet
