### ISSUE TITLE
How to use pre-trained model's specific class

### ISSUE THREAD

**Issue by IyshwaryaK** [Deci-AI/super-gradients#1195]
### 💡 Your Question

As in other YOLO models, where we specify model.predict(source='/content/', show=True, stream=True, classes=0), 0 indicates "Person" class. Likewise which should we modify for the YOLO-NAS to detect only a specific class. I tired modifying out = model.predict("/content/1.jpg", conf=0.25, classes=0). But, it shows TypeError: CustomizableDetector.predict() got an unexpected keyword argument 'classes'.

**Comment by BloodAxe** [comment]
This probably will be a good improvement. However as of now I cannot provide an estimate when (if at all) this will be supported. 
If someone wants to contribute we can provide instructions how to contribute. Feel free to reach out to us.
