### ISSUE TITLE
AssertionError: mixed precision is not available for CPU

### ISSUE THREAD

**Issue by xyboox** [Deci-AI/super-gradients#1201]
### 💡 Your Question

The error is thrown when attempting to train a model in a google colab. notebook ( https://drive.google.com/file/d/17rB84S9L8QxXxGVey5hm24-NHGjIJjvL/view?usp=sharing ). All the cells above ran just fine. I've attached 2 screenshots:
1. the error itself
2. the used runtime
Any hints are greatly appreciated!

<img width="812" alt="Screenshot 2023-06-21 at 16 39 58" src="https://github.com/Deci-AI/super-gradients/assets/642584/787ee817-2e50-47cf-b5c7-d071287f3d79">
<img width="823" alt="Screenshot 2023-06-21 at 16 40 37" src="https://github.com/Deci-AI/super-gradients/assets/642584/ebaebfae-22a5-4dc1-a23e-a17cdee4ea7d">

**Comment by xyboox** [comment]
@shaydeci  as it can be seen in the second screenshot I posted above, the env. idoes have GPU acceleration, of type T4. Fact is sustained by the output  [True] of torch.cuda.is_available()
<img width="366" alt="Screenshot 2023-06-21 at 22 51 10" src="https://github.com/Deci-AI/super-gradients/assets/642584/73b57ef1-8b42-4cd1-8968-86b4d338d0ff">

**Comment by BloodAxe** [comment]
Try printing actual `device_config`:
```
from super_gradients.common.environment.device_utils import device_config
print(device_config)
```
It may be that for some reason it is not picking right device

**Comment by kragrrr** [comment]
`DeviceConfig(device='cpu', multi_gpu=None, assigned_rank=-1)`

i got this as output, how do i switch to gpu?

**Comment by BloodAxe** [comment]
Can you please retry with 3.1.3? I wonder whether this is still an issue?
I will close the issue for now, feel free to re-open it if the problem still persists and we make sure it is solved.
