### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'qat'

### ISSUE THREAD

**Issue by adkbbx** [Deci-AI/super-gradients#1205]
### 💡 Your Question

I was trying to implement QA fine tuning on my dataset using the collab notebook  [Quantization Aware Training YoloNAS on Custom Dataset](https://colab.research.google.com/drive/1yHrHkUR1X2u2FjjvNMfUbSXTkUul6o1P?usp=sharing) but I am getting this attribute error.
`AttributeError: 'Trainer' object has no attribute 'qat'`
 when I run this part of the code:
` trainer.qat(model=net,training_params=train_params,train_loader=train_data,valid_loader=val_data, calib_loader=train_data) `
Do let me know if you have any suggestion for me to overcome this error.
Thank you. 

### Versions

I am running this code on google colab environment with super-gradients version 3.1.0

**Comment by spsancti** [comment]
Hi!
You need SuperGradients 3.1.2 to use this API.

**Comment by adkbbx** [comment]
Thank you for your response. I just tried to upgarde my super-gradients version to 3.1.2 but I am getting a different attribute error when I run the code to load my dataset. 
my code

```
from super_gradients.training import dataloaders
from super_gradients.training.dataloaders.dataloaders import coco_detection_yolo_format_train, coco_detection_yolo_format_val

dataset_params = {
    'data_dir':'/content/drive/MyDrive//YOLONAS/data',
    'train_images_dir':'train/images',
    'train_labels_dir':'train/labels',
    'val_images_dir':'validate/images',
    'val_labels_dir':'validate/labels',
    'test_images_dir':'test/images',
    'test_labels_dir':'test/labels',
    'classes': ["red","blue","green"]
}

from IPython.display import clear_output

train_data = coco_detection_yolo_format_train(
    dataset_params={
        'data_dir': dataset_params['data_dir'],
        'images_dir': dataset_params['train_images_dir'],
        'labels_dir': dataset_params['train_labels_dir'],
        'classes': dataset_params['classes']
    },
    dataloader_params={
        'batch_size':16,
        'num_workers':16
    }
)

val_data = coco_detection_yolo_format_val(
    dataset_params={
        'data_dir': dataset_params['data_dir'],
        'images_dir': dataset_params['val_images_dir'],
        'labels_dir': dataset_params['val_labels_dir'],
        'classes': dataset_params['classes']
    },
    dataloader_params={
        'batch_size':16,
        'num_workers':16
    }
)

test_data = coco_detection_yolo_format_val(
    dataset_params={
        'data_dir': dataset_params['data_dir'],
        'images_dir': dataset_params['test_images_dir'],
        'labels_dir': dataset_params['test_labels_dir'],
        'classes': dataset_params['classes']
    },
    dataloader_params={
        'batch_size':16,
        'num_workers':16
    }
)

clear_output()
```
error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-7-6480bcd8f926>](https://localhost:8080/#) in <cell line: 3>()
      1 from IPython.display import clear_output
      2 
----> 3 train_data = coco_detection_yolo_format_train(
      4     dataset_params={
      5         'data_dir': dataset_params['data_dir'],

8 frames
[/usr/local/lib/python3.10/dist-packages/super_gradients/training/utils/utils.py](https://localhost:8080/#) in ensure_is_tuple_of_two(inputs)
    593         return None
    594 
--> 595     if isinstance(inputs, collections.Iterable) and not isinstance(inputs, str):
    596         a, b = inputs
    597         return a, b

AttributeError: module 'collections' has no attribute 'Iterable'

```
Do let me know if you have any suggestion for me to overcome this error.
Thank you for your answer.

**Comment by adkbbx** [comment]
I was able to overcome the above error by using the solution from #1208 by changing the contents of the util.py file.

but when I run the quantization code
`trainer.qat(model=net,training_params=train_params,train_loader=train_data,valid_loader=val_data, calib_loader=train_data)`
I am getting the error

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-13-2c04fc2a753e>](https://localhost:8080/#) in <cell line: 5>()
      3 net = models.get('yolo_nas_s',num_classes=len(dataset_params['classes']),checkpoint_path="/content/drive/MyDrive/YoloNas/checkpoints/yolo_nas_s/ckpt_best.pth")
      4 
----> 5 trainer.qat(model=net,training_params=train_params,train_loader=train_data,valid_loader=val_data, calib_loader=train_data)

1 frames
[/usr/local/lib/python3.10/dist-packages/super_gradients/training/sg_trainer/sg_trainer.py](https://localhost:8080/#) in ptq(self, calib_loader, model, valid_loader, valid_metrics_list, quantization_params, deepcopy_model_for_export)
   2332         model.eval()
   2333         fuse_repvgg_blocks_residual_branches(model)
-> 2334         q_util = SelectiveQuantizer(
   2335             default_quant_modules_calibrator_weights=get_param(selective_quantizer_params, "calibrator_w"),
   2336             default_quant_modules_calibrator_inputs=get_param(selective_quantizer_params, "calibrator_i"),

NameError: name 'SelectiveQuantizer' is not defined
```
Do let me know if you have any suggestion for me to overcome this error.
Thank you for your answer.

**Comment by shaydeci** [comment]
I am closing this down as this has been addressed in https://github.com/Deci-AI/super-gradients/issues/1208 and a fix is introduced in the upcoming release.

**Comment by asifraza151** [comment]
> I was able to overcome the above error by using the solution from #1208 by changing the contents of the util.py file.
> 
> but when I run the quantization code `trainer.qat(model=net,training_params=train_params,train_loader=train_data,valid_loader=val_data, calib_loader=train_data)` I am getting the error
> 
> ```
> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> [<ipython-input-13-2c04fc2a753e>](https://localhost:8080/#) in <cell line: 5>()
>       3 net = models.get('yolo_nas_s',num_classes=len(dataset_params['classes']),checkpoint_path="/content/drive/MyDrive/YoloNas/checkpoints/yolo_nas_s/ckpt_best.pth")
>       4 
> ----> 5 trainer.qat(model=net,training_params=train_params,train_loader=train_data,valid_loader=val_data, calib_loader=train_data)
> 
> 1 frames
> [/usr/local/lib/python3.10/dist-packages/super_gradients/training/sg_trainer/sg_trainer.py](https://localhost:8080/#) in ptq(self, calib_loader, model, valid_loader, valid_metrics_list, quantization_params, deepcopy_model_for_export)
>    2332         model.eval()
>    2333         fuse_repvgg_blocks_residual_branches(model)
> -> 2334         q_util = SelectiveQuantizer(
>    2335             default_quant_modules_calibrator_weights=get_param(selective_quantizer_params, "calibrator_w"),
>    2336             default_quant_modules_calibrator_inputs=get_param(selective_quantizer_params, "calibrator_i"),
> 
> NameError: name 'SelectiveQuantizer' is not defined
> ```
> 
> Do let me know if you have any suggestion for me to overcome this error. Thank you for your answer.

i am having same error can you tell me whats the solution for it
