### ISSUE TITLE
AttributeError: 'DistributedSampler' object has no attribute 'keys'

### ISSUE THREAD

**Issue by sunmooncm** [Deci-AI/super-gradients#1210]
### 🐛 Describe the bug

setup_devices()

sampler_name = list(dataloader_params["sampler"].keys())[0]
AttributeError: 'DistributedSampler' object has no attribute 'keys'

dataloader.py
elif is_dist:
        dataloader_params["sampler"] = {"DistributedSampler": {}}
        dataloader_params = _instantiate_sampler(dataset, dataloader_params)

### Versions

is this a bug?

**Comment by shaydeci** [comment]
@sunmooncm Can you add the code snippet you are trying to launch and the full stack trace ?

**Comment by sunmooncm** [comment]
my.py
from PIL import Image
import os
import numpy as np
import torch

import random
import pathlib

from torch.utils.data import Dataset
import json
from torchvision import transforms, utils


import torch
from torch.utils.data import Dataset
import json
import os
from PIL import Image
from pathlib import Path
import cv2
import matplotlib.pyplot as plt


import os

import requests
import torch
from PIL import Image
from torch import quantization

from super_gradients.training import Trainer, dataloaders, models
from super_gradients.training.dataloaders.dataloaders import (
    coco_detection_yolo_format_train, coco_detection_yolo_format_val
)
from super_gradients.training.losses import PPYoloELoss
from super_gradients.training.metrics import DetectionMetrics_050
from super_gradients.training.models.detection_models.pp_yolo_e import (
    PPYoloEPostPredictionCallback
)
from super_gradients import init_trainer, Trainer
from super_gradients.common import MultiGPUMode
from super_gradients.training.utils.distributed_training_utils import setup_device

def main(argv=None):
    basedir = os.getcwd()
    yolo_path = os.path.join(basedir, 'data/yolo') 
    txtpath =  os.path.join(yolo_path, 'txt') 

    # Initialize the environment
    init_trainer()

        # Launch DDP on 4 GPUs'
    setup_device(multi_gpu=MultiGPUMode.DISTRIBUTED_DATA_PARALLEL, num_gpus=2)


    class config:

        #trainer params
        CHECKPOINT_DIR = 'checkpoints' #specify the path you want to save checkpoints to
        EXPERIMENT_NAME = 'knot-detector' #specify the experiment name

        #dataset params
        DATA_DIR = yolo_path #parent directory to where data lives

        TRAIN_IMAGES_DIR = 'images/train' #child dir of DATA_DIR where train images are
        TRAIN_LABELS_DIR = 'labels/train' #child dir of DATA_DIR where train labels are

        VAL_IMAGES_DIR = 'images/val' #child dir of DATA_DIR where validation images are
        VAL_LABELS_DIR = 'labels/val' #child dir of DATA_DIR where validation labels are

        # if you have a test set
        TEST_IMAGES_DIR = 'images/test' #child dir of DATA_DIR where test images are
        TEST_LABELS_DIR = 'labels/test' #child dir of DATA_DIR where test labels are

        CLASSES = [] #what class names do you have

        NUM_CLASSES = len(CLASSES)

        #dataloader params - you can add whatever PyTorch dataloader params you have
        #could be different across train, val, and test  #,
        #'sampler':{'DistributedSampler': {}}    
        DATALOADER_PARAMS={
        'batch_size':16,
        'num_workers':2
        }

        # model params
        MODEL_NAME = 'yolo_nas_s' # choose from yolo_nas_s, yolo_nas_m, yolo_nas_l
        PRETRAINED_WEIGHTS = 'coco' #only one option here: coco
    #print('xxxxxxxxxxxx: ',config.DATALOADER_PARAMS["sampler"]["DistributedSampler"])  
    
    
    train_data = coco_detection_yolo_format_train(
        dataset_params={
            'data_dir': config.DATA_DIR,
            'images_dir': config.TRAIN_IMAGES_DIR,
            'labels_dir': config.TRAIN_LABELS_DIR,
            'classes': config.CLASSES
        },
        dataloader_params=config.DATALOADER_PARAMS
    )
    val_data = coco_detection_yolo_format_val(
        dataset_params={
            'data_dir': config.DATA_DIR,
            'images_dir': config.VAL_IMAGES_DIR,
            'labels_dir': config.VAL_LABELS_DIR,
            'classes': config.CLASSES
        },
        dataloader_params=config.DATALOADER_PARAMS
    )
    test_data = coco_detection_yolo_format_val(
        dataset_params={
            'data_dir': config.DATA_DIR,
            'images_dir': config.TEST_IMAGES_DIR,
            'labels_dir': config.TEST_LABELS_DIR,
            'classes': config.CLASSES
        },
        dataloader_params=config.DATALOADER_PARAMS
    )
    #===============================================
    model = models.get(config.MODEL_NAME, 
                   num_classes=config.NUM_CLASSES, 
                   pretrained_weights=config.PRETRAINED_WEIGHTS
                   )
    train_params = {
    # ENABLING SILENT MODE
    "average_best_models":True,
    "warmup_mode": "linear_epoch_step",
    "warmup_initial_lr": 1e-5,
    "lr_warmup_epochs": 5,
    "initial_lr": 3e-4,
    "lr_mode": "cosine",
    "cosine_final_lr_ratio": 0.1,
    "optimizer": "Adam",
    "optimizer_params": {"weight_decay": 0.0001},
    "zero_weight_decay_on_bias_and_bn": True,
    "ema": True,
    "ema_params": {"decay": 0.9, "decay_type": "threshold"},
    # ONLY TRAINING FOR 10 EPOCHS FOR THIS EXAMPLE NOTEBOOK======================================
    "max_epochs": 15,
    "mixed_precision": True,       #True gpu
    "loss": PPYoloELoss(
        use_static_assigner=False,
        # NOTE: num_classes needs to be defined here
        num_classes=config.NUM_CLASSES,
        reg_max=16
    ),
    "valid_metrics_list": [
        DetectionMetrics_050(
            score_thres=0.1,
            top_k_predictions=300,
            # NOTE: num_classes needs to be defined here
            num_cls=config.NUM_CLASSES,
            normalize_targets=True,
            post_prediction_callback=PPYoloEPostPredictionCallback(
                score_threshold=0.01,
                nms_top_k=1000,
                max_predictions=300,
                nms_threshold=0.7
            )
        )
    ],
    "metric_to_watch": 'mAP@0.50'
    }    
    trainer = Trainer(experiment_name='knot-detector', ckpt_root_dir='checkpoints')
    # Call the trainer

    trainer.train(model=model, 
              training_params=train_params, 
              train_loader=train_data, 
              valid_loader=val_data)
if __name__ == "__main__":
    main()
==================wrong

Traceback (most recent call last):
  File "/home/yazcy1248/2023/yolonas/train_nas.py", line 182, in <module>
    main()
  File "/home/yazcy1248/2023/yolonas/train_nas.py", line 102, in main
    val_data = coco_detection_yolo_format_val(
  File "/home/yazcy1248/anaconda3/envs/yolonas/lib/python3.9/site-packages/super_gradients/training/dataloaders/dataloaders.py", line 336, in coco_detection_yolo_format_val
    return get_data_loader(
  File "/home/yazcy1248/anaconda3/envs/yolonas/lib/python3.9/site-packages/super_gradients/training/dataloaders/dataloaders.py", line 80, in get_data_loader
    dataloader_params = _process_dataloader_params(cfg, dataloader_params, dataset, train)
  File "/home/yazcy1248/anaconda3/envs/yolonas/lib/python3.9/site-packages/super_gradients/training/dataloaders/dataloaders.py", line 133, in _process_dataloader_params
    dataloader_params = _process_sampler_params(dataloader_params, dataset, default_dataloader_params)
  File "/home/yazcy1248/anaconda3/envs/yolonas/lib/python3.9/site-packages/super_gradients/training/dataloaders/dataloaders.py", line 158, in _process_sampler_params
    dataloader_params = _instantiate_sampler(dataset, dataloader_params)
  File "/home/yazcy1248/anaconda3/envs/yolonas/lib/python3.9/site-packages/super_gradients/training/dataloade**rs/dataloaders.py**", line 194, in _instantiate_sampler
    sampler_name = list(dataloader_params["sampler"].keys())[0]
AttributeError: 'DistributedSampler' object has no attribute 'keys'

**Comment by sunmooncm** [comment]
dataloaders.py
def _process_sampler_params(dataloader_params, dataset, default_dataloader_params):
    is_dist = super_gradients.is_distributed()
    dataloader_params = override_default_params_without_nones(dataloader_params, default_dataloader_params)    
    if get_param(dataloader_params, "sampler") is not None:
        dataloader_params = _instantiate_sampler(dataset, dataloader_params)        
    elif is_dist:
        dataloader_params["sampler"] = {"DistributedSampler": {}}
        dataloader_params = _instantiate_sampler(dataset, dataloader_params)
        if get_param(dataloader_params, "min_samples") is not None:
            min_samples = dataloader_params.pop("min_samples")
            if len(dataset) < min_samples:
                world_size = dist.get_world_size()
                num_repeats = min_samples / len(dataset)
                selected_ratio = world_size / num_repeats
...

**Comment by MoShuangYe** [comment]
Hello, is this problem solved? I also encountered the same error.
