### ISSUE TITLE
bad experience for this project predict image and video

### ISSUE THREAD

**Issue by futureflsl** [Deci-AI/super-gradients#1212]
### 🐛 Describe the bug

I use for this project for the first time,But I find that this project code is not easy to use.I try run predict image,but predict with cuda not work.then I run video predict,I find is is slow.if this project can modify the predict style like yolov5/yolov7/yolov8,it will be nice.as far as I am concerned，This project is not very friendly to those who have just come into contact with it。

### Versions

sg=3.1.2

**Comment by Louis-Dupont** [comment]
Hi @futureflsl ,

Thanks for your feedback, as I just answered in your this issue (https://github.com/Deci-AI/super-gradients/issues/1211), I think you may be using a too-complex setup for your use-case, let me know if it helps. If so, we will work on improving the documentation to clarify this confusion :)

Concerning speed, our `predict` method is meant for simplicity, and quick testing. For production and high-performance setting, we strongly recommend quantizing the model and working on inference engines. This is more work to set up, but yields to a strong increase of performance. If you are interested, I invite you to check this [page](https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/BenchmarkingYoloNAS.md)

Hoping this helps
