### ISSUE TITLE
I'm stuck in trainning yolo_nas_s on my own dataset

### ISSUE THREAD

**Issue by futureflsl** [Deci-AI/super-gradients#1215]
### 💡 Your Question

I follow How to Connect Custom Dataset Detection How to Connect Custom Dataset
and write code:

from super_gradients.training import Trainer
from super_gradients.training.utils.ssd_utils import DefaultBoxes
from PIL import Image
import numpy as np
import torch
from super_gradients.training import models
from torch.utils.data import Dataset, DataLoader
from super_gradients.training.utils.detection_utils import DetectionCollateFN
from super_gradients.common.object_names import Models
from super_gradients.training import training_hyperparams
from prettyformatter import pprint

\# Anchors
def dboxes():
    figsize = 96
    feat_size = [6, 3, 2, 1]
    scales = [9, 36, 64, 91, 96]
    aspect_ratios = [[2], [2], [2], [2]]
    return DefaultBoxes(figsize, feat_size, scales, aspect_ratios)

def base_detection_collate_fn(batch):
    """
    Simple aggregation function to batched the data
    """

    images_batch, labels_batch = list(zip(*batch))
    for i, labels in enumerate(labels_batch):
        # ADD TARGET IMAGE INDEX
        labels[:, 0] = i

    return torch.stack(images_batch, 0), torch.cat(labels_batch, 0)

class YoloDataset(Dataset):
    """
    A PyTorch Dataset class to be used in a PyTorch DataLoader to create batches.
    """

    def __init__(self, txt_file, keep_difficult=False, input_size=640):
        """
        :param data_folder: folder where data files are stored
        :param split: split, one of 'TRAIN' or 'TEST'
        :param keep_difficult: keep or discard objects that are considered difficult to detect?
        """
        self.input_size = input_size
        self.keep_difficult = keep_difficult
        # Read data files
        with open(txt_file, 'r') as f:
            self.images = f.read().rstrip('\n').split('\n')

    def __getitem__(self, i):
        # Read image and label
        image = Image.open(self.images[i], mode='r').resize((self.input_size, self.input_size))
        image_tensor = torch.tensor(np.array(image)).permute(2, 0, 1).float()
        labels = np.loadtxt(self.images[i].replace("jpg", "txt").replace("JPEGImages", "labels"))
        return image_tensor, labels

    def __len__(self):
        return len(self.images)

if \_\_name\_\_ == '\_\_main\_\_':
    train_dataset = YoloDataset(r'D:\firc\yolov5-5.0-train-firc\myproj\config\train.txt')
    val_dataset = YoloDataset(r'D:\firc\yolov5-5.0-train-firc\myproj\config\val.txt')
    train_dataloader = DataLoader(train_dataset, batch_size=1, shuffle=True, num_workers=1, collate_fn=DetectionCollateFN())
    val_dataloader = DataLoader(val_dataset, batch_size=1, shuffle=False, num_workers=1, collate_fn=DetectionCollateFN())

    CHECKPOINT_DIR = './runs/'
    trainer = Trainer(experiment_name='transfer_learning_object_detection_yolo_nas_s', ckpt_root_dir=CHECKPOINT_DIR)

    model = models.get(Models.YOLO_NAS_S, pretrained_weights="coco", num_classes=80)
    print(model.num_classes)

    train_params = training_hyperparams.get('coco2017_yolo_nas_s')
    print('Training parameters:')
    pprint(train_params, json=True)
    train_params['max_epochs'] = 5
    train_params['lr_warmup_epochs'] = 0
    train_params['lr_cooldown_epochs'] = 0
    train_params['criterion_params']['num_classes'] = 80
    train_params['average_best_models'] = False
    train_params['initial_lr'] = 0.0005
    train_params['cosine_final_lr_ratio'] = 0.9
    train_params['mixed_precision'] = False

    trainer.train(model=model, training_params=train_params, train_loader=train_dataloader, valid_loader=val_dataloader)

but error occured:
Training parameters:
{
    "resume"    : null,
    "resume_path"       : null,
    "resume_from_remote_sg_logger"      : false,
    "ckpt_name" : "ckpt_latest.pth",
    "lr_mode"   : "cosine",
    "lr_schedule_function"  : null,
    "lr_warmup_epochs"  : 0,
    "lr_warmup_steps"   : 1000,
    "lr_cooldown_epochs": 0,
    "warmup_initial_lr" : 1e-06,
    "step_lr_update_freq"   : null,
    "cosine_final_lr_ratio" : 0.1,
    "warmup_mode"       : "linear_batch_step",
    "lr_updates": [],
    "pre_prediction_callback"   : null,
    "optimizer" : "AdamW",
    "optimizer_params"  : {"weight_decay": 1e-05},
    "load_opt_params"   : true,
    "zero_weight_decay_on_bias_and_bn"  : true,
    "loss"      : {"ppyoloe_loss": {"use_static_assigner": false, "num_classes": 80, "reg_max": 16}},
    "criterion_params"  : {},
    "ema"       : true,
    "ema_params": {"decay": 0.9997, "decay_type": "threshold", "beta": 15},
    "train_metrics_list": [],
    "valid_metrics_list":
        [
            {
                "DetectionMetrics":
                    {
                        "score_thres"       : 0.1,
                        "top_k_predictions" : 300,
                        "num_cls"   : 80,
                        "normalize_targets" : true,
                        "post_prediction_callback"  : PPYoloEPostPredictionCallback()
                    }
            }
        ],
    "metric_to_watch"   : "mAP@0.50:0.95",
    "greater_metric_to_watch_is_better" : true,
    "launch_tensorboard": false,
    "tensorboard_port"  : null,
    "tb_files_user_prompt"  : false,
    "save_tensorboard_to_s3": false,
    "precise_bn": false,
    "precise_bn_batch_size" : null,
    "sync_bn"   : true,
    "silent_mode"       : false,
    "mixed_precision"   : true,
    "save_ckpt_epoch_list"  : [100, 200, 250],
    "average_best_models"   : true,
    "dataset_statistics": false,
    "batch_accumulate"  : 1,
    "run_validation_freq"   : 1,
    "save_model": true,
    "seed"      : 42,
    "phase_callbacks"   : [],
    "log_installed_packages": true,
    "clip_grad_norm"    : null,
    "ckpt_best_name"    : "ckpt_best.pth",
    "max_train_batches" : null,
    "max_valid_batches" : null,
    "sg_logger" : "base_sg_logger",
    "sg_logger_params":
        {
            "tb_files_user_prompt"      : false,
            "launch_tensorboard": false,
            "tensorboard_port"  : null,
            "save_checkpoints_remote"   : false,
            "save_tensorboard_remote"   : false,
            "save_logs_remote"  : false,
            "monitor_system"    : true
        },
    "_convert_" : "all",
    "max_epochs": 300,
    "initial_lr": 0.0002
}
The console stream is now moved to ./runs/transfer_learning_object_detection_yolo_nas_s/console_6月27_15_36_39.txt
[2023-06-27 15:36:41] INFO - sg_trainer.py - Using EMA with params {'decay': 0.9997, 'decay_type': 'threshold', 'beta': 15}
[2023-06-27 15:36:41] WARNING - callbacks.py - Number of warmup steps (1000) is greater than number of steps in epoch (270). Warmup steps will be capped to number of steps in epoch to avoid interfering with any pre-epoch LR schedulers.
[2023-06-27 15:36:58] ERROR - sg_trainer_utils.py - Uncaught exception
Traceback (most recent call last):
  File "D:\pythonspace\supergradients_object_detection_how_to_connect_custom_dataset.py", line 89, in <module>
    trainer.train(model=model, training_params=train_params, train_loader=train_dataloader, valid_loader=val_dataloader)
  File "D:\anaconda3\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 1237, in train
    first_batch = next(iter(self.train_loader))
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "D:\anaconda3\lib\site-packages\torch\_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\anaconda3\lib\site-packages\super_gradients\training\utils\detection_utils.py", line 669, in __call__
    return ims, self._format_targets(targets)
  File "D:\anaconda3\lib\site-packages\super_gradients\training\utils\detection_utils.py", line 672, in _format_targets
    nlabel = (targets.sum(dim=2) > 0).sum(dim=1)  # number of label per image
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Traceback (most recent call last):
  File "D:\pythonspace\supergradients_object_detection_how_to_connect_custom_dataset.py", line 89, in <module>
    trainer.train(model=model, training_params=train_params, train_loader=train_dataloader, valid_loader=val_dataloader)
  File "D:\anaconda3\lib\site-packages\super_gradients\training\sg_trainer\sg_trainer.py", line 1237, in train
    first_batch = next(iter(self.train_loader))
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "D:\anaconda3\lib\site-packages\torch\_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\anaconda3\lib\site-packages\super_gradients\training\utils\detection_utils.py", line 669, in __call__
    return ims, self._format_targets(targets)
  File "D:\anaconda3\lib\site-packages\super_gradients\training\utils\detection_utils.py", line 672, in _format_targets
    nlabel = (targets.sum(dim=2) > 0).sum(dim=1)  # number of label per image
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

my dataset format is yolo like:

![360截图20230627154430235](https://github.com/Deci-AI/super-gradients/assets/23259315/d8c1b6bd-429c-455e-a0f1-477053775481)

### Versions

super-gradients==3.1.2
windows10 x64

**Comment by BloodAxe** [comment]
In 3.1.3 we introduced a `YoloDarknetFormatDetectionDataset` which I believe should fit your needs.

**Comment by Arbaaz-Shaikh** [comment]
But what about SSD model. 
How to calculate the SSDLoss(dboxes= DefaultBoxes)

how to calculate this.

please help in this asap or is this a bug?

dataset Prep:

train_data = coco_detection_yolo_format_train (
dataset_params={
"data_dir": dataset_params ["data_dir"],
"images_dir": dataset_params ["train_
_images_dir"],
"labels _dir": dataset_params ["train_labels_dir"],
"classes": dataset_params ["classes"],

dataloader_params={
'batch
_size': BATCH_SIZE,
'num_workers' : WORKERS
val_data = coco_detection_yolo_format_val (
dataset_params=‹
"data_dir": dataset_params l"data_dir"],
"images_dir": dataset_params ["val
_images_dir"],
"labels_dir": dataset_params ["val_labels_dir"],
"classes": dataset_params ["classes"],
dataloader_params={
'batch_size': BATCH_SIZE,
'num_workers': WORKERS
｝，

test.
_data = coco_detection_yolo_format_val(
dataset_params={
"data_dir": dataset_params ["datadir"],
"images_dir": dataset_params ["test_
_images_dir"],
"labels_dir": dataset_params ["test_labels_dir"],
"classes": dataset_params ["classes"],
dataloader_params={
'batch_size': BATCH_SIZE,
'num_workers': WORKERS
｝

Training parameters prep:

# Set the training parameters
train_params = {
'max_epochs': MAX_EPOCHS,
'Ir_mode': 'CosineLRScheduler',
'optimizer': 'SGD'
optimizer_params'! {'momentum': 0.9, 'weight_decay': 0.0005, 'nesterov': True},
'loss': SSDLoss (dboxes= DefaultBoxes) ,
'valid
_metrics_list': [
{'DetectionMetrics': {'post_prediction_callback': SSDPostPredictCallback(),
'num_cls': len (dataset_params ['classes'])}}1,
'metric_to_watch': mAP@0.50:0.95',
'average_best_models': True,
'initial_lr': 0.01,
'warmup_momentum' : 0.8,
'warmup_bias_lr': 0.1,

Any help will be appreciated:

DefaultBoxes ?

![image](https://github.com/Deci-AI/super-gradients/assets/52887465/c111fa8a-6f6e-447b-85ad-f135236866d4)
