### ISSUE TITLE
Anyone successfully installed Yolo-nas on a closed network with no Internet connection?

### ISSUE THREAD

**Issue by whnam87** [Deci-AI/super-gradients#1216]
### 💡 Your Question

I have an Ubuntu container environment provided by my company, but this is a closed network with no Internet connection.

The container environment is running Python 3.8 with tf 2.4.0, torch 1.9.0, cuda 11.1 on Ubuntu 20.04 on AMD64 and has high-end hardware installed: Nvidia A100 80GB x 3 without internet connection. So I cannot use the 'apt-get' or 'pip install' command with the Internet connection. 

The Ultralytics requires many dependencies, but anyone who has successfully installed Yolo-nas on a closed network can share the way?

**Comment by Louis-Dupont** [comment]
Hi @whnam87 
If you don't have control over the container building and don't have access to the internet then I don't see a clean and simple way to handle that.
I guess a workaround may be to setup a python virtual env on a device with internet, download and install everything needed there, then copy these to the device running the container, and finally build a volume mapping to these files when launching the container. This assumes that you have write access to the device where you want to run all of this.

**Comment by whnam87** [comment]
Not solved
