### ISSUE TITLE
Getting bbox from model.predict()

### ISSUE THREAD

**Issue by mikelmujika11** [Deci-AI/super-gradients#1219]
### 💡 Your Question

Hi,

I am using YOLO-NAS to perform some object detection and to compare it with YOLOv5 and YOLOv8. I am trying to get the bbox, confidence, label... of the predictions, like in the YOLOv5 or YOLOv8. How can I obtain these metrics?

Thank you,

Mikel

**Comment by BloodAxe** [comment]
Please check https://github.com/Deci-AI/super-gradients/issues/907 where this question has been answered

**Comment by harpreetsahota204** [comment]
Hi @mikelmujika11 -

Thanks for opening an issue for SG. I'm gathering some feedback on SuperGradients and YOLO-NAS.

Would you be down for a quick call to chat about your experience?

If a call doesn't work for you, no worries. I've got a short survey you could fill out: https://bit.ly/sgyn-feedback.

I know you’re super busy, but your input will help us shape the direction of SuperGradients and make it as useful as possible for you.

I appreciate your time and feedback. Let me know what works for you.

Cheers,

Harpreet
