### ISSUE TITLE
Multiple metrics in training

### ISSUE THREAD

**Issue by MaxEAB** [Deci-AI/super-gradients#1231]
### 💡 Your Question

Hi, Is there a way to assign multiple metrics in training for a network with multiple output branches? 

I changed the segmentation network to include a regression head, and I want to assign metrics such that the segmentation head uses IOU and the regression head uses MeanSquaredError. 

(The single output trainer currently uses "IOU" alone.)

Thank you!

**Comment by BloodAxe** [comment]
As of now there is no _easy_ way to achieve this.
