### ISSUE TITLE
Obtain metrics per class on custom dataset

### ISSUE THREAD

**Issue by Leo-Thomas** [Deci-AI/super-gradients#1235]
### 💡 Your Question

Hello,

Is there any way to get the metrics results for each class in the dataset?

I am training YOLO-NAS on a two class custom dataset, and it would be very useful to have the model performance for each class. Something similar to what YOLOv5 and YOLOv8 show:

![example](https://github.com/Deci-AI/super-gradients/assets/91854676/cf0a0451-5966-4c82-ae22-18c4214a287f)

Thanks in advance for any help

**Comment by BloodAxe** [comment]
The PR with this change is merged in master and should be available in the next SG release.
Or you can install master branch from git and use it today.
You will need to provide `include_classwise_ap: True` for `DetectionMetric` class in YAML (Or via code) and (optionally) class names.

**Comment by gsrujana** [comment]
I got an error while trying to add this:
`        DetectionMetrics_050_095(
            score_thres=0.1,
            top_k_predictions=300,
            num_cls=107,
            normalize_targets=True,
            include_classwise_ap=True,
            post_prediction_callback=PPYoloEPostPredictionCallback(
                score_threshold=0.01,
                nms_top_k=1000,
                max_predictions=300,
                nms_threshold=0.7
            )`

**Comment by gsrujana** [comment]
Hi, which version to download to get this feature? I have 3.1.1

**Comment by dengbuqi** [comment]
@gsrujana I have tried on 3.5.0, It works~

**Comment by proevgenii** [comment]
@BloodAxe @dengbuqi 
Is there a way to get per class Precision, Recall and F1(like in initial question) ?
`param include_classwise_ap` - only add AP per class metrics
