### ISSUE TITLE
Detecting limited number of objects

### ISSUE THREAD

**Issue by shameem198** [Deci-AI/super-gradients#1242]
### 💡 Your Question

Hi,

I'm fine tuning coco object detection for my custom dataset. It is giving pretty good results for samples where target bbox are less and facing missing bbox when I have more objects in the image.

is there any parameter which I can tune to overcome this issue?

**Comment by BloodAxe** [comment]
There isn't. You can increasing confidence threshold to keep only the most confident ones though.

**Comment by shameem198** [comment]
> You can increasing confidence threshold to keep only the most confident ones though.

I tried to tweak confidence, the objects are missing with less confidence. I think its because of some other parameter

**Comment by BloodAxe** [comment]
Providing at least a code snippet you're using to predict (Or ideally a model checkpoint and the image) would definitely help us to check whether there is some sort of bug or not.
Without such information it is impossible to address your problem. 
I'm closing this issue for now, please re-open it if you are ready to provide additional information.
