### ISSUE TITLE
About the computational complexity (GFLOPs) of the yolo-nas_s

### ISSUE THREAD

**Issue by xiaohangguo** [Deci-AI/super-gradients#1246]
### 💡 Your Question

Hello, great job! I would like to inquire about the computational complexity (GFLOPs) of the yolo-nas_s model. Or, what parameters do I need to reference in order to see it while parsing the model?

**Comment by BloodAxe** [comment]
Currently we do not have mechanism to compute GFLOPs complexity. 
However we are open to PRs that may allow computing it.
