### ISSUE TITLE
Rectangular training

### ISSUE THREAD

**Issue by AmanSP0044** [Deci-AI/super-gradients#1249]
### 🚀 Feature Request

Want to train YoloNAS model on rectangular images similar to yolov5 and yolov8 (https://github.com/ultralytics/yolov5/issues/2009)

**Comment by BloodAxe** [comment]
What in particular you are missing from existing training pipeline that
already train in 640x640 (resizing + pad with aspect ratio preserving)?

чт, 6 лип. 2023 р. о 15:26 AmanSP0044 ***@***.***> пише:

**Comment by AmanSP0044** [comment]
I want to train with rectangular image sizes having aspect ratio in proportion to stride size, similar to yolov5 --rect parameter.
The training image will look like this.
![image](https://github.com/Deci-AI/super-gradients/assets/120374995/fb89f3bf-e059-4845-91a6-43719c49ce35)

**Comment by BloodAxe** [comment]
You can change dataset parameters and set size of images for train and validation to arbitrarily size: https://github.com/Deci-AI/super-gradients/blob/f49a35811638905bbe9b19d4521aa39891315d43/src/super_gradients/recipes/dataset_params/coco_detection_yolo_nas_dataset_params.yaml#L5

Note you probably have to change the input sim in all relevant transforms as well.
