### ISSUE TITLE
how to generate precision-recall curve, F1 curve in yolo nas?

### ISSUE THREAD

**Issue by absmahi01** [Deci-AI/super-gradients#1255]
### 💡 Your Question

I trained yolo nas on my custom dataset & the epoch number was 300. After testing the model with test data, i didn't get precesion recall curve. What is the solution of it?

**Comment by oussaifi-majdi** [comment]
you should use tensorboard 

CHECKPOINT_DIR='....'
EXPERIMENT_NAME='.....'
%load_ext tensorboard
%tensorboard --logdir {CHECKPOINT_DIR}/{EXPERIMENT_NAME} --port 6005
%reload_ext tensorboard

**Comment by BloodAxe** [comment]
As for PR curve - indeed we do not generate it.
We do however log F1, precision & recall plots per epoch
