### ISSUE TITLE
Inference on CPU with QAT training from onnx model 

### ISSUE THREAD

**Issue by anantgupta129** [Deci-AI/super-gradients#1261]
### 💡 Your Question

I want to run qat trained model on custom dataset.  I have used this [documentation](https://github.com/Deci-AI/super-gradients/blob/c339e2619616878172c060e6491c8c2129ed3fd4/documentation/source/ptq_qat.md) for training the model but unable to figure out how to use the qat.onnx model 

I have tried onnxruntime here is the code 

```python

import onnx
import onnxruntime
import torch

tmp_model_path = "<model_path>_m_qat_16x3x640x640_qat.onnx"
onnx_model = onnx.load(tmp_model_path)
onnx.checker.check_model(onnx_model)

ort_session = onnxruntime.InferenceSession(tmp_model_path, providers=["CUDAExecutionProvider", "CPUExecutionProvider"])

x = torch.randn(1, 3, 640, 640, requires_grad=False)

ort_inputs = {ort_session.get_inputs()[0].name: x.cpu().numpy()}
ort_outs = ort_session.run(None, ort_inputs)
```

output 
```bash
---------------------------------------------------------------------------
InvalidArgument                           Traceback (most recent call last)
Cell In[14], line 4
      1 x = torch.randn(1, 3, 640, 640, requires_grad=False)
      3 ort_inputs = {ort_session.get_inputs()[0].name: x.cpu().numpy()}
----> 4 ort_outs = ort_session.run(None, ort_inputs)

File [~/miniconda3/envs/qat/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:200](https://vscode-remote+ssh-002dremote-002bgpu.vscode-resource.vscode-cdn.net/home/watcherai/.dev/super-gradients/checkpoints/vehicle_detection_yolo_nas_m_qat/~/miniconda3/envs/qat/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:200), in Session.run(self, output_names, input_feed, run_options)
    198     output_names = [output.name for output in self._outputs_meta]
    199 try:
--> 200     return self._sess.run(output_names, input_feed, run_options)
    201 except C.EPFail as err:
    202     if self._enable_fallback:

InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: inputs.1 for the following indices
 index: 0 Got: 1 Expected: 16
 Please fix either the inputs or the model.
```

**Comment by SamratThapa120** [comment]
`x = torch.randn(1, 3, 640, 640, requires_grad=False)`

You need to change this part to what is specified in the filename for the onnx model <model_path>_m_qat_16x3x640x640_qat.onnx

`x = torch.randn(16, 3, 640, 640, requires_grad=False)`

Check the following link if you want to change the batch size
https://github.com/onnx/onnx/issues/2182

Or try rebuilding the model with batch size 1

**Comment by anantgupta129** [comment]
i trained quantization aware training using this [documentation](https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/qat_ptq_yolo_nas.md)  how to change batch size here while exporting onnx model ?

**Comment by SamratThapa120** [comment]
You can try setting the validation batch size to 1.

https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/training/sg_trainer/sg_trainer.py#L2374

**Comment by anantgupta129** [comment]
Thanks one more question I tried running onnx model on CPU but it took around 3 to 4 sec on 1 image. Is achieving higher fps not possible without trt conversion. 

Can I achieve fps on cpu

**Comment by BloodAxe** [comment]
This is how you can export model to ONNX with quantization https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/examples/model_export/models_export.ipynb
