### ISSUE TITLE
How can I train the model with multi nodes multi gpus and is there any modification when it is on the slurm ?

### ISSUE THREAD

**Issue by AlfredQin** [Deci-AI/super-gradients#1262]
### 💡 Your Question

Hi, thanks for your excellent work! I used the example code of Distributed Data Parallel(DDP) training provided by super-gradients and it worked well on a single machine with multiple gpus. But I want to konw how can I implement DDP training using multi-nodes multi-gpus. Besides, is it feasible to use super-gradients on slurm? Thank you !

**Comment by shaydeci** [comment]
Hey @AlfredQin multi-node training is not officially supported yet.
We do plan to add support for it in the future.

**Comment by BloodAxe** [comment]
Closing for now, since we unable to provide accurate time estimate when this be released
