### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Iterable'

### ISSUE THREAD

**Issue by tivivui95** [Deci-AI/super-gradients#1267]
### 🐛 Describe the bug

error while using the `coco_detection_yolo_format_train` in version 3.1.2

```
 File "/home/van/miniconda3/lib/python3.10/site-packages/super_gradients/training/utils/utils.py", line 595, in ensure_is_tuple_of_two
    if isinstance(inputs, collections.Iterable) and not isinstance(inputs, str):
AttributeError: module 'collections' has no attribute 'Iterable'
```
I've added a quick fix by replacing `collections.Iterable` with `collections.abc.Iterable` in the utils file in `training/utils/utils.py` and it worked.
``` python
if isinstance(inputs, collections.abc.Iterable) and not isinstance(inputs, str):
        a, b = inputs
        return a, b
```

### Versions

3.1.2

**Comment by Louis-Dupont** [comment]
Hi @tivivui95 ,
Thanks for the report, it was actually fixed in the master branch and will be in the next release (3.1.3) which should come out soon.

**Comment by tivivui95** [comment]
Thank you very much.
