### ISSUE TITLE
Hide the labels in the results

### ISSUE THREAD

**Issue by YYazidd** [Deci-AI/super-gradients#1268]
### 💡 Your Question

Hi, is there any way to hide the labels from the returned image
When i use model.predict() the returned image contained the bounding box with the labels of the class, i want to hide the labels from the image
and also is there is any way to make the line width of the bounding box smaller

**Comment by harpreetsahota204** [comment]
Hi @YYazidd 

Thanks for opening an issue for SG. I'm gathering some feedback on SuperGradients and YOLO-NAS.

Would you be down for a quick call to chat about your experience?

If a call doesn't work for you, no worries. I've got a short survey you could fill out: https://bit.ly/sgyn-feedback.

I know you’re super busy, but your input will help us shape the direction of SuperGradients and make it as useful as possible for you.

I appreciate your time and feedback. Let me know what works for you.

Cheers,

Harpreet
