### ISSUE TITLE
How to save yolo-nas predictions into my workspace?

### ISSUE THREAD

**Issue by ahmad2246** [Deci-AI/super-gradients#1270]
### 💡 Your Question

This is the first time I'm posting a question, so I'm sorry if I'm violating any rule
 
I'm using the yolo-nas code offered by [Deci ](https://deci.ai/blog/yolo-nas-object-detection-foundation-model/)on a custom dataset

and i want to know how can i save the label predictions into my workspace 
 
I don't want to save images containing detection boxes
I just want to save the labels (txt files)

a label (txt file) should contain: class  x-center  y-center  width  height

**Comment by Louis-Dupont** [comment]
Hi @ahmad2246 
We don't have a pre-made script for this, but you can build one on top of SG.

I invite you to have a look at [this page](https://docs.deci.ai/super-gradients/documentation/source/ModelPredictions.html#detect-objects-in-multiple-images), it explains how to iterate over each predicted image. With this, you can easily do any filtering/transformation you want over the predictions to fit your need.
Hoping this helps
