### ISSUE TITLE
How to change batch_size for model.predict for YOLO-NAS?

### ISSUE THREAD

**Issue by Allison2324** [Deci-AI/super-gradients#1272]
How to change batch_size for model.predict for YOLO-NAS?

As I can see it's 32 by default. I need to change it.

**Comment by Louis-Dupont** [comment]
Hi @Allison2324 
I opened a [PR](https://github.com/Deci-AI/super-gradients/pull/1273) to add this as an option to the `model.predict` method.
Until this is merged/released, you can go for one of the two workarounds:
- Install SG from this branch pip install git+https://github.com/Deci-AI/super-gradients@hotfix/SG-000-add_batch_size. Then just call `model.predict(IMAGES, batch_size=8)`. 
    - Note: This branch is not an official release
- Bypass `model.predict` by using our internal API as below. 
    - Note: The internal API can always change so this is not recommended for production environment

``` python

pipeline = model._get_pipeline()  # Same API as `model.predict()`
predictions = pipeline(IMAGES, batch_size=8)
...
```

**Comment by Louis-Dupont** [comment]
@Allison2324 The parameter `batch_size` was added in this [PR](https://github.com/Deci-AI/super-gradients/pull/1273) which was merged. The feature is available on the master branch and will be part of the next release `3.1.3`.

**Comment by harpreetsahota204** [comment]
Hi @Allison2324 -

Thanks for opening an issue for SG. I'm gathering some feedback on SuperGradients and YOLO-NAS.

Would you be down for a quick call to chat about your experience?

If a call doesn't work for you, no worries. I've got a short survey you could fill out: https://bit.ly/sgyn-feedback.

I know you’re super busy, but your input will help us shape the direction of SuperGradients and make it as useful as possible for you.

I appreciate your time and feedback. Let me know what works for you.

Cheers,

Harpreet
