### ISSUE TITLE
How can I use MPS (Apple Silicon) for YOLO-NAS inference?

### ISSUE THREAD

**Issue by oscarwzt** [Deci-AI/super-gradients#1285]
### 💡 Your Question

I ran the following code and got: ```RuntimeError: Currently topk on mps works only for k<=16 ```
```python
from super_gradients.training import models

model = models.get("yolo_nas_s", pretrained_weights="coco")
model.to("mps")
model.predict("/Users/oscarwan/bballDetection/videos/v2Test.mov")
```

```model.to("mps")``` did not cause any problems, so I think something went wrong in inferencing. 

I looked at [Thtis post](https://github.com/pytorch/pytorch/issues/78915) and a few related one about the same error, but found no solution.

### Versions

PyTorch version: 2.1.0.dev20230716
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.12 (main, Jul  5 2023, 15:34:07) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==2.1.0.dev20230716
[pip3] torchaudio==2.1.0.dev20230716
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.16.0.dev20230716
[conda] blas                      1.0                         mkl  
[conda] mkl                       2023.1.0         h59209a4_43558  
[conda] mkl-service               2.4.0           py310h6c40b1e_1  
[conda] mkl_fft                   1.3.6           py310h3ea8b11_1  
[conda] mkl_random                1.2.2           py310h3ea8b11_1  
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] pytorch                   2.1.0.dev20230716        py3.10_0    pytorch-nightly
[conda] torchaudio                2.1.0.dev20230716       py310_cpu    pytorch-nightly
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchvision               0.16.0.dev20230716       py310_cpu    pytorch-nightly

**Comment by BloodAxe** [comment]
As of now it seems your only option is to use `cpu` device on mac. I don't feel this issue directly related to YOLO-NAS. We use topk in postprocessing step. 
It looks like `torch.topk` support for `mps` device is limited. You can try filling a bugreport on torch repo.

**Comment by ZYX-MLer** [comment]
Do you have any plans to support MPS acceleration on macOS?
