### ISSUE TITLE
How to generate a Classification report and confusion matrix for yolo-nas model

### ISSUE THREAD

**Issue by kumarsyamala** [Deci-AI/super-gradients#1306]
### 🚀 Feature Request

I am using yolo-nas model and trying to use different model architecture.

So is there a way to generate a classification report and confusion matrix for each model to evaluate it decide which model and parameters are good and use that to prediction.

**Comment by BloodAxe** [comment]
This is not implemented. You probably need to write you own code to summarize this.

**Comment by harpreetsahota204** [comment]
Hi @kumarsyamala 

Thanks for opening an issue for SG.  I'm gathering some feedback on SuperGradients and YOLO-NAS.   

Would you be down for a quick call to chat about your experience?

If a call doesn't work for you, no worries. I've got a short survey you could fill out: https://bit.ly/sgyn-feedback.

I know you’re super busy, but your input will help us shape the direction of SuperGradients and make it as useful as possible for you.

I appreciate your time and feedback. Let me know what works for you.   

Cheers, 
Harpreet
