### ISSUE TITLE
Inference time is lesser for pytorch fp32 than pytorch fp16

### ISSUE THREAD

**Issue by PrajwalCogniac** [Deci-AI/super-gradients#1308]
### 🐛 Describe the bug

Following the article by [deci,](https://deci.ai/blog/measure-inference-time-deep-neural-networks/) I tried to benchmark the yolonas_l on fp32 and fp16 in google collab. 
Strangely fp32 (52 milisec) has better inference time than fp16 (72 milisec) ! Any reason why ?
I imported the models like this : 
![image](https://github.com/Deci-AI/super-gradients/assets/99682235/9b5825ce-34eb-4769-920e-8b061ca422f6)
Code for benchmarking fp32:
![image](https://github.com/Deci-AI/super-gradients/assets/99682235/9cb66242-4443-405a-b9ed-e080bbae2567)
 Code for bench marking fp16:
![image](https://github.com/Deci-AI/super-gradients/assets/99682235/fbd8847f-2b5a-471b-bdd1-6282db2c8ddf)

### Versions

standard google collab with Tesla t4 gpu

**Comment by PrajwalCogniac** [comment]
Any idea @BloodAxe @Louis-Dupont ?

**Comment by BloodAxe** [comment]
Because Colab usually gives you old GPU that do not have native fp16 compute support. Driver simulate this functionality by doing full-precision compute and casting instead. So this is where the increased processing time comes from.

**Comment by PrajwalCogniac** [comment]
Thanks a lot @BloodAxe

**Comment by vilkkiE** [comment]
Hi, I also ran these inference time tests on both a Tesla T4 and RTX 3090 and fp16 was slower on both. Is this expected?
