### ISSUE TITLE
How to enable albumentations for YOLO-NAS

### ISSUE THREAD

**Issue by giorgiounity** [Deci-AI/super-gradients#1309]
### 📚 Documentation Improvement

I'm using the notebook "Intro to SuperGradients + YOLONAS Starter Notebook.ipynb" and it says that it supports albumentations.

> SuperGradients added transforms for you. You're free to experiment with these transformations as you please. You can also add in your own transformations from torchvision.transforms, albumentations or a custom tranformaton.

I tried to add albumentations, with no success.
Last experiment I tried was to use the AlbumentationsAdaptor, in this way:
```
from super_gradients.training.transforms.pipeline_adaptors import AlbumentationsAdaptor
train_dataloader.dataset.transforms = [AlbumentationsAdaptor(A.Blur(p=0.01))]
```
Can you clarify how to use albumentations with Yolo-nas object detection, please?

**Comment by BloodAxe** [comment]
It's not supported

**Comment by harpreetsahota204** [comment]
Hi @giorgiounity 

Thanks for opening an issue for SG.  I'm gathering some feedback on SuperGradients and YOLO-NAS.   

Would you be down for a quick call to chat about your experience?

If a call doesn't work for you, no worries. I've got a short survey you could fill out: https://bit.ly/sgyn-feedback.

I know you’re super busy, but your input will help us shape the direction of SuperGradients and make it as useful as possible for you.

I appreciate your time and feedback. Let me know what works for you.   

Cheers, 
Harpreet

**Comment by giorgiounity** [comment]
Hi Harpreet,
Sure, we can have a call, let me know when it works for you,

Giorgio

**Comment by harpreetsahota204** [comment]
@giorgiounity - Great! Feel free to find sometime here:https://calendly.com/harpreet-sahota/30min
