### ISSUE TITLE
'Label files are not associated' (Manual Check shows all files are correctly associated)

### ISSUE THREAD

**Issue by aymuos15** [Deci-AI/super-gradients#1316]
### 💡 Your Question

![label missing](https://github.com/Deci-AI/super-gradients/assets/54958228/9576873e-0a30-4ce2-b985-0ef6ec28e304)

As seen in the image, it shows the label files are not associated. However, my manual check shows:
1. Every image has an associated label.
2. No label/image is empty.

Question: _Any idea on what seems to be the problem?_

**Sidenote:** I am also getting an 0 mAP score (with a semi-decent loss value). Leaving aside the fact that the task it hard, does this have any correlation to the problem above?

**Comment by AkashParua** [comment]
Check whether the annotation files have the same exact name as that of the image and they are in the same split. If the problem persists , check whether the format is correct . You can also share the dataset so that I can pinpoint the problem.

**Comment by aymuos15** [comment]
I have double checked -
- annotation files have the same exact name as that of the image
- they are in the same split
- format

Unfortunately I can't share the data at the moment. Is there anything else you could think of?
