### ISSUE TITLE
Index Error when train yolonas small in google collab with TPU

### ISSUE THREAD

**Issue by RaffelRavionaldo** [Deci-AI/super-gradients#1322]
### 💡 Your Question

I train yolonas with my own dataset and train it in TPU (I cant use GPU because the google colab always restart the runtime), when I run this code :
from super_gradients.training import Trainer

trainer = Trainer(experiment_name=EXPERIMENT_NAME, ckpt_root_dir=CHECKPOINT_DIR)

trainer.train(model=model,
              training_params=train_params,
              train_loader=train_data,
              valid_loader=val_data)
              
 I got error like this :

[/usr/local/lib/python3.10/dist-packages/super_gradients/training/sg_trainer/sg_trainer.py](https://localhost:8080/#) in train(self, model, training_params, train_loader, valid_loader, test_loaders, additional_configs_to_log)
   1359                     self.train_loader.sampler.set_epoch(epoch)
   1360 
-> 1361                 train_metrics_tuple = self._train_epoch(context=context, silent_mode=silent_mode)
   1362 
   1363                 # Phase.TRAIN_EPOCH_END

[/usr/local/lib/python3.10/dist-packages/super_gradients/training/sg_trainer/sg_trainer.py](https://localhost:8080/#) in _train_epoch(self, context, silent_mode)
    440 
    441                     # COMPUTE THE LOSS FOR BACK PROP + EXTRA METRICS COMPUTED DURING THE LOSS FORWARD PASS
--> 442                     loss, loss_log_items = self._get_losses(outputs, targets)
    443 
    444                 context.update_context(preds=outputs, loss_log_items=loss_log_items)

[/usr/local/lib/python3.10/dist-packages/super_gradients/training/sg_trainer/sg_trainer.py](https://localhost:8080/#) in _get_losses(self, outputs, targets)
    473     def _get_losses(self, outputs: torch.Tensor, targets: torch.Tensor) -> Tuple[torch.Tensor, tuple]:
    474         # GET THE OUTPUT OF THE LOSS FUNCTION
--> 475         loss = self.criterion(outputs, targets)
    476         if isinstance(loss, tuple):
    477             loss, loss_logging_items = loss

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.10/dist-packages/super_gradients/training/losses/ppyolo_loss.py](https://localhost:8080/#) in forward(self, outputs, targets)
    772             alpha_l = 0.25
    773         else:
--> 774             assigned_labels, assigned_bboxes, assigned_scores = self.assigner(
    775                 pred_scores=pred_scores.detach().sigmoid(),  # Pred scores are logits on training for numerical stability
    776                 pred_bboxes=pred_bboxes.detach() * stride_tensor,

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
    113     def decorate_context(*args, **kwargs):
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 
    117     return decorate_context

[/usr/local/lib/python3.10/dist-packages/super_gradients/training/losses/ppyolo_loss.py](https://localhost:8080/#) in forward(self, pred_scores, pred_bboxes, anchor_points, num_anchors_list, gt_labels, gt_bboxes, pad_gt_mask, bg_index, gt_scores)
    505         gt_labels_ind = torch.stack([batch_ind.tile([1, num_max_boxes]), gt_labels.squeeze(-1)], dim=-1)
    506 
--> 507         bbox_cls_scores = pred_scores[gt_labels_ind[..., 0], gt_labels_ind[..., 1]]
    508 
    509         # compute alignment metrics, [B, n, L]

IndexError: index 2 is out of bounds for dimension 1 with size 2

**Comment by BloodAxe** [comment]
We don't support TPU compute engine in SG. 
Sorry, there is no solution for your problem at the moment.
