### ISSUE TITLE
Validation on trained model

### ISSUE THREAD

**Issue by guetaro** [Deci-AI/super-gradients#1323]
### 💡 Your Question

Hi,

I'm trying to use validation on trained model, but struggle with it:

When using evaluate_checkpoint as in the example, I receive errors that the function can't find .hydra and overrides.yaml , which does not exist.

When using evaluate_from_recipe , It requires many parameters and structure I'm not sure how to provide and what they mean such as val_loader_params and val_dataset_params.

How can I do it?

Thanks,

Roi

**Comment by BloodAxe** [comment]
Please follow example usages in our official scripts for evaluating a model:

https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/evaluate_from_recipe.py
https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/evaluate_checkpoint.py
