### ISSUE TITLE
Error while installing supergradients

### ISSUE THREAD

**Issue by gshivaprasad21** [Deci-AI/super-gradients#1325]
### 💡 Your Question

pip install super-gradients==3.1.0 on ubuntu 20.04 python 3.8 is showing the following error:
× Building wheel for pycocotools (pyproject.toml) did not run successfully.
237.6   ¦ exit code: 1
237.6   ?-> [24 lines of output]
237.6       running bdist_wheel
237.6       running build
237.6       running build_py
237.6       creating build
237.6       creating build/lib.linux-x86_64-cpython-38
237.6       creating build/lib.linux-x86_64-cpython-38/pycocotools
237.6       copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-cpython-38/pycocotools
237.6       copying pycocotools/mask.py -> build/lib.linux-x86_64-cpython-38/pycocotools
237.6       copying pycocotools/__init__.py -> build/lib.linux-x86_64-cpython-38/pycocotools
237.6       copying pycocotools/coco.py -> build/lib.linux-x86_64-cpython-38/pycocotools
237.6       running build_ext
237.6       Compiling pycocotools/_mask.pyx because it changed.
237.6       [1/1] Cythonizing pycocotools/_mask.pyx
237.6       building 'pycocotools._mask' extension
237.6       creating build/common
237.6       creating build/temp.linux-x86_64-cpython-38
237.6       creating build/temp.linux-x86_64-cpython-38/common
237.6       creating build/temp.linux-x86_64-cpython-38/pycocotools
237.6       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/tmp/pip-build-env-3h9be_du/overlay/lib/python3.8/site-packages/numpy/core/include -I./common -I/usr/local/include/python3.8 -c ../common/
maskApi.c -o build/temp.linux-x86_64-cpython-38/../common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
237.6       cc1: fatal error: ../common/maskApi.c: No such file or directory
237.6       compilation terminated.
237.6       /tmp/pip-build-env-3h9be_du/overlay/lib/python3.8/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier relea
ses! File: /tmp/pip-install-pp3evmo9/pycocotools_e098238c76834a67bdd5a1a7fda1e71b/pycocotools/_mask.pyx
237.6         tree = Parsing.p_module(s, pxd, full_module_name)
237.6       error: command '/usr/bin/gcc' failed with exit code 1
237.6       [end of output]

**Comment by BloodAxe** [comment]
Can you try with our latest release 3.1.3? We've upgraded dependency version for pycocotools recently which may fix this issue.

**Comment by gshivaprasad21** [comment]
It works,Thank you!
