### ISSUE TITLE
Class_imbalance

### ISSUE THREAD

**Issue by NikhilM97** [Deci-AI/super-gradients#1326]
### 💡 Your Question

Hi i am dealing with severely imbalanced data,Is there any way i can change the weights of a perticular classes in yolo_Nas?Or deal this problem in yolonas.
Thank you for your time.

**Comment by BloodAxe** [comment]
Yolo NAS uses focal loss to train the classifier part of the head which is already quite robust to class imbalance. 
Unfortunately we don't have the option to pass class weights as of now. However, we are open to contributions as this may be a good improvement.
