### ISSUE TITLE
Predict images progress bar

### ISSUE THREAD

**Issue by Allison2324** [Deci-AI/super-gradients#1329]
### 🚀 Feature Request

Can you add the ability to turn off the progress bar when getting predictions on pictures? For example, for YOLO-NAS.

### Proposed Solution (Optional)

The code for this is on the path super_gradients/training/pipelines/pipelines.py

**Comment by BloodAxe** [comment]
It is quite easy thing to add, yet I'm afraid now we are out of capacity.
We would be, however, happy to see a PR with addition of a `progress: bool` argument to predict() method 🤗 If you're willing to contribute let us know by replying here and we can assist you.

**Comment by EduardoPach** [comment]
@BloodAxe Is this still an active issue? I'm willing to take this one :D, also if you point out to me where in the `super_gradients/training/pipelines/pipelines.py` should I be looking at would be awesome, otherwise I can figure it out myself

**Comment by EduardoPach** [comment]
@BloodAxe I've created a PR here https://github.com/Deci-AI/super-gradients/pull/1465
