### ISSUE TITLE
How to train YoloNAS on the 2Million images.

### ISSUE THREAD

**Issue by praful1993** [Deci-AI/super-gradients#1341]
### 💡 Your Question

I attempted to train it on 2 million images, but creating the list and caching annotations are taking too much time.
all_images_file_names = list(image_name for image_name in os.listdir(self.images_folder) if is_image(image_name))
all_labels_file_names = list(label_name for label_name in os.listdir(self.labels_folder) if label_name.endswith(".txt"))

**Comment by BloodAxe** [comment]
We now have `cache_annotations` argument that you can set to False which should enable you to train on large number of images. This is not released yet, but already in master. Planned to be released in 3.2.0

**Comment by praful1993** [comment]
Thank you for your response. Once version 3.20 is released, kindly inform me.
