### ISSUE TITLE
FILE TRAIN.py

### ISSUE THREAD

**Issue by chelsea456** [Deci-AI/super-gradients#1349]
### 🚀 Feature Request

hi sir!! i want  to have a file python train.py such as yolo5

**Comment by BloodAxe** [comment]
The SuperGradients is a much more just a `train.py` to train yet another yolo.
We provide support for various tasks and different models.  
That, surely, has some learning curve. Take a time reading some docs & colab notebooks we've made

* https://github.com/Deci-AI/super-gradients#classification-1
* https://docs.deci.ai/super-gradients/documentation/source/ObjectDetection.html#training

I hope after reading them it would be more clear where to start with training modes using SG.
