### ISSUE TITLE
Unused argument in `PPYoloEPostPredictionCallback::forward` method

### ISSUE THREAD

**Issue by sadra-barikbin** [Deci-AI/super-gradients#1360]
Hi, `PPYoloEPostPredictionCallback`'s `forward` method receives a required `device` argument which isn't used in the method. Besides, it might be better that `device` be given in the constructor instead of `forward` method.

https://github.com/Deci-AI/super-gradients/blob/699b972df9bea093d2bb06838b7394b7a90a1623/src/super_gradients/training/models/detection_models/pp_yolo_e/post_prediction_callback.py#L30-L36

**Comment by BloodAxe** [comment]
Thanks for highlighting this. I agree this second argument is not strictly needed, however some internal code assumes this argument is present. I think we will make it optional to not require users to pass it explicitly.
