### ISSUE TITLE
Training time!

### ISSUE THREAD

**Issue by sunmooncode** [Deci-AI/super-gradients#1364]
### 💡 Your Question

Can you please provide information on the time comparison of the data set when trained under the same configuration using YOLOV8? 
Thank you!

**Comment by BloodAxe** [comment]
I'm not sure what is the request here. Do you ask us to train (what?) using same configuration using YoloV8 (why)? It is not clear who else except you will benefit from this information. Therefore it is highly unlikely we will be investing time into this.

**Comment by sunmooncode** [comment]
I would like to use Yolonas to train my dataset, but it is particularly large. Could you please provide me with an estimate of the training time for Yolonas on a dataset of similar dimensions? Thank you.
