### ISSUE TITLE
Cannot use convert_to_onnx function to convert custom trained yolo_nas_m model

### ISSUE THREAD

**Issue by KanikaAdik** [Deci-AI/super-gradients#1371]
### 💡 Your Question

I have pretrained a custom yol-nas-m model and wish to make it compatible with a tflite integrated application

I have my own set of custom dataset labelled and ready to use in yolov5/ coco format as per requirement, but as i try to convert a custom trained model  to ONNX using conver_to_onnx i get following error which I am not aware how to get resolved. 
Additional steps suggested were also implemented but that did not solve the purpose of converting to ONNX  
It will be good if this crucial step is seamless and handled with any scenario to convert a custom pretrained model to convert to ONNX  or even to a TFLite model will be of great help!

```

models.convert_to_onnx(model=model, prep_model_for_conversion_kwargs={'input_size':[ 3, 640, 640]}, out_path="yolo_nasm.onnx")

RESPONSE::

[2023-08-11 03:41:06] WARNING - conversion.py - input_shape is deprecated and will be removed in the next major release.Use the convert_to_onnx(..., prep_model_for_conversion_kwargs(input_size=(1, 3, 640, 640))) instead
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-25-8cb9fc7e7a42> in <cell line: 4>()
      2 
      3 #net = models.get("yolo_nas_s", pretrained_weights="coco")
----> 4 models.convert_to_onnx(model=model, input_shape=(3,640,640), out_path="yolo_nas_m.onnx")

30 frames
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py in _conv_forward(self, input, weight, bias)
    457                             weight, bias, self.stride,
    458                             _pair(0), self.dilation, self.groups)
--> 459         return F.conv2d(input, weight, bias, self.stride,
    460                         self.padding, self.dilation, self.groups)
    461 

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

```
Kindly suggest how this can be resolved!
Additionally - 
Is it possible that input weights are readily pickup from model parameters? I think that will be way easier approach to use this function seamlessly. 
I welcome any suggestions and requests to get my custom trained yolo_nas model to conver to tflite!

thank you so much for your help.

### Versions

--2023-08-13 20:43:23--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21653 (21K) [text/plain]
Saving to: ‘collect_env.py.1’

collect_env.py.1    100%[===================>]  21.15K  --.-KB/s    in 0.001s  

2023-08-13 20:43:23 (24.0 MB/s) - ‘collect_env.py.1’ saved [21653/21653]

Collecting environment information...
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.109+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.20GHz
CPU family:                      6
Model:                           79
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4399.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        55 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Vulnerable

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchdata==0.6.1
[pip3] torchmetrics==0.8.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.12.0+cu113
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by bit-scientist** [comment]
Hi, @KanikaAdik, the warning message you received also suggests using the new argument format for specifying the input size. Instead of input_shape, use prep_model_for_conversion_kwargs={'input_size': (1, 3, 640, 640)} in the convert_to_onnx function call. Could you try making the inputs compatible?

**Comment by BloodAxe** [comment]
The warning message is not relevant to the original issue. 
It looks like the input tensor is created not on the right device (The model is on cuda and the input tensor is on cpu). This looks like a bug to me, and we will take a look on it.

Meanwhile what you can do is to call "model.cpu()" before exporting a model to onnx:

```
models.convert_to_onnx(model=model.cpu(), input_shape=(3,640,640), out_path="yolo_nas_m.onnx")
```

I believe this should do the job.

**Comment by KanikaAdik** [comment]
> Meanwhile what you can do is to call "model.cpu()" before exporting a model to onnx:

Thanks @BloodAxe , yes this method worked for me ! 

Another solution mentioned --

> making the inputs compatible

i could not find a way to do that,  i am still curious to know how input type can be converted to cpu cuda version
```
models.convert_to_onnx(model=model.cpu(), prep_model_for_conversion_kwargs={'input_size':[ 1,3, 640, 640]}, out_path="yolo_nasm.onnx")
```
It asked for 4D parameter hence [1,2,640,640] ,

**Comment by BloodAxe** [comment]
Yesterday we released SG 3.2 with the brand new export API (For object detection models only for now, will be extended for other tasks in future versions).
I highly encourage you to check it out and give it a try: https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/models_export.md

With this API you can export Yolo-NAS, PP-Yolo-E or YoloX models to ONNX file including NMS step with just a single call: model.export(...). The good thing your this method that it will infer automatically all default settings like target device or the preprocessing / postprocessing settings that were used during the training. 

Give it a try and let us know how it goes.

**Comment by KanikaAdik** [comment]
Hi @BloodAxe , 
Congratulations of your SG3.2.0 release!

I tried to use export method to convert to ONNX with latest super gradient 3.2.0 version
I am get following error - 

```
export_result = model.export(output="yolo_model_cv.onnx")

RESPONSE:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/super_gradients/conversion/gs_utils.py](https://localhost:8080/#) in import_onnx_graphsurgeon_or_install()
     13     try:
---> 14         import onnx_graphsurgeon as gs
     15 

ModuleNotFoundError: No module named 'onnx_graphsurgeon'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
12 frames
[/usr/local/lib/python3.10/dist-packages/pip/_internal/configuration.py](https://localhost:8080/#) in _construct_parser(self, fname)
    275         # need to construct a parser.
    276         if os.path.exists(fname):
--> 277             locale_encoding = locale.getpreferredencoding(False)
    278             try:
    279                 parser.read(fname, encoding=locale_encoding)

TypeError: <lambda>() takes 0 positional arguments but 1 was given
```

something related to module - onnx_graphsurgeon

**Comment by KanikaAdik** [comment]
I did pip install onnx_graphsurgeon module and tried to export again, there was one module installation request - 
```
pip install pytorch-quantization==2.1.2 --extra-index-url https://pypi.ngc.nvidia.com
```
and this worked!
```
export_result = model.export(output="yolo_model_cv.onnx")
```
Thanks for your help!

Here are the environment details --

```
--2023-08-17 15:20:26--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21653 (21K) [text/plain]
Saving to: ‘collect_env.py’

collect_env.py      100%[===================>]  21.15K  --.-KB/s    in 0.002s  

2023-08-17 15:20:27 (11.2 MB/s) - ‘collect_env.py’ saved [21653/21653]

Collecting environment information...
PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.109+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.30GHz
CPU family:                      6
Model:                           63
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4599.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        45 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] torch==2.0.1+cu118
[pip3] torchaudio==2.0.2+cu118
[pip3] torchdata==0.6.1
[pip3] torchmetrics==0.8.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.2+cu118
[pip3] triton==2.0.0
[conda] Could not collect
```
