### ISSUE TITLE
YOLO NAS nano models

### ISSUE THREAD

**Issue by look4pritam** [Deci-AI/super-gradients#1377]
### 🚀 Feature Request

YOLO NAS supports small, medium and large models. It will be good to have nano models also. These can be deployed on NVIDIA Jetson Nano edge devices. Nano models will have lesser latency and more fps than small models. How can I add nano models? Are weights trained on COCO dataset available for the nano models? Or what is the procedure to train the nano model on COCO dataset?

**Comment by BloodAxe** [comment]
We do not provide official Nano version for Yolo NAS at the moment. 

You can however create your own version by creating a copy of [Yolo NAS S Config](https://github.com/Deci-AI/super-gradients/blob/e1db4d99492a25f8e65b5d3e17a6ff2672c5467b/src/super_gradients/recipes/arch_params/yolo_nas_s_arch_params.yaml) and scaling down number of channels / layers according to your intuition.
Of course you will have to train this model from scratch on COCO of whatever dataset you need.

Training procedure for your custom yolo nas model can be the same as training an S variant shown here: https://github.com/Deci-AI/super-gradients/blob/92a9187cf0484bcebc7f7d87c2d73bffc19147e4/src/super_gradients/recipes/coco2017_yolo_nas_s.yaml. Note that you may want to change some dataset augmentation / preprocessing settings listed here (https://github.com/Deci-AI/super-gradients/blob/7afa83d057cb39366b9cd8a13848b75211246604/src/super_gradients/recipes/dataset_params/coco_detection_yolo_nas_dataset_params.yaml) to match your target resolution for inference (This is to ensure best model accuracy)
