### ISSUE TITLE
Increased model size

### ISSUE THREAD

**Issue by RadouaneK** [Deci-AI/super-gradients#1384]
### 💡 Your Question

I trained a yolo_nas_s model on my custom datasets, but I have noticed the the model size has increased after training, from 73MB to 256 MB. is it normal ?
the input size I used is: 256. and the number of classes is: 40

**Comment by BloodAxe** [comment]
The checkpoint may contain optimizer state (useful if you want to resume training) and also ema model state dict as well, so yet it is normal.
