### ISSUE TITLE
Error when using the model.export function - super gradients 3.2.0

### ISSUE THREAD

**Issue by PrajwalCogniac** [Deci-AI/super-gradients#1399]
### 🐛 Describe the bug

I get the following error when using the model.export code as provided in the models_export.md

Code + error:
```
from super_gradients.common.object_names import Models
from super_gradients.training import models

model = models.get(Models.YOLO_NAS_S, pretrained_weights="coco")

export_result = model.export("yolo_nas_s.onnx")
```
![image](https://github.com/Deci-AI/super-gradients/assets/99682235/b18894a6-8f55-495a-b6f2-825a28012d91)

### Versions

Standard google collab notebook with T4 GPU

Collecting environment information...
PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.109+-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 525.105.17
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU @ 2.30GHz
CPU family:                      6
Model:                           63
Thread(s) per core:              2
Core(s) per socket:              1
Socket(s):                       1
Stepping:                        0
BogoMIPS:                        4599.99
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB (1 instance)
L1i cache:                       32 KiB (1 instance)
L2 cache:                        256 KiB (1 instance)
L3 cache:                        45 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable; SMT Host state unknown
Vulnerability Meltdown:          Vulnerable
Vulnerability Mmio stale data:   Vulnerable
Vulnerability Retbleed:          Vulnerable
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] pytorch-quantization==2.1.2
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchdata==0.6.1
[pip3] torchmetrics==0.8.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.15.2
[pip3] torchvision==0.12.0+cu113
[pip3] triton==2.0.0
[conda] Could not collect

**Comment by PrajwalCogniac** [comment]
So I tried correcting it by doing - manually changing the opset to 11.
Code + error:
![image](https://github.com/Deci-AI/super-gradients/assets/99682235/f5138ab4-77a6-43c9-9bf3-92ece572e4ba)

**Comment by bit-scientist** [comment]
Hello, @PrajwalCogniac, [some other issue](https://github.com/facebookresearch/fairseq/issues/3395#issuecomment-968256371) was resolved by putting `operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK` inside the export method. I am away from my setup right now and hence unable to reproduce the issue, try the above and let me know if it helps.

**Comment by PrajwalCogniac** [comment]
@bit-scientist thanks for the reply.
The above suggestion does not seem to solve the problem here ! I still get the same above errors !
Also in exportable_detector.py it is mentioned overriding args are not supported 
Without solving this error we cannot use model.export() and hence cannot use the major update of 3.2.0

**Comment by PrajwalCogniac** [comment]
I think the problem arises when pre and post processing is set to True

**Comment by PrajwalCogniac** [comment]
@BloodAxe @harpreetsahota204  any help on this issue !

**Comment by BloodAxe** [comment]
Can you please upgrade torch to something like 1.13 or 2.0? It may solve your issue. 
I think we didn't test with old 1.10 torch.

**Comment by PrajwalCogniac** [comment]
@BloodAxe thanks a lot for the response !
Yes upgrading the torch solved the issue. 
However if I continue replicating things from model_export.md I get the following error !
Code:
![image](https://github.com/Deci-AI/super-gradients/assets/99682235/c4079208-55ea-4de0-a6d1-c2c88e00109c)

**Comment by BloodAxe** [comment]
Thanks for the update and sorry for inconvenience. We tested that feature on window, mac and Linux platform with 1.13 and 2.0 and 1.12 but not doing exhaustive combinatorial match of all variants...
What version of pytorch did you install lastly?

**Comment by PrajwalCogniac** [comment]
@BloodAxe no worries at all I completely understand.
This model.export is fantastic feature so want to test it early and iron out all the details.
So I installed torch 2.0.1 and it solved the problem !
So if I run this alone 
```
export_result = model.export(
    "yolo_nas_s_int8.onnx",
    output_predictions_format=DetectionOutputFormatMode.FLAT_FORMAT,
    quantization_mode=ExportQuantizationMode.INT8
)
```
The error is not there but if we run 
`export_result = model.export("yolo_nas_s.onnx")` and then the above code I get the error msg shared above !

**Comment by bit-scientist** [comment]
Hi @PrajwalCogniac, first off, please leave the code and tracebacks as code format, not as a screenshot. It helps one to copy-paste it for reproduction 😉 

Now, I wonder if your code is indeed exactly the same as you posted:
```
from super_gradients.conversion.conversion_enums import ExportQuantizationMode
export_result = model.export(
    "yolo_nas_s_int8.onnx",
    output_predictions_format=DetectionOutputFormatMode.FLAT_FORMAT,
    quantization_mode=ExportQuantizationMode.INT8
)
```
Because when I tested, it complained about `DetectionOutputFormatMode` as not defined. I guess it should be imported along with `ExportQuantizationMode ` as ` from super_gradients.conversion.conversion_enums import ExportQuantizationMode, DetectionOutputFormatMode`. 

After that I could export it well both in Windows (python 3.8.17, torch=1.12.1, cuda 11.3, super-gradients=3.2.0 ) and Linux (python 3.9.17, torch 1.13.1, cuda 11.7, super-gradients=3.2.0) machines. 
I should note that I got a bunch of `UserWarning`s.

**Comment by PrajwalCogniac** [comment]
@bit-scientist haha sure next time I will paste the code rather than screenshots ! :) 
Also I had no import issues `DetectionOutputFormatMode`! ... I have been following the exact steps mentioned in models_export.md where it is mentioned to import the necessary packages and methods

**Comment by PrajwalCogniac** [comment]
@BloodAxe @bit-scientist thanks a lot for taking a look at the issue. I was able to solve the issue by downgrading my torch version to 1.13 .So the error still persists for torch version 2.0.1 and beyond !

**Comment by bit-scientist** [comment]
Glad to hear that
