### ISSUE TITLE
How to evaluate custom trained YOLO-NAS model for each class?

### ISSUE THREAD

**Issue by Dev-Devesu** [Deci-AI/super-gradients#1405]
### 💡 Your Question

trainer.test(
    model=best_model,
    test_loader=test_data,
    test_metrics_list=DetectionMetrics_050(
        score_thres=0.1, 
        top_k_predictions=300, 
        num_cls=len(dataset_params['classes']), 
        normalize_targets=True, 
        post_prediction_callback=PPYoloEPostPredictionCallback(
            score_threshold=0.01, 
            nms_top_k=1000, 
            max_predictions=300,                                                                              
            nms_threshold=0.7
        )
    )
)

this gives the metrics for all classes combined. How do i find the evaluation metric for each class .

**Comment by bit-scientist** [comment]
You should probably loop through all the classes and compute the metrics separately for each class. You would  collect them in a dictionary and then print out each. It would be something like below:

```
from super_gradients.training.metrics import DetectionMetrics, DetectionMetrics_050

class_names = dataset_params['classes']
class_metrics = {}

for class_idx, class_name in enumerate(class_names):
    class_metrics[class_name] = trainer.test(
        model=best_model,
        test_loader=test_data,
        test_metrics_list=DetectionMetrics_050(
            score_thres=0.1,
            top_k_predictions=300,
            num_cls=len(dataset_params['classes']),
            normalize_targets=True,
            post_prediction_callback=PPYoloEPostPredictionCallback(
                score_threshold=0.01,
                nms_top_k=1000,
                max_predictions=300,
                nms_threshold=0.7
            ),
            class_idx=class_idx 
        )
    )

for class_name, metrics in class_metrics.items():
    print(f"Metrics for {class_name}:")
    print(metrics)

```

**Comment by Dev-Devesu** [comment]
@bit-scientist what is the use of class_idx here? Because the way i have the data doesn't inherently has class_idx. So whats the impact of it and also if i run this without class_idx my evaluation result is same for all class which is equal to the overall score.

**Comment by bit-scientist** [comment]
@Dev-Devesu It's because of `enumerate`, it helps you orderly count ( and print out) each class name. Take a loot at [python's enumerate](https://docs.python.org/3.9/library/functions.html#enumerate)

**Comment by chriszxk** [comment]
> ### 💡 Your Question
> trainer.test( model=best_model, test_loader=test_data, test_metrics_list=DetectionMetrics_050( score_thres=0.1, top_k_predictions=300, num_cls=len(dataset_params['classes']), normalize_targets=True, post_prediction_callback=PPYoloEPostPredictionCallback( score_threshold=0.01, nms_top_k=1000, max_predictions=300, nms_threshold=0.7 ) ) )
> 
> this gives the metrics for all classes combined. How do i find the evaluation metric for each class .
> 
> ### Versions
> _No response
no evaluation map outputs when I use this script.

**Comment by BloodAxe** [comment]
In SG 3.6 you can use include_classwise_ap argument:
```
metric = DetectionMetrics_050(..., include_classwise_ap = True, class_names = [....])
```
This will output AP score per class in addition to mAP score.
