### ISSUE TITLE
where can i ask question as i`m a beginner??//Weird predicion bbox after custom training

### ISSUE THREAD

**Issue by AR384** [Deci-AI/super-gradients#1409]
### 💡 Your Question

I want to ask why my local machine(pc) and colab tutorial make different result?(inference, bbox, mAP value)
I assumed some of my fault make a my major Issue. but can not figure out what it is.
I follow basic tutorial from YOLO-NAS git- google colab named 'Intro to SuperGradients'. Also run exact same code on my local machine(Win10/VScode[JupyterNotebook]/Python3.9/conda)
I use some dataset from roboflow and format is yolov5
Here is list where i guess something suspicious part between colab vs my pc

1. When i'm run, i got issue on my pc which is conflict between pyparsing-2.4.7(for roboflow) & 2.4.5(for SG)
2. I got a out put log my pc < env_sanity_check.py - Failed to verify operating system: Deci officially supports only Linux kernels. Some features may not work as expected.> but not in colab.
3. When i'm start training each epoch give a warning that - sg_trainer.py - Could not set preprocessing pipeline from the validation dataset: Before callingpredict make sure to call set_dataset_processing_params.
4. After finishing training, when i run model.predict output log give me also, -You must set the dataset processing parameters before calling predict.
Please call model.set_dataset_processing_params(...) first.
5. After i write code < set_dataset_processing_params & image_processor>  and run best_model.predict that make atteched images.

Other thing (info,warning..etc) is exact same as colab and my pc
Where am i wrong?
p.s I do conf 0.01 because of when i do same as colab i can't inference anything(colab is 0.6)
And very curious of same epoch can make big difference mAP value(Vscode:0.73, colab:0.93)
![combine](https://github.com/Deci-AI/super-gradients/assets/20662246/feb3a8f7-da49-41c2-a728-41c44901f409)
![code](https://github.com/Deci-AI/super-gradients/assets/20662246/b5840d9e-d8f4-4f61-a68e-d93250ef07be)

### Versions

VS code -JupyterNote Book (Anaconda enviorment)
super-gradients 3.2.0

**Comment by bit-scientist** [comment]
Let's address your issues one at a time, @AR384. What have you done to get weird predictions using this repo? Please leave a minimal reproducible example. If possible, explain your dataset format, labels and provide image samples. 

P.S. Avoid unnecessary information and try to format your content to be more readable and appealing. You can preview what you are about to post through **Preview** panel:
![image](https://github.com/Deci-AI/super-gradients/assets/26497571/9f1ccf7a-db9f-40c1-adec-00b92c30f1a2)

**Comment by AR384** [comment]
Thanks for considering. i update my post. if something not correct please tell me.
