### ISSUE TITLE
Some expression errors

### ISSUE THREAD

**Issue by TaoweiZhang** [Deci-AI/super-gradients#1410]
### 📚 Documentation Improvement

1. File name error
[expor_yolo_nas_pose.py](https://github.com/Deci-AI/super-gradients/blob/master/expor_yolo_nas_pose.py), **export_yolo_nas_pose.py** will be better, I think.
2. Grammatical error
In [README.md](https://github.com/Deci-AI/super-gradients/blob/a6d90035df964b17f0b6275a2287678872fc4864/README.md?plain=1#L91C8-L91C8) (More **example** on how and why to use recipes can be found in [Recipes](#recipes)), **example** --> **examples**.

**Comment by bit-scientist** [comment]
Thank you for your time. We will do our best to make the content accurate and user-friendly. If you happen to have time for making it more accurate, please fork the project, make local changes and create one PR after you have done enough modifications. This way, the authors will be able to look through your changes quickly and approve your PR. Thank you!

**Comment by TaoweiZhang** [comment]
Sorry, I don't know how to create a PR well. Please help me create a PR to submit these changes, thank you.

**Comment by bit-scientist** [comment]
@TaoweiZhang then I suggest you learn on some other resources first. These changes are minor changes, they aren't worth spending time, sorry for the expression. But you may still collect them in your own repo and create **one** PR to include all your changes.

**Comment by TaoweiZhang** [comment]
Ok, I'll keep collecting if I continue to use sg.
