### ISSUE TITLE
Which metric is best for object counting?

### ISSUE THREAD

**Issue by Phyrokar** [Deci-AI/super-gradients#1417]
### 💡 Your Question

Hello,
my job is mainly to count objects in the image and not get a highly accurate bounding box. Can anyone recommend a good available metric for training for this?

### Versions

Super-gradients

**Comment by bit-scientist** [comment]
@Phyrokar, well, this repository isn't oriented in counting the number of objects. The number of specific objects comes for almsot free. You just count the number of detections for the given image. If you are not too much concerned about the accuracy of the detection, you may tweak the detection threshold a bit. However, it's always a good practice to first accurately detect the objects on the image. Please explain what you need and why you need a particular thing in more detail, with examples.

**Comment by bit-scientist** [comment]
I can't help with your specific requirements but you can find metrics here: `src/super_gradients/training/metrics`.

**Comment by Phyrokar** [comment]
No worries, thank you anyways! Maybe someone else knows a solution.

**Comment by BloodAxe** [comment]
A bit late for the party, but:

I think want you can do is to adjust NMS IoU threshold option in post prediction callback to higher values (0.9 but exact value probably should be adjusted based on visual analysis). The idea is to prevent near objects to suppress one another.

And then you can do regular mAP0.5..0.95 metric.
