### ISSUE TITLE
ResNet num_classes doesn't change

### ISSUE THREAD

**Issue by Allison2324** [Deci-AI/super-gradients#1426]
Training code:

```
DEVICE = 'cuda'
print(DEVICE)
from super_gradients.training import Trainer

CHECKPOINT_DIR = 'checkpoints'
EXPERIMENT_NAME = 'resnet50'
trainer = Trainer(experiment_name=EXPERIMENT_NAME, ckpt_root_dir=CHECKPOINT_DIR)

from super_gradients.training import dataloaders
from super_gradients.training.dataloaders.dataloaders import imagenet_resnet50_train, imagenet_resnet50_val

dataset_params = {
    'train_dir': 'dataset/train/',
    'val_dir': 'dataset/val/',
    'classes': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13']
}

train_data = imagenet_resnet50_train(
    dataset_params={
        'root': dataset_params['train_dir']
    },
    dataloader_params={
        'batch_size': 16,
        'num_workers': 1
    }
)

val_data = imagenet_resnet50_val(
    dataset_params={
        'root': dataset_params['val_dir']
    },
    dataloader_params={
        'batch_size': 16,
        'num_workers': 1
    }
)

import pprint

print("Dataloader parameters:")
pprint.pprint(train_data.dataloader_params)

print("Dataset parameters:")
pprint.pprint(train_data.dataset.dataset_params)

from super_gradients.training import models
from super_gradients.common.object_names import Models

model = models.get(model_name=Models.RESNET18,
                   num_classes=len(dataset_params['classes']),
                   pretrained_weights="imagenet")

from super_gradients.training import training_hyperparams

train_params = training_hyperparams.get("training_hyperparams/imagenet_resnet50_train_params")

trainer.train(model=model,
              training_params=train_params,
              train_loader=train_data,
              valid_loader=val_data)

```

Error:

Traceback (most recent call last):
  File "/home/allison/PycharmProjects/game_mode_train/train.py", line 58, in <module>
    trainer.train(model=model,
  File "/home/allison/PycharmProjects/game_mode_train/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 1362, in train
    train_metrics_tuple = self._train_epoch(context=context, silent_mode=silent_mode)
  File "/home/allison/PycharmProjects/game_mode_train/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 442, in _train_epoch
    loss, loss_log_items = self._get_losses(outputs, targets)
  File "/home/allison/PycharmProjects/game_mode_train/venv/lib/python3.10/site-packages/super_gradients/training/sg_trainer/sg_trainer.py", line 475, in _get_losses
    loss = self.criterion(outputs, targets)
  File "/home/allison/PycharmProjects/game_mode_train/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/allison/PycharmProjects/game_mode_train/venv/lib/python3.10/site-packages/super_gradients/training/losses/label_smoothing_cross_entropy_loss.py", line 99, in forward
    loss = cross_entropy(
  File "/home/allison/PycharmProjects/game_mode_train/venv/lib/python3.10/site-packages/super_gradients/training/losses/label_smoothing_cross_entropy_loss.py", line 70, in cross_entropy
    loss = -(target * lsm).sum(-1)
RuntimeError: The size of tensor a (1000) must match the size of tensor b (13) at non-singleton dimension 1

1000 - ImageNet num_classes
13 - My dataset num_classes

This code for num_classes changing doesn't work:

```
model = models.get(model_name=Models.RESNET18,
                   num_classes=len(dataset_params['classes']),
                   pretrained_weights="imagenet")
```

Please, help me to solve it.

**Comment by Allison2324** [comment]
This bug was fixed by changing num_classes here:

```
'collate_fn': {
            'CollateMixup': {
                'mixup_alpha': 0.2,
                'cutmix_alpha': 1.0,
                'label_smoothing': 0.1,
                'num_classes': 13
            }
        }
```

But I found a new problem:
During training I have NaN in Labelsmoothingcrossentropyloss
```
├── Train
│   ├── Labelsmoothingcrossentropyloss = nan
│   │   ├── Epoch N-1      = nan    (= nan)
│   │   └── Best until now = nan    (= nan)
│   ├── Accuracy = 0.043
│   │   ├── Epoch N-1      = 0.043  (= 0.0)
│   │   └── Best until now = 0.043  (= 0.0)
│   └── Top5 = 0.2459
│       ├── Epoch N-1      = 0.2459 (↘ -0.0001)
│       └── Best until now = 0.2459 (↘ -0.0001)
└── Validation
    ├── Labelsmoothingcrossentropyloss = nan
    │   ├── Epoch N-1      = nan    (= nan)
    │   └── Best until now = nan    (= nan)
    ├── Accuracy = 0.0375
    │   ├── Epoch N-1      = 0.0375 (= 0.0)
    │   └── Best until now = 0.0375 (= 0.0)
    └── Top5 = 0.2157
        ├── Epoch N-1      = 0.2157 (= 0.0)
        └── Best until now = 0.2157 (= 0.0)
```

Maybe I need to do something else. Help please if you have some advice.

**Comment by shaydeci** [comment]
No you have it right, num classes need to be changed in the mixup collate as well.
