### ISSUE TITLE
Can int8 .trt use for object detection?

### ISSUE THREAD

**Issue by Chiauwen** [Deci-AI/super-gradients#1439]
### 💡 Your Question

I converted my custom-trained model into int8 in a .trt file format by following the tutorial in this link :
https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/qat_ptq_yolo_nas.md

I would like to ask how to do object detection on an image by using my model after I have converted it to .trt?

Thank You.

**Comment by BloodAxe** [comment]
Please check https://github.com/Deci-AI/super-gradients/blob/master/notebooks/YoloNAS_Inference_using_TensorRT.ipynb
