### ISSUE TITLE
Is AutoNAC use while training on custom-dataset ?

### ISSUE THREAD

**Issue by Dhiaeddine-Oussayed** [Deci-AI/super-gradients#1456]
### 💡 Your Question

I got confused reading about Yolo-NAS. 

Did it use AutoNAC to produce the architectures that are available now ? Or does it use AutoNAC everytime you try to run training on any custom-dataset ? 

Also, is quantization only available for CPU, or can we do it on GPU too ?

I would appreciate if you clarify these matters for me, thank you.

**Comment by BloodAxe** [comment]
AutoNAC is a proprietary tool made by Deci. And AutoNAC was used to find architecture of YoloNAS that was publicly released to open-source.
For community users AutoNAC is not available for public use. 

Regarding quantization - absolutely, GPU also supports doing math in FP16 and INT8.

**Comment by Dhiaeddine-Oussayed** [comment]
@BloodAxe, thank you for your quick interaction.
If you may please confirm the following:

- As I can understand Yolo-NAS present architecture is optimized for the COCO dataset and the NVIDIA T4 GPU.

- Is the gain on the quantization on the GPU level worth doing or not. As previous quantization solutions and products doesn't offer a much gain on the GPU level as it was primarily designed for CPU (exp: NVIDIA GPUs are specifically designed for convolutional multiplication..etc.)
