### ISSUE TITLE
Import Error when import super_gradients.training.model

### ISSUE THREAD

**Issue by okanegemen** [Deci-AI/super-gradients#1459]
### 🐛 Describe the bug

when I try import  models module I got Import error! 
ImportError: cannot import name 'DEV_PKGS' from 'pip._internal.commands.freeze'

<img width="413" alt="Screenshot 2023-09-12 at 12 23 29" src="https://github.com/Deci-AI/super-gradients/assets/108547664/1f306e45-5b50-4c0d-950e-32c71a083cd1">

### Versions

<img width="565" alt="Screenshot 2023-09-12 at 12 24 02" src="https://github.com/Deci-AI/super-gradients/assets/108547664/39874641-2a6d-4cf3-bfb3-eaa82262e164">

**Comment by geifmany** [comment]
Changing pip to pip==23.1 solved it to me. We'll wait for the team to come up with a better solution.

**Comment by BloodAxe** [comment]
@okanegemen can you please share what python & pip version are you using?

**Comment by prince0310** [comment]
> pip==23.1

worked for me too
