### ISSUE TITLE
ImportError: cannot import name 'get_local_rank'

### ISSUE THREAD

**Issue by gufeng745** [Deci-AI/super-gradients#1466]
### 🐛 Describe the bug

When importing super_gradients, an error occurs: “ImportError: cannot import name ‘get_local_rank’ from ‘super_gradients.common.environment.ddp_utils’”.

### Versions

![image](https://github.com/Deci-AI/super-gradients/assets/66720028/0344cf63-93f9-47d4-99bd-7f70d742d42d)

**Comment by Louis-Dupont** [comment]
Hi @gufeng745 
Could you please share the version of `super_gradients` that you are using?
Besides, it would help if you could also show
1. how to reproduce (minimal snippet of code that you run and that leads to this crash)
2. Full error traceback (not just the line with `ImportError`). If you can copy/paste the code inside "```" it would increase readability :) 

Thanks

**Comment by gufeng745** [comment]
super-gradients==3.2.1
![image](https://github.com/Deci-AI/super-gradients/assets/66720028/c2a63c2c-6384-4f7d-ae19-ae4f6450d3a5)

**Comment by BloodAxe** [comment]
Updating SG to 3.3.1 should fix the issue
