### ISSUE TITLE
You provide an option to export YOLO-NAS model to ONNX, but no example how to preproc, run and postproc it

### ISSUE THREAD

**Issue by hlacikd** [Deci-AI/super-gradients#1480]
### 💡 Please provide an example how to preprocess and postprocess YOLO-NAS

Guys,

question is simple , why there is not an example of running onnx model , you provide an option to export it to onnx (so it can be converted to platform specific models runable on different devices --- which is my case as well), but there is not an example of how to preprocess and postprocess outputs ...

**Comment by BloodAxe** [comment]
Have you seen a new version of model.export() and documentation?

https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/models_export.md
https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/examples/model_export/models_export.ipynb

I believe it covers all the aspects you mentioned. 
Let us know if something is missing in these docs.

**Comment by hlacikd** [comment]
oh wow, thank you that is perfect.

**Comment by hlacikd** [comment]
@BloodAxe you have a bug in this documentation

if you do not want to export model with NMS postprocessing it should be `postprocessing=False`

you refer it as `preprocessing=True` in both of these documents
