### ISSUE TITLE
Update SG docker images to use Ubuntu 22.04 (which has python 3.10)

### ISSUE THREAD

**Issue by mayorblock** [Deci-AI/super-gradients#1498]
### 🚀 Feature Request

Now what SG (as of  3.1.3) supports python 3.10 it would be nice to see this reflected in the available Docker images. The most [recent](https://hub.docker.com/layers/deciai/super-gradients/3.2.1/images/sha256-8f00e146d893ce7b492f4589f9ea3fa8281a76eb39a303900f1230cbbcc9e40b?context=explore) from 2 weeks ago is still based on Ubuntu 20.04 and so, ships with python 3.8.

### Proposed Solution (Optional)

Update base image from 20.04 to 22.04
![image](https://github.com/Deci-AI/super-gradients/assets/126508264/98d8ba32-3e18-48a0-9d34-195777a569f5)

This has been [available from Nvidia](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=22.04) for some time. 

Out of curiosity, why don't you save yourselves some time and build directly off the Nvidia image? Do you have any special additional requirements?

Oh yes, and thank you for a wonderful package. So far it has been a pleasure to work with :)

**Comment by BloodAxe** [comment]
Thanks for your feedback!
I'm afraid right now it is hard to estimate when we would be able to address this since we are bit out of hands due to war in Israel. Sorry for the inconvenience. This is noted in internal tracke, hopefully one day we will get to that.

**Comment by mayorblock** [comment]
HI @BloodAxe ,

Of course, I completely understand. Thank you for taking the time to reply.

Let me know if I can help by making a PR. I have a working image with 22.04.
