### ISSUE TITLE
The mAP reported by SG is not consistent with COCO-API

### ISSUE THREAD

**Issue by NatanBagrov** [Deci-AI/super-gradients#150]
### Describe the bug
When training a detection model, e.g. SSD Lite MobileNet, the mAP shown in SG (TensorBoard) is much higher than the mAP returned via COCO-API

### To Reproduce

1. Branch https://github.com/Deci-AI/super-gradients/tree/ssd_mobilenet
2. Run `train_from_recipe.py` with `coco_ssd_lite_mobilenet_v2.yaml` or `coco_ssd_mobilenet_v1.yaml`
3. (The model should reach ~30 mAP)

**However: running the [COCO-API reference](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoEvalDemo.ipynb) returns ~0.17 mAP.**

### Expected behavior
The mAP information should correspond to COCO-API's mAP.

### Screenshots
![image](https://user-images.githubusercontent.com/20153650/158202978-1fbd56ec-8512-487d-aff9-6afd556d987b.png)

**Comment by oferbaratz** [comment]
Fixed and merged
