### ISSUE TITLE
resume training 

### ISSUE THREAD

**Issue by sulaiman1988** [Deci-AI/super-gradients#1504]
### 💡 Your Question

 this error appear when am trying to resume training and update training_params as previous you say :
 train_params = {

        'resume': True,
        'ckpt_name':'ckpt_latest.pth',
        'resume_strict_load':  True,
   
        'resume_path': 'runs/train1/RUN_20231004_100940_572703/ckpt_latest.pth',
        # 'checkpoint_path':,
        # ENABLING SILENT MODE
        'silent_mode': False,
        "average_best_models": True,
        "warmup_mode": "linear_epoch_step",
        "warmup_initial_lr": 1e-6,
        "lr_warmup_epochs": 3,
        "initial_lr": 5e-4,
        "lr_mode": "cosine",
        "cosine_final_lr_ratio": 0.1,
        "optimizer": "Adam",
        "optimizer_params": {"weight_decay": 0.0001},
        "zero_weight_decay_on_bias_and_bn": True,
        "ema": True,
        "ema_params": {"decay": 0.9, "decay_type": "threshold"},
        # ONLY TRAINING FOR 10 EPOCHS FOR THIS EXAMPLE NOTEBOOK
        "max_epochs": args['epoch'],
        "mixed_precision": True,
        "loss": PPYoloELoss(
            use_static_assigner=False,
            # NOTE: num_classes needs to be defined here
            num_classes=len(yaml_params['names']),
            reg_max=16
        ),
        
        
  File "train.py", line 154, in <module>
    train_loader=train_data,
  File "/home/Deci_AI-super_gradients/super-gradients/super_gradients/training/models/model_factory.py", line 232, in get
    ckpt_entries = read_ckpt_state_dict(ckpt_path=checkpoint_path).keys()
  File "/home/Deci_AI-super_gradients/super-gradients/super_gradients/training/utils/checkpoint_utils.py", line 173, in read_ckpt_state_dict
    raise FileNotFoundError(f"Incorrect Checkpoint path: {ckpt_path} (This should be an absolute path)")
FileNotFoundError: Incorrect Checkpoint path: runs/train4/ckpt_best.pth (This should be an absolute path)
Traceback (most recent call last):
  File "train.py", line 154, in <module>
    train_loader=train_data,
  File "/home/Deci_AI-super_gradients/super-gradients/super_gradients/training/models/model_factory.py", line 232, in get
    ckpt_entries = read_ckpt_state_dict(ckpt_path=checkpoint_path).keys()
  File "/home/Deci_AI-super_gradients/super-gradients/super_gradients/training/utils/checkpoint_utils.py", line 173, in read_ckpt_state_dict
    raise FileNotFoundError(f"Incorrect Checkpoint path: {ckpt_path} (This should be an absolute path)")
FileNotFoundError: Incorrect Checkpoint path: runs/train4/ckpt_best.pth (This should be an absolute path)
[2023-10-05 10:54:24] INFO - exception_monitoring_setup.py - Uploading console log to deci platform ...
/home/.virtualenvs/super_gradients/lib/python3.8/site-packages/deci_platform_client/exceptions.py:123: DeprecationWarning: HTTPResponse.getheaders() is deprecated and will be removed in urllib3 v2.1.0. Instead access HTTPResponse.headers directly.
  return self.api_response.response.getheaders()
[2023-10-05 10:54:25] WARNING - exception_monitoring_setup.py - Exception could not be uploaded to platform with exception: (401)
Reason: Unauthorized

**Comment by BloodAxe** [comment]
As the exception suggests:

> FileNotFoundError: Incorrect Checkpoint path: runs/train4/ckpt_best.pth (This should be an absolute path)

checkpoint should be an absolute path if you want to load weight.


Second issue I'm seeing is that you have deci platform package installed, which is mainly used for by customers who are using Deci Platform to track their experiments. There is no benefit in having this package installed (As you see it tries to upload error logs to plaform but since you don't have account there it fails.). You can either remove the package or set environment variable UPLOAD_LOGS to 0/False to disable it.

**Comment by BloodAxe** [comment]
Also may want to check resume feature https://github.com/Deci-AI/super-gradients/issues/1139

**Comment by sulaiman1988** [comment]
this is created after running so is create runs/train4/RUN_20231005_110620_654443/console_Oct05_11_06_22.txt as apath for all checpoints and result but when want to save it in the same directory failed to find it and raise an error

**Comment by sulaiman1988** [comment]
the code make folder automatiaclly so I apply the last checkpoint from runs/train1/RUN_20231004_100940_572703/ckpt_latest.pth' and save result at the end in
 train4
