### ISSUE TITLE
How to KD for object detection

### ISSUE THREAD

**Issue by minhhotboy9x** [Deci-AI/super-gradients#1507]
### 💡 Your Question

I saw in this repo that there is knowledge distillation for different models. However, I got nothing when I tried to find a tutorial for object detection distillation. There is only a tutorial for classification distillation. Can somebody help me to KD for object detection in this repo, please?

**Comment by harpreetsahota204** [comment]
Hi @minhhotboy9x, it will follow the same pattern as the image classification tutorial. Have you tried it out? If so, what difficulty did you face?

**Comment by BloodAxe** [comment]
KD of object detection is currently not supported in SG.
