### ISSUE TITLE
Error message: "mixed precision is not available for CPU" even with GPU setting on.

### ISSUE THREAD

**Issue by tztechno** [Deci-AI/super-gradients#1547]
### 💡 Your Question

Recently, in YOLO-NAS custom training, when setting "mixed_precision": True along with GPU setting on, AssertionError occurred with this message: "mixed precision is not available for CPU." and program stopped even with GPU setting on.
I know this error was not seen before. Is there anyone encountering the same phenomenon?

**Comment by BloodAxe** [comment]
Thanks, this has been fixed in 3.3.1 release: https://github.com/Deci-AI/super-gradients/releases/tag/3.3.1

**Comment by tztechno** [comment]
I confirmed that it can be executed using GPU/CPU. Thank you.
