### ISSUE TITLE
Neg in ONNX

### ISSUE THREAD

**Issue by pbonazzi** [Deci-AI/super-gradients#1555]
https://github.com/Deci-AI/super-gradients/blob/68a96bb485cb0f411dce8c42d717da9e69362dee/src/super_gradients/training/utils/bbox_utils.py#L19C1-L19C24

Negations are not supported in certain MicroControllers / Accelerators
I recommend changing this line to :
```
    x1y1 = points - lt
```

**Comment by pbonazzi** [comment]
It also simplifies the graph 
see netron.app

**Comment by BloodAxe** [comment]
We merged the patch, thank for contributing!
