### ISSUE TITLE
Why does YOLONAS use more System RAM when using GPU than CPU?

### ISSUE THREAD

**Issue by georgemuriithi** [Deci-AI/super-gradients#1566]
### 💡 Question

I was testing object detection using YOLONAS and realized it uses more System RAM when using GPU than CPU.

I tested on a batch of 2 images, using coco pretrained weights, in Google Colab. The rest of the parameters remained constant and I just changed the fuse_model argument in model.predict() from True to False.

The following were the results:
![Screenshot from 2023-10-23 09-21-49](https://github.com/Deci-AI/super-gradients/assets/21691211/0afece1c-f6be-4632-8c59-0f7cb0a5b480)

The results were the same when testing on my local machine.

Why is more System RAM used when using GPU than CPU and how I can reduce that?

Thank you in advance :)

**Comment by BloodAxe** [comment]
I don't have answer for that. Probably investigating allocated memory and comparing living objects between two runs could shed some light on this. However this is not of a high priority and won't be investigated by our team.
