### ISSUE TITLE
How to custom YOLO-NAS model 

### ISSUE THREAD

**Issue by YoungHsu1002** [Deci-AI/super-gradients#1617]
### 💡 Your Question

Could you please advise on how I might modify the architecture of the model? I'm looking to make alterations and would appreciate some guidance on possible ways to approach this.

Like Two-stream-fusion detection.

**Comment by BloodAxe** [comment]
What are the exact modifications to the model you would like to achieve? Two inputs & shared backbone or what?

**Comment by CodingMonkey3688** [comment]
here: https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/recipes/arch_params/yolo_nas_s_arch_params.yaml
