### ISSUE TITLE
Labelled Image Output with Predictions

### ISSUE THREAD

**Issue by PrashantDixit-dev** [Deci-AI/super-gradients#1622]
### 🚀 Feature Request

model_predictions  = yolo_nas.predict(img, conf=0.5).save("ot.jpg")

Here I want to save image and also want predictions in output for postprocessing

**Comment by BloodAxe** [comment]
You have it:
```
model_predictions = yolo_nas.predict(img, conf=0.5)
model_predictions.save("./output_directory")

# Do whatever you want with `model_predictions`
# print(...)
```

**Comment by PrashantDixit-dev** [comment]
When I am saving image and trying to get prediction, it is throwing error

**Comment by PrashantDixit-dev** [comment]
When I am saving image and trying to get prediction, it is throwing error
