### ISSUE TITLE
Numpy VisibleDeprecationWarning

### ISSUE THREAD

**Issue by cawilchesp** [Deci-AI/super-gradients#1625]
### 🐛 Describe the bug

During prediction, a warning from Numpy showed only one time:
```
with sv.VideoSink(target_path=f"{target}.avi", video_info=video_info, codec="H264") as sink:
        for image in tqdm(frame_generator, total=video_info.total_frames, unit='frames'):
            annotated_image = image.copy()

            # Process YOLO-NAS detections
            results = list(yolo_nas_model.predict(image, conf=CONFIDENCE, fuse_model=False))[0]
```

The message is:
C:\anaconda3\envs\vision\lib\site-packages\numpy\lib\arraypad.py:487: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array(x)

### Versions

Numpy 1.23.0

**Comment by BloodAxe** [comment]
What is sv.VideoSink in this snippet?

**Comment by cawilchesp** [comment]
> What is sv.VideoSink in this snippet?

I'm sorry for not including more code, `sv` is for: `import supervision as sv`.
`sv.VideoSink` is to save a video from the processed frames.

The warning message appears only when executing the first time the line: `results = list(yolo_nas_model.predict(image, conf=CONFIDENCE, fuse_model=False))[0]`

I hope that helps

**Comment by BloodAxe** [comment]
We have a [fix ](https://github.com/Deci-AI/super-gradients/pull/1632)for that already which will land in 3.4.1 next week
