### ISSUE TITLE
How to train Semantic segmentation on custom dataset with pixel masks as input

### ISSUE THREAD

**Issue by james-imi** [Deci-AI/super-gradients#1627]
### 💡 Your Question

So my dataset is composed of an image and a corresponding pixel mask where 0 is the background, and each pixel is the classes (e.g. 0 to 5 for 6 classes including the background).

**Comment by shaydeci** [comment]
Hey @james-imi I suggest looking into the [segmentation tutorial notebooks](https://github.com/Deci-AI/super-gradients#semantic-segmentation-1).
More specifically, the 'How To Connect a Custom Dataset' one.
