### ISSUE TITLE
Get List of Specific Task Models

### ISSUE THREAD

**Issue by haritsahm** [Deci-AI/super-gradients#1630]
### 🚀 Feature Request

SG has a wide range of available models but it's hard to find which model is available for specific task without opening the documents. The only available methods are using the `registry.ARCHITECTURES` or `object_names.Models` that have the list of all available models or architectures.

I'm currently building a simple mlops pipeline that utilize super_gradients. I want to filter out which models are available for specific tasks (detection, classification, segmentation) and the only possible way to do it is to create a list/class that holds the list of models available for that task

### Proposed Solution (Optional)

Utilize the registry to create a new list for specific task models `registry.{DETECTION_MODELS, CLASSIFICATION_MODELS}`

```
DETECTION_MODELS = {}
register_det_model = create_register_decorator(registry=DETECTION_MODELS)

CLASSIFICATION_MODELS = {}
register_cls_model = create_register_decorator(registry=CLASSIFICATION_MODELS)

@register_model(Models.YOLO_NAS_S)
@register_det_model(Models.YOLO_NAS_S)
class YoloNAS_S(YoloNAS):
    pass
```

**Comment by shaydeci** [comment]
Hello @haritsahm,
We currently have other features in our pipeline we are focued on. However contributions are always welcome.
We will consider re-opening this issue in the future if there will be more demand for it.
