### ISSUE TITLE
Is possibile to select which layers to train?

### ISSUE THREAD

**Issue by eric-tc** [Deci-AI/super-gradients#1645]
### 💡 Your Question

Hi,
thanks for super gradients. I want to know if it is possible to select which layers to train using parameters from a recipe? Like having a list of layers and automatically freezing the other layers not included.

If not can you please give me some hint on how to do this for example with a resnet50 model?
Thanks

### Versions

3.4.1

**Comment by BloodAxe** [comment]
Yes, this will be available in 3.5 release. You can see this [PR](https://github.com/Deci-AI/super-gradients/pull/1612) with a preview what is needed to set this.
