### ISSUE TITLE
Predicting using Cityscapes

### ISSUE THREAD

**Issue by shovalfaibish** [Deci-AI/super-gradients#1646]
### 💡 Your Question

Hello,

I want to predict using the Cityscapes dataset and weights available from the model zoo.
I tried using [this notebook](https://colab.research.google.com/github/Deci-AI/super-gradients/blob/master/notebooks/quickstart_segmentation.ipynb) as a base, but I keep running into a problem with this line: `mask = ToPILImage()(mask.float())`
Since the function ToPILImage() takes an image with 1, 3 or 4 channels. I want to use all 19 classes of Cityscapes, is this possible? When I predict using 1, 3, 4 channels I don't get good results.

Thank you

**Comment by shaydeci** [comment]
@shovalfaibish We will introduce soon .predict() functionality for our segmentation models (like we have for YoloNAS).
The notebook's predict is fixed for binary labels,
