### ISSUE TITLE
Auto Augmentation Problem

### ISSUE THREAD

**Issue by 7Vyshak7** [Deci-AI/super-gradients#1656]
### 💡 Your Question

I have trained a YOLO-NAS L model for some Pavement markings like Crossmarks, Left arrow, Right arrow, Bike lane, Junction etc. While testing the model on Unseen data the right and left arrow is getting confused. Most right arrow is been identified as Left and vice versa. **So if there is some internal Flipping or other augmentation are there, where can I find that, and I want to remove all auto augmentations**

**Comment by BloodAxe** [comment]
You probably want to remove this augmentation https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/recipes/dataset_params/coco_detection_yolo_nas_dataset_params.yaml#L28

**Comment by 7Vyshak7** [comment]
@BloodAxe Thank You, This solves my issue...

**Comment by BloodAxe** [comment]
Glad it helped)

**Comment by BloodAxe** [comment]
Glad it helped)

**Comment by tdengs** [comment]
Hi, is there a way to remove it in the code? i.e. I tried the following but it's not working

![image](https://github.com/Deci-AI/super-gradients/assets/73059305/ceb8ee07-ced2-4627-9ab8-33bd1806adc8)
