### ISSUE TITLE
Erro when use pip install super-gradients

### ISSUE THREAD

**Issue by eumateuscandido** [Deci-AI/super-gradients#1658]
### 🐛 Describe the bug

I trying install super-gradients on jupyter notebook using !pip install super-gradients ang get this error:

  error: subprocess-exited-with-error
  
  Building wheel for pycocotools (pyproject.toml) did not run successfully.
  exit code: 1
  
  [17 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\coco.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\mask.py -> build\lib.win-amd64-cpython-310\pycocotools
  copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-310\pycocotools
  running build_ext
  C:\Users\USER\AppData\Local\Temp\pip-build-env-zm4t8rny\overlay\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\USER\AppData\Local\Temp\pip-install-zk69wcbg\pycocotools_7ed8db31a5e54fb3b9bf7830d670b434\pycocotools\_mask.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  Compiling pycocotools/_mask.pyx because it changed.
  [1/1] Cythonizing pycocotools/_mask.pyx
  building 'pycocotools._mask' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture=9

CurrentClockSpeed=1711

DeviceID=CPU0

Family=198

L2CacheSize=4096

L2CacheSpeed=

Manufacturer=GenuineIntel

MaxClockSpeed=2200

Name=12th Gen Intel(R) Core(TM) i7-1270P

ProcessorType=3

Revision=

Versions of relevant libraries:
[pip3] No relevant packages
[conda] No relevant packages

**Comment by BloodAxe** [comment]
As the name suggests - you need C++ compiler to build pycocotools:
```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

Please search in closed issues, since this is a common problem and there were suggestsion how to tackle that.

**Comment by cobaltautomationdev** [comment]
me, too. I already install c++, but still got this error.
![image](https://github.com/Deci-AI/super-gradients/assets/145321686/d5f7b780-9b9b-4cd8-b6d6-44f01d9d5ffb)
Building wheels for collected packages: pycocotools, termcolor, treelib, antlr4-python3-runtime, stringcase, future
  Building wheel for pycocotools (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-39
      creating build\lib.win-amd64-cpython-39\pycocotools
      copying pycocotools\coco.py -> build\lib.win-amd64-cpython-39\pycocotools
      copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-39\pycocotools
      copying pycocotools\mask.py -> build\lib.win-amd64-cpython-39\pycocotools
      copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-39\pycocotools
      running build_ext
      C:\Users\heyongli\AppData\Local\Temp\pip-build-env-d881ntpo\overlay\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\heyongli\AppData\Local\Temp\pip-install-_8cwmq8_\pycocotools_29e8548005774c608ebde2f056baf8f3\pycocotools\_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      Compiling pycocotools/_mask.pyx because it changed.
      [1/1] Cythonizing pycocotools/_mask.pyx
      building 'pycocotools._mask' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
