### ISSUE TITLE
Evaluate yolo_nas model with Yolov8

### ISSUE THREAD

**Issue by tjasmin111** [Deci-AI/super-gradients#1662]
### 💡 Your Question

According to Ultralytics docs [here](https://docs.ultralytics.com/models/yolo-nas/#usage-examples), we can use yolo to do predictions/val of a yolo-nas model like below:
`yolo val model=yolo_nas_s.pt data=coco8.yaml
`

I trained my NAS model, but it produces a .pth model (not .pt). So when I pass it to yolo, it complains about it. What should I do?

**Comment by BloodAxe** [comment]
I'm not sure why you trying to evaluate our model using third party repository.

Anything that goes beyond this repo is an external contribution and we provide no support on external stuff.
