### ISSUE TITLE
Aarch64 Install Ubuntu 22.04

### ISSUE THREAD

**Issue by StuartIanNaylor** [Deci-AI/super-gradients#1664]
### 🐛 Describe the bug

`pip install git+https://github.com/Deci-AI/super-gradients.git@stable`
```
  WARNING: Generating metadata for package onnx-simplifier produced metadata for project name onnxsim. Fix your #egg=onnx-simplifier fragments.
Discarding https://files.pythonhosted.org/packages/a5/65/56398c020ea361a879968d8f703ccf34fcb4ad172eff17b132f6948271ad/onnx-simplifier-0.4.35.tar.gz (from https://pypi.org/simple/onnx-simplifier/) (requires-python:>=3.7): Requested onnxsim from https://files.pythonhosted.org/packages/a5/65/56398c020ea361a879968d8f703ccf34fcb4ad172eff17b132f6948271ad/onnx-simplifier-0.4.35.tar.gz (from super-gradients==3.6.0rc32009) has inconsistent name: expected 'onnx-simplifier', but metadata has 'onnxsim'
  Using cached onnx-simplifier-0.4.34.tar.gz (20.1 MB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package onnx-simplifier produced metadata for project name onnxsim. Fix your #egg=onnx-simplifier fragments.
Discarding https://files.pythonhosted.org/packages/0a/03/9e4224cd6baf914eefd3f04512f85a67647c70b3ceb25e73c0b42262e0d0/onnx-simplifier-0.4.34.tar.gz (from https://pypi.org/simple/onnx-simplifier/) (requires-python:>=3.7): Requested onnxsim from https://files.pythonhosted.org/packages/0a/03/9e4224cd6baf914eefd3f04512f85a67647c70b3ceb25e73c0b42262e0d0/onnx-simplifier-0.4.34.tar.gz (from super-gradients==3.6.0rc32009) has inconsistent name: expected 'onnx-simplifier', but metadata has 'onnxsim'
  Using cached onnx-simplifier-0.4.33.tar.gz (20.1 MB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package onnx-simplifier produced metadata for project name onnxsim. Fix your #egg=onnx-simplifier fragments.
Discarding https://files.pythonhosted.org/packages/e5/cf/530c3645de1461841ad677b500726fe26b554d9f7e987f83099042fc41c8/onnx-simplifier-0.4.33.tar.gz (from https://pypi.org/simple/onnx-simplifier/) (requires-python:>=3.7): Requested onnxsim from https://files.pythonhosted.org/packages/e5/cf/530c3645de1461841ad677b500726fe26b554d9f7e987f83099042fc41c8/onnx-simplifier-0.4.33.tar.gz (from super-gradients==3.6.0rc32009) has inconsistent name: expected 'onnx-simplifier', but metadata has 'onnxsim'
  Using cached onnx-simplifier-0.4.31.tar.gz (20.1 MB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package onnx-simplifier produced metadata for project name onnxsim. Fix your #egg=onnx-simplifier fragments.
Discarding https://files.pythonhosted.org/packages/52/cc/1d98036bbca75422a7d22b2ea932dd548fac6275f70debaf5272f3235876/onnx-simplifier-0.4.31.tar.gz (from https://pypi.org/simple/onnx-simplifier/) (requires-python:>=3.7): Requested onnxsim from https://files.pythonhosted.org/packages/52/cc/1d98036bbca75422a7d22b2ea932dd548fac6275f70debaf5272f3235876/onnx-simplifier-0.4.31.tar.gz (from super-gradients==3.6.0rc32009) has inconsistent name: expected 'onnx-simplifier', but metadata has 'onnxsim'
  Using cached onnx-simplifier-0.4.30.tar.gz (20.1 MB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package onnx-simplifier produced metadata for project name onnxsim. Fix your #egg=onnx-simplifier fragments.
Discarding https://files.pythonhosted.org/packages/4f/ce/a0426de4d0a10ea601239d3c154ed37442049cd9744e0c6be3bbfa6a29bd/onnx-simplifier-0.4.30.tar.gz (from https://pypi.org/simple/onnx-simplifier/) (requires-python:>=3.7): Requested onnxsim from https://files.pythonhosted.org/packages/4f/ce/a0426de4d0a10ea601239d3c154ed37442049cd9744e0c6be3bbfa6a29bd/onnx-simplifier-0.4.30.tar.gz (from super-gradients==3.6.0rc32009) has inconsistent name: expected 'onnx-simplifier', but metadata has 'onnxsim'
...
```

### Versions

PyTorch version: 2.1.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.10.160-rockchip-aarch64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       ARM
Model name:                      Cortex-A55
Model:                           0
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        r2p0
CPU max MHz:                     1800.0000
CPU min MHz:                     408.0000
BogoMIPS:                        48.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
Model name:                      Cortex-A76
Model:                           0
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       2
Stepping:                        r4p0
CPU max MHz:                     2304.0000
CPU min MHz:                     408.0000
BogoMIPS:                        48.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
L1d cache:                       384 KiB (8 instances)
L1i cache:                       384 KiB (8 instances)
L2 cache:                        2.5 MiB (8 instances)
L3 cache:                        3 MiB (1 instance)
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable: Unprivileged eBPF enabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torch==2.1.1
[pip3] torchvision==0.16.1
[conda] Could not collect

**Comment by BloodAxe** [comment]
Thanks! The fix should be pretty easy)
