### ISSUE TITLE
SSD model training error: The size of tensor a (12828) must match the size of tensor b (25600) at singleton dimension 2

### ISSUE THREAD

**Issue by Arbaaz-Shaikh** [Deci-AI/super-gradients#1673]
### 💡 Your Question

I am training a ssd model with my custom data.
Below is the code:

Data loading:

train_data = coco_detection_yolo_format_train(
dataset_params={
"data_dir": dataset_params ["data_dir"],
"input_dim": [640, 640],
"images_dir": dataset_params ["train_images_dir"],
"labels_dir": dataset_params ["train_labels_dir"],
"classes": dataset_params ["classes"],
dataloader_params={
*batch_size' :BATCH_SIZE, num_workers': WORKERS
｝
val_data = coco_detection_yolo_format_vall
dataset_params={
"data_dir": dataset_params ["data_dir"],
"input_dim": [640, 6401,
"images_dir": dataset_params ["val_images_dir"],
"labels_dir": dataset_params ["val_labels_dir"],
"classes": dataset_params ["classes"1,
dataloader_params={
'batch_size' :BATCH_SIZE,
‘num_workers' :WORKERS
},
)

Data is loading perfectly.

I think the main problem starts from here:

# Set the number of classes
num_classes = len(dataset_params['classes'])

# Create an instance of DefaultBoxes with the required parameters
fig_size = (640, 640)  # Replace with the appropriate input image size
feat_size = [(40, 40), (20, 20), (10, 10), (5, 5), (3, 3), (1, 1)]  # These are just example values, adjust based on your model
aspect_ratios = [
    [(1, 2, 1/2), (1, 2, 1/2), (1, 2, 1/2)],
    [(1, 2, 1/2), (1, 2, 1/2), (1, 2, 1/2)],
    [(1, 2, 1/2), (1, 2, 1/2), (1, 2, 1/2)],
    [(1, 2, 1/2), (1, 2, 1/2), (1, 2, 1/2)],
    [(1, 2, 1/2), (1, 2, 1/2), (1, 2, 1/2)],
    [(1, 2, 1/2), (1, 2, 1/2), (1, 2, 1/2)]
]  # Modify this line to match your desired aspect_ratios
scales = [0.1, 0.2, 0.5, 0.9, 1.1, 1.5]  # Modify this line to match your desired scales

# Create a list to store DefaultBoxes instances for each feature map
default_boxes_list = []

for idx, feat_size_value in enumerate(feat_size):
    sk1 = scales[idx]
    sk2 = sqrt(sk1 * scales[(idx + 1) % len(scales)])
    sk3 = sqrt(sk1 * sk2)

    # Note: The constructor of DefaultBoxes expects aspect_ratios and scales directly
    default_boxes = DefaultBoxes(fig_size, feat_size_value, scales, aspect_ratios[idx], scale_xy=sk1, scale_wh=sk3)
    default_boxes_list.append(default_boxes)

# Instantiate the SSDLoss with a single instance of DefaultBoxes
ssd_loss = SSDLoss(dboxes=default_boxes_list[0])  # Use the first set of default boxes

# Set the training parameters
train_params = {
    'max_epochs': MAX_EPOCHS,
    'lr_mode': 'CosineLRScheduler',
    'optimizer': 'SGD',
    'optimizer_params': {'momentum': 0.9, 'weight_decay': 0.0005, 'nesterov': True},
    'loss': ssd_loss,  # Use the instantiated SSDLoss with default boxes
    'valid_metrics_list': [{'DetectionMetrics': {'post_prediction_callback': SSDPostPredictCallback(), 'num_cls': num_classes}}],
    'metric_to_watch': 'mAP@0.50:0.95',
    'average_best_models': True,
    'initial_lr': 0.01,
    'warmup_momentum': 0.8,
    'warmup_bias_lr': 0.1,
}

trainer = Trainer(
        experiment_name=EXPERIMENT_NAME,
        ckpt_root_dir=checkpoint_dir,
    )

model = models.get(
        MODEL_ARCH,
        num_classes=len(dataset_params['classes']),
        # pretrained_weights="coco"
    )

mlflow.set_experiment("mlflow-experiment")
with mlflow.start_run():
    mlflow.pytorch.autolog(log_models=False, log_datasets=False)

    trainer.train(
        model=model,
        training_params=train_params,
        train_loader=train_data,
        valid_loader=val_data
    )
    best_model = models.get(
        MODEL_ARCH,
        num_classes=len(dataset_params['classes']),
        checkpoint_path=f"{trainer.checkpoints_dir_path}/average_model.pth"
    ).to(DEVICE)

    test_results = trainer.test(
    model=best_model,
    test_loader=test_data,
    test_metrics_list=DetectionMetrics_050(
        num_cls=len(dataset_params['classes']),
        post_prediction_callback=SSDPostPredictCallback()
    )
)

Error:
 

RuntimeError: The size of tensor a (12828) must match the size of tensor b (25600) at non-singleton dimension 2

Any help will be appreciated.
Thank you

**Comment by Arbaaz-Shaikh** [comment]
@BloodAxe please reply.

**Comment by Arbaaz-Shaikh** [comment]
I have resolved it by going through the yaml files
ssd_anchors.yaml

need more quality documentation on this part because it is very critical information required to train the ssd model.

**Comment by BloodAxe** [comment]
Glad you figured it out! Do you mind sharing more information what was the issue and what was wrong with docs? 
BTW you are more than welcome to open a PR and improve docs if some pieces there are incorrect/outdated of you want 😎
