### ISSUE TITLE
YOLO NAS export ONNX Dynamic

### ISSUE THREAD

**Issue by kevinzezel** [Deci-AI/super-gradients#1674]
### 💡 Your Question

How to export a YOLO NAS model to onnx with dynamic = True?

Regards,
Kevin

**Comment by BloodAxe** [comment]
We haven't tested ONNX export with dynamic shapes and `model.export()` is not designed to support dynamic shapes (At least for current 3.5.0 release).

You can however try exporting a model using `torch.onnnx.export` and specify dynamic axis during export. I believe this should work, but the model you will obtain will not have the NMS postprocessing.
