### ISSUE TITLE
super-gradients is not working with opencv-python-headless only

### ISSUE THREAD

**Issue by JT-MODE** [Deci-AI/super-gradients#1689]
### 💡 Your Question

I use opencv-python-headless on my headless machine. When I try to run a command like this: 

import super_gradients

I get an error:

WARNING - env_sanity_check.py - Failed to verify installed packages: opencv-python required but not found

Is it possible to run your framework with opencv-python-headless only?

**Comment by BloodAxe** [comment]
This is not an error, this is a warning message. 
It indicates the requirements for `opencv-python` are not met (Obviously, as you have headless version installed). 
You should be fine with `opencv-python-headless` though.
