### ISSUE TITLE
Where is deciseg

### ISSUE THREAD

**Issue by xbkaishui** [Deci-AI/super-gradients#1716]
### 🚀 Feature Request

Hello: 
I saw in the [blog](https://deci.ai/blog/semantic-segmentation-sota-architectures/) describe deciseg model, but can't find in the source code, just wonder is it avaiable in public?  how can I try the deciseg model 

thanks

**Comment by BloodAxe** [comment]
DeciSeg is available for the Deci's customers and this architecture is not publicly available.

**Comment by xbkaishui** [comment]
ok got it. how to be your customers

**Comment by BloodAxe** [comment]
Probably [booking a demo](https://deci.ai/schedule-demo/) would be the easiest way to learn more about Deci's offerings.

**Comment by xbkaishui** [comment]
hello, I have booking a demo last week, but no one get in touch with me. can you give some help? thanks

**Comment by ziviziv** [comment]
Please put here your email. I'll reach out directly

**Comment by xbkaishui** [comment]
> Please put here your email. I'll reach out directly

Hello,  email is xingbing@digitalpredict.cn.
