### ISSUE TITLE
Classification with YOLO NAS Pose

### ISSUE THREAD

**Issue by matteomarjanovic** [Deci-AI/super-gradients#1722]
### 💡 Your Question

Hi,

I'm sorry if the question is dumb, but I'd like to know if it's possible to have the classification of the object along with the bounding box and the pose, in yolo nas pose inference.

If yes, I'm not able to find how in the code.

Thanks!

**Comment by BloodAxe** [comment]
YoloNAS pose is trained of pose estimation on a single class - humans.
There are no other classes in this model. 
Sorry but we don't have the "joint" model to do 80-class object detection and human pose estimation task simultaneously.
