### ISSUE TITLE
unreasonable output after exporting to onnx 

### ISSUE THREAD

**Issue by tooichitake** [Deci-AI/super-gradients#1753]
### 💡 Your Question

ImageDetectionPrediction(image=array([[[ 55,  73,  93],
        [ 55,  73,  92],
        [ 58,  75,  95],
        ...,
        [213, 201, 182],
        [213, 201, 182],
        [213, 201, 182]],

       [[ 57,  75,  96],
        [ 57,  74,  97],
        [ 57,  75,  96],
        ...,
        [214, 202, 183],
        [214, 202, 183],
        [213, 201, 182]],

       [[ 60,  77, 100],
        [ 59,  77, 100],
        [ 57,  74,  98],
        ...,
        [214, 202, 183],
        [214, 202, 183],
        [214, 202, 183]],

       ...,

       [[ 38,  49,  51],
        [ 38,  49,  51],
        [ 38,  49,  51],
        ...,
        [174, 198, 212],
        [174, 198, 212],
        [174, 198, 212]],

       [[ 38,  49,  51],
        [ 38,  49,  51],
        [ 38,  49,  51],
        ...,
        [175, 199, 213],
        [176, 200, 214],
        [175, 199, 212]],

       [[ 37,  48,  51],
        [ 37,  48,  51],
        [ 37,  48,  51],
        ...,
        [176, 200, 214],
        [176, 200, 213],
        [176, 201, 212]]], dtype=uint8), prediction=DetectionPrediction(bboxes_xyxy=array([[340.25, 415.5 , 365.5 , 457.25],
       [489.25, 384.75, 515.  , 418.5 ]], dtype=float32), confidence=array([0.7402344 , 0.40771484], dtype=float32), labels=array([1., 1.], dtype=float32)), class_names=('A', 'B'))
This is before export, which is the original pth. format. However, after exporting to onnx format. It becomes:[[[-6.1469555e-02 -1.7411280e-01  5.4508118e+01  2.0952858e+01]
  [-3.5952187e-01 -6.5043926e-02  5.7374405e+01  2.9069407e+01]
  [-9.8688889e-01 -5.9130192e-02  5.6417435e+01  2.5949154e+01]
  ...
  [ 3.9930933e+02  5.0614914e+02  6.4729034e+02  6.4378088e+02]
  [ 4.3487637e+02  5.0238599e+02  6.4857166e+02  6.4466669e+02]
  [ 4.6666125e+02  4.9133246e+02  6.5076910e+02  6.5134937e+02]]]
[[[-6.1469555e-02 -1.7411280e-01  5.4508118e+01  2.0952858e+01]
  [-3.5952187e-01 -6.5043926e-02  5.7374405e+01  2.9069407e+01]
  [-9.8688889e-01 -5.9130192e-02  5.6417435e+01  2.5949154e+01]
  ...
  [ 3.9930933e+02  5.0614914e+02  6.4729034e+02  6.4378088e+02]
  [ 4.3487637e+02  5.0238599e+02  6.4857166e+02  6.4466669e+02]
  [ 4.6666125e+02  4.9133246e+02  6.5076910e+02  6.5134937e+02]]] Even have negtive output. I do not think this can be a bbox. And, I tested with official model exporting to onnx. It also show negetive output. Why this happen?

**Comment by BloodAxe** [comment]
Have you tried visualizing predictions from the torch model and exported one?
I'm really curious to see the visuals there. See https://github.com/Deci-AI/super-gradients/blob/8c022d5943bccd01e77769f8b1ad73d38eca5fdb/src/super_gradients/examples/model_export/models_export.ipynb for the example.


Since the prediction showed here contains custom classes I assume you have trained your model manually.
Keep in mind that if you are export a model with postprocessing (Enabled by default) and preprocessing (Enabled by default) then image normalization step and size preprocessing from the validation dataset will be embedded in the exported model so you don't need to normalize the image beforehand.

Also, the predictions of the model are not clipped to the image boundary which indeed can cause small negative values.

That is all I can comment at this point with the information provided.

**Comment by tooichitake** [comment]
Thanks, this problem has been solved after remove my own preprocess and postprocess.
However, I found the input size of the exported onnx model was not the same as I expected.
This is the code:
model = models.get(Models.YOLO_NAS_S, checkpoint_path='checkpoint_dir/ax/RUN_20240110_193055_514997/ckpt_best.pth',num_classes=2)
models.convert_to_onnx(model=model, input_shape=(3,160,160), out_path="yolo_nas_s_160.onnx")
export_result = model.export("yolo_nas_s_160.onnx")
print(export_result)

output:
Model exported successfully to yolo_nas_s_160.onnx
Model expects input image of shape [1, 3, 640, 640]
Input image dtype is torch.uint8
Exported model already contains preprocessing (normalization) step, so you don't need to do it manually.
Preprocessing steps to be applied to input image are:
Sequential(
  (0): CastTensorTo(dtype=torch.float32)
  (1): ChannelSelect(channels_indexes=tensor([2, 1, 0]))
)

Exported model contains postprocessing (NMS) step with the following parameters:
    num_pre_nms_predictions=1000
    max_predictions_per_image=1000
    nms_threshold=0.65
    confidence_threshold=0.5
    output_predictions_format=batch

Exported model is in ONNX format and can be used with ONNXRuntime
To run inference with ONNXRuntime, please use the following code snippet:

    import onnxruntime
    import numpy as np
    session = onnxruntime.InferenceSession("yolo_nas_s_160.onnx", providers=["CUDAExecutionProvider", "CPUExecutionProvider"])
    inputs = [o.name for o in session.get_inputs()]
    outputs = [o.name for o in session.get_outputs()]
    example_input_image = np.zeros((1, 3, 640, 640)).astype(np.uint8)
    predictions = session.run(outputs, {inputs[0]: example_input_image})

Exported model has predictions in batch format:

    num_detections, pred_boxes, pred_scores, pred_classes = predictions
    for image_index in range(num_detections.shape[0]):
      for i in range(num_detections[image_index,0]):
        class_id = pred_classes[image_index, i]
        confidence = pred_scores[image_index, i]
        x_min, y_min, x_max, y_max = pred_boxes[image_index, i]
        print(f"Detected object with class_id={class_id}, confidence={confidence}, x_min={x_min}, y_min={y_min}, x_max={x_max}, y_max={y_max}")

My training input size is (640,640). But I want to export with another input size. Although I set the input size to (160,160) at "model = models.get()" function, it didn't work. Also, I want to know How to export with FP16.

**Comment by BloodAxe** [comment]
You are doing two exports here:

```
models.convert_to_onnx(model=model, input_shape=(3,160,160), out_path="yolo_nas_s_160.onnx")
export_result = model.export("yolo_nas_s_160.onnx")
```

Please avoid using `convert_to_onnx` as it is deprecated in favor of `model.export()`

If if want to use custom input image shape then you can specify image shape (rows, cols) as follows:

```
export_result = model.export("yolo_nas_s_160.onnx", input_image_shape=(custom_image_height, custom_image_width))
```

That should be enough to use model at custom resolution

**Comment by tooichitake** [comment]
Thanks! Problems all solved!
I hope you can develop yolo_mas_n model like yolov8_n, the smallest model of yolo-nas that I can find is s, but s is still quit big for some tasks.
