### ISSUE TITLE
Jetson DLA  support for ONNX model

### ISSUE THREAD

**Issue by ranjitkathiriya544** [Deci-AI/super-gradients#1760]
Hello,

I have convert my model to onnx format, now I want that model to run in jetson using DLA (Deep Learning Accelerator). 

The steps followed by me for conversion is:

1. pth -> Onnx: I have converted my model to INT8 Quantization, tensorrt as a Target Backend, Document was very helpful, thanks!

https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/examples/model_export/models_export.ipynb

2. Convert this onnx model to .trt format using: 

`./trtexec --onnx=<onnx model> --saveEngine=<engin file -save path>.trt --explicitBatch --int8 --useDLACore=0 --allowGPUFallback --useSpinWait`

if I try to run this script, then 

`Node: /model/heads/head3/cls_convs/cls_convs.0/seq/act/Relu cannot run in INT8 mode due to missing scale and zero point. This node will not run on DLA.`

I am getting this warning for every layers in model, and every layers are loading in GPU, not on DLA. 

Thanks in advance for help!

**Comment by ranjitkathiriya544** [comment]
Any update on this?

**Comment by BloodAxe** [comment]
DLA offers very limited support of ONNX layers. And I'm not sure we will be ready to provide a support on this matter as DLA support goes outside SG scope of responsibility.

**Comment by ranjitkathiriya544** [comment]
thanks for reply!
