### ISSUE TITLE
DetectionVisualization is generating images that seem to have many samples blended in together

### ISSUE THREAD

**Issue by ani-mal** [Deci-AI/super-gradients#1761]
### 💡 Your Question

I have implemented a custom callback to log some metrics to MLFlow, and I am trying to visualize how the model is predicting during the validation. I am using the `DetectionVisualization` for that, however the saved image seems to be corrupted. 

code: 

```cpp
        @multi_process_safe
        def on_validation_loader_end(self, context: PhaseContext) -> None:
           # mlflow logging metrics logic 
            
            # SOME CALCULATIONS ARE IN-PLACE IN NMS, SO CLONE THE PREDICTIONS
            preds = (context.preds[0].clone(), None)
            preds = self.post_prediction_callback(preds)
            batch_imgs = DetectionVisualization.visualize_batch(context.inputs, preds, context.target, self.batch_idx, self.classes)
   
            batch_imgs = np.stack(batch_imgs)
            for i, img in enumerate(batch_imgs):
                cv2.imwrite(f'batch_image_{context.epoch}_{i}.png', img)

           # TODO: log image to mlflow
```

Result:
![image](https://github.com/Deci-AI/super-gradients/assets/36199397/c89d1073-1492-4842-89b3-c80a5083d223)

It seems like all or the batch size of the validation images are being blended together, original images:

![image](https://github.com/Deci-AI/super-gradients/assets/36199397/55b2c9a5-87c3-4bc6-94f4-168d41f56d56)

How can I get one image per prediction with the bounding boxes drawn?

### Versions

SuperGradient 3.5 

CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.15.5
Libc version: glibc-2.31

Python version: 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1040-azure-x86_64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 470.199.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   48 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7V12 64-Core Processor
Stepping:                        0
CPU MHz:                         2445.433
BogoMIPS:                        4890.86
Hypervisor vendor:               Microsoft
Virtualization type:             full
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        2 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Mitigation; untrained return thunk; SMT disabled
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr rdpru arat umip rdpid

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.13.0
[pip3] onnx-simplifier==0.4.35
[pip3] onnxruntime==1.13.1
[pip3] torch==2.1.2
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] torch                     2.1.2                    pypi_0    pypi
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchvision               0.16.2                   pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

**Comment by Louis-Dupont** [comment]
Hi @ani-mal , I believe that what you see is not a bug but is the consequence of your dataset `transforms`.
Basically, it looks like there is a mixup between an image and another image with "mosaic'.
So, I believe that if you remove these transformations, you should not see this "corrupted" aspect.
Could you please retry without these augmentation steps ?

**Comment by ani-mal** [comment]
@Louis-Dupont I am not adding any augmentation step, unless that is build in the dataloaders provided by super gradient:

```yaml
train_dataloader: coco_detection_yolo_format_train
val_dataloader: coco_detection_yolo_format_val
```

**Comment by shaydeci** [comment]
@ani-mal like @Louis-Dupont suggested - to me it seems like you are indeed seeing images that had mosaic and/or mixup applied to them.
Do you see this happening in both train and validation data loader?
The reason I am asking, is that these data loaders have pre defined transforms so that users can just plug them easily and start training fast.
If you follow the coco_detection_yolo_format_train implementation, you will see it is defined by the configuration file:
super_gradients/recipes/dataset_params/coco_detection_yolo_format_base_dataset_params.yaml

There you will see, that indeed that mosaic and mixup transforms are applied, but only on the train set.
You can of course, override the transforms by spedfying other ones in `dataset_params`, under `train_dataset_params`' `transforms`.

**Comment by ani-mal** [comment]
@shaydeci Thank you for your insights. I think what was happening is that the `context.target` on the `validation_loader_end` were images from the `train` dataset loader. Since, after inspecting the `super_gradients/recipes/dataset_params/coco_detection_yolo_format_base_dataset_params.yaml` and verifying my recipe. I am using the `train` dataloader for training and `val` dataloader for validation. So now, I am calling `DetectionVizualization` from `on_validation_batch_end`, and the mosaic and mixup transform dont seem to be there. The image is not perfect, but tweaking the a custom `undo_image_processing` should get me there. 

Also thank you for the latest release, there was a casting bug inside `DetectionVisualization._visualize_image` that I changed locally to make this code work, and with the newest release it has been fix :D

**Comment by shaydeci** [comment]
@ani-mal Glad to help (:
I am closing this issue down as it seems the problem is solved.
Feel free to re-open it if it ends up it was another problem, or open another issue.
