### ISSUE TITLE
How to print and save validation metrics results?

### ISSUE THREAD

**Issue by rupher3222** [Deci-AI/super-gradients#1766]
### 💡 Your Question

How can I train a custom dataset like YOLOV8 so that it automatically generates validation metrics results (F1-score, p-r curve, mAP@0.5, mAP@0.5_0.95, Precision, Recall) and also saves the graphs related to them? I have no idea how to modify the code for this. Please help!!

**Comment by BloodAxe** [comment]
There is a PR related to this issue https://github.com/Deci-AI/super-gradients/pull/1772
