### ISSUE TITLE
Can I constrain the size of yolo-nas during training?

### ISSUE THREAD

**Issue by Pzzzzzzzzz** [Deci-AI/super-gradients#1771]
### 💡 Your Question

I trained a yolo-nas but his memory size is too large, is there a way to constrain the size during training

**Comment by BloodAxe** [comment]
Please provide additional information. What memory you are talking about? How much is too much? How much is not? So was you able to train or not?

**Comment by Pzzzzzzzzz** [comment]
> Please provide additional information. What memory you are talking about? How much is too much? How much is not? So was you able to train or not?

I can do the training, but I would like to keep the model size under control, I have tried to train it before and got a model of 224MB, which is  big

**Comment by BloodAxe** [comment]
If you are talking about checkpoint size - this is expected since optimized state and other stuff is serialized there. 
Can you elaborate why is it an issue? You can always take this checkpoint and remove unwanted parts and get smaller file.

**Comment by ShpihanVlad** [comment]
Hi, @BloodAxe , could you please elaborate on how to remove these parts, and describe which parts are important for inference, so model becomes inference-only if we are not planning on making any experiments with it further?
