### ISSUE TITLE
yolo-nas sem

### ISSUE THREAD

**Issue by POVTUASTHOV** [Deci-AI/super-gradients#1775]
### 💡 Your Question

i want to learn about yolo nas with segmentation. but I tested with 1 image and got an error, can you help me?

from super_gradients.common.object_names import Models
from super_gradients.training import models

model = models.get(model_name=Models.PP_LITE_T_SEG75, pretrained_weights="cityscapes")

IMAGES = [
    "https://deci-pretrained-models.s3.amazonaws.com/sample_images/beatles-abbeyroad.jpg",
]

predictions = model.predict(IMAGES)
predictions.show()
predictions.save(output_folder="")  # Save in working directory

AttributeError: 'PPLiteSegT' object has no attribute 'predict'

**Comment by Louis-Dupont** [comment]
Hi @POVTUASTHOV, the `.predict` API for segmentation models is still in our roadmap.
Until we release it, you can write a few lines of code to do the same, as shown in [this collab notebook](https://colab.research.google.com/github/Deci-AI/super-gradients/blob/master/notebooks/how_to_run_model_predict.ipynb) (check the segmentation part).
Hoping this helps!
