### ISSUE TITLE
How to register a new architecture in the model zoo

### ISSUE THREAD

**Issue by ZYX-MLer** [Deci-AI/super-gradients#1776]
### 💡 Your Question

"May I use recipes to define a new network architecture that is not present in the model zoo? I've noticed that the model_name parameter in models.get must be one already defined in ARCHITECTURES. How can I add a new network structure to ARCHITECTURES, and could you provide an example? Thank you."

**Comment by shaydeci** [comment]
@ZYX-MLer please see https://github.com/Deci-AI/super-gradients/tree/master/src/super_gradients/common/registry
