### ISSUE TITLE
If i do QAT, what is the minimum version of Tensorrt I should use?

### ISSUE THREAD

**Issue by Bananaspirit** [Deci-AI/super-gradients#1777]
### 💡 Your Question

Hi, I'm working with nvidia jetson TX2 and I need to do QAT for yolox model. For Jetson TX2 the most accessible version of Tensorrt is 8.2.5.1. Yesterday I found in your repository the minimum [requirement](https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/BenchmarkingYoloNAS.md#:~:text=TensorRT%20version%20%3E%3D%208.4) for SG and Tensorrt to work is version 8.4 or higher for Tensorrt.

Is this requirement key to using SG?

What approaches can be used for quantization for quantization during training under tensorrt 8.2.5.1?

**Comment by cntontis** [comment]
Any news on this one? we are training a yolo-nas model and our jetson has a hard dependency on tensorRT 8.2.1.9. 
We are able to convert the model to tensorRT fine but whenever we run it only 1 (the box confidences) of the 4 outputs has results the rest are full of zeros

**Comment by cntontis** [comment]
We were eventually able to use our yolo nas pose model by using [this](https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/utils/export_yolonas.py) script to convert it

**Comment by BloodAxe** [comment]
8.6 is the minimum version of TRT if you want to have end-to-end model with postprocessing and NMS.
