### ISSUE TITLE
How can I visualize pose estimation results during the training process

### ISSUE THREAD

**Issue by ZYX-MLer** [Deci-AI/super-gradients#1793]
### 💡 Your Question

How can I visualize pose estimation results during the training process? I found a class called DEKRVisualizationCallback, but this class inherits from PhaseCallback instead of Callback. When I placed this class directly in phase_callbacks, I found that it did not trigger. 

Best wishes.

**Comment by BloodAxe** [comment]
Please see this example https://github.com/Deci-AI/super-gradients/blob/46cdc18a14c9ed96b69c8e6aad94ae10404b9cd5/src/super_gradients/recipes/training_hyperparams/coco2017_yolo_nas_pose_train_params.yaml#L61
