### ISSUE TITLE
YOLO NAS PREDICTION ERROR IMAGEDETECTIONOBJECT is not iterable

### ISSUE THREAD

**Issue by ZIDANE2003** [Deci-AI/super-gradients#1798]
### 🐛 Describe the bug

 result = list(best_model.predict(img_url, conf=0.35))[0]
[2024-01-27 13:09:10] INFO - pipelines.py - Fusing some of the model's layers. If this takes too much memory, you can deactivate it by setting `fuse_model=False`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-51-b1c8179d8cf9>](https://localhost:8080/#) in <cell line: 1>()
----> 1 result = list(best_model.predict(img_url, conf=0.35))[0]

TypeError: 'ImageDetectionPrediction' object is not iterable

for image_prediction in images_predictions:
    class_names = image_prediction.class_names
    labels = image_prediction.prediction.labels
    confidence = image_prediction.prediction.confidence
    bboxes = image_prediction.prediction.bboxes_xyxy

    for i, (label, conf, bbox) in enumerate(zip(labels, confidence, bboxes)):
        print("prediction: ", i)
        print("label_id: ", label)
        print("label_name: ", class_names[int(label)])
        print("confidence: ", conf)
        print("bbox: ", bbox)
        print("--" * 10)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-26-2df3a9eaa2af>](https://localhost:8080/#) in <cell line: 1>()
----> 1 for image_prediction in images_predictions:
      2     class_names = image_prediction.class_names
      3     labels = image_prediction.prediction.labels
      4     confidence = image_prediction.prediction.confidence
      5     bboxes = image_prediction.prediction.bboxes_xyxy

TypeError: 'ImageDetectionPrediction' object is not iterable

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by ZIDANE2003** [comment]
I dont understand i am running notebook on colab, before colab was executing the prediction part code without error but now it is not , am using yolo nas but to access prediction result it is throwing error. Colab was giving output before but it is producing error now.

**Comment by ZIDANE2003** [comment]
is this the issue of colab

**Comment by BloodAxe** [comment]
Do you mind specifying what colab notebook are you attempting to run?

**Comment by BloodAxe** [comment]
https://github.com/Deci-AI/super-gradients/issues/1801#issuecomment-1916521475 Proper way of using prediction for single image. Please update your notebook .
