### ISSUE TITLE
How do I get detected labels in print format,as in 3.5 version we can use loop to get that but In latest version it is producing an error using loop so how we can get detected objects as an output 

### ISSUE THREAD

**Issue by PEERMOH-tech** [Deci-AI/super-gradients#1801]
for image_prediction in images_predictions:
    class_names = image_prediction.class_names
    labels = image_prediction.prediction.labels
    confidence = image_prediction.prediction.confidence
    bboxes = image_prediction.prediction.bboxes_xyxy

    for i, (label, conf, bbox) in enumerate(zip(labels, confidence, bboxes)):
        print("prediction: ", i)
        print("label_id: ", label)
        print("label_name: ", class_names[int(label)])
        print("confidence: ", conf)
        print("bbox: ", bbox)
        print("--" * 10)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-7b64588141eb> in <cell line: 1>()
----> 1 for image_prediction in images_predictions:
      2     class_names = image_prediction.class_names
      3     labels = image_prediction.prediction.labels
      4     confidence = image_prediction.prediction.confidence
      5     bboxes = image_prediction.prediction.bboxes_xyxy

TypeError: 'ImageDetectionPrediction' object is not iterable

**Comment by BloodAxe** [comment]
If your input is a **single image** simply don't iterate over it:

```
result = model.predict("image.jpg")

class_names = result.class_names
labels      = image_prediction.prediction.labels
confidence  = image_prediction.prediction.confidence
bboxes      = image_prediction.prediction.bboxes_xyxy
```

**Comment by PEERMOH-tech** [comment]
I run the code it is giving labels, conf, bbboxes correctly for single input image  but it is not providing that particular detected class label instead it is providing all database labels as an output.

'''class_names = image_prediction.class_names
labels      = image_prediction.prediction.labels
confidence  = image_prediction.prediction.confidence
bboxes      = image_prediction.prediction.bboxes_xyxy'''
