### ISSUE TITLE
YoloNAS-pose-s seems not better than yolov8s-pose?

### ISSUE THREAD

**Issue by J0eky** [Deci-AI/super-gradients#1803]
### 💡 Your Question

I used yolov8s-pose and yolonas-pose-s respectively to predict the same image. The prediction results show that the confidence level of the bounding boxes predicted by the former is higher than that of the latter. Additionally, the former can detect more people. Therefore, it seems that the statement in the advertisement claiming that yolonas-pose is better than yolov8-pose does not quite match the actual results.

here is my code:
1. use yolov8s-pose
   model = YOLO('yolov8s-pose.pt')
  results = model.predict('dance.jpg', conf=0.5) 
[
![test1](https://github.com/Deci-AI/super-gradients/assets/105731709/31b9ad53-29de-4957-8f83-f30f59f289c4)
](url)
2. use yolonas-pose-s
yolo_nas_pose = models.get(Models.YOLO_NAS_POSE_S, pretrained_weights="coco_pose")
prediction = yolo_nas_pose.predict("dance.jpg", conf=0.5)
![test2](https://github.com/Deci-AI/super-gradients/assets/105731709/e5244446-53bd-43ba-ad66-5fc4ec5141e6)

**Comment by BloodAxe** [comment]
It's hard to confirm or deny your statement by one cherry-picked image. 
According to your evaluation on COCO dataset, indeed YoloNAS Pose performs better in terms or accuracy and latency than corresponding YoloV8 Pose variants.

Even the attached screenshots demonstrate this - take a look at the right arm of the lady in front. 
It may be true that confidence threshold should be tuned, but this is not a signal that one model is better or worse than the other. It may indicate one model is overly pessimistic or another overly optimistic in their predictions. But when it comes to evaluation of keypoints accuracy YoloNAS Pose shows better mAP on COCO validation dataset,

**Comment by J0eky** [comment]
> It's hard to confirm or deny your statement by one cherry-picked image. According to your evaluation on COCO dataset, indeed YoloNAS Pose performs better in terms or accuracy and latency than corresponding YoloV8 Pose variants.
> 
> Even the attached screenshots demonstrate this - take a look at the right arm of the lady in front. It may be true that confidence threshold should be tuned, but this is not a signal that one model is better or worse than the other. It may indicate one model is overly pessimistic or another overly optimistic in their predictions. But when it comes to evaluation of keypoints accuracy YoloNAS Pose shows better mAP on COCO validation dataset,

I get it. Thank you for your reply.
