### ISSUE TITLE
How can I use yolo-nas in ROS2

### ISSUE THREAD

**Issue by Harry-maximum** [Deci-AI/super-gradients#1805]
### 💡 Your Question

I ve trained my own yolo-nas-m model, and now I want to move it to 3D by using it in ROS2, I am so confused that there are no tutorials on the web, maybe can I get some instructions....

**Comment by BloodAxe** [comment]
I suggest you to check the documentation on ROS2 in that regard. We provide a mechanism to export a model to ONNX format which you can then take to any platform you like that is capable of running ONNX graphs. Can't provide support on that as it's goes very much beyond expertise. To learn how to export YoloNAS to ONNX please check the tutorials listed in our README.
