### ISSUE TITLE
YOLO NAS DETECTED LABELS

### ISSUE THREAD

**Issue by PEERMOH-tech** [Deci-AI/super-gradients#1811]
### 💡 Your Question

I run the code it is giving labels, conf, bbboxes correctly for single input image but it is not providing that particular detected class label instead it is providing all database labels as an output.

'''class_names = image_prediction.class_names
labels = image_prediction.prediction.labels
confidence = image_prediction.prediction.confidence
bboxes = image_prediction.prediction.bboxes_xyxy'''

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by BloodAxe** [comment]
Getting class names from labels is pretty trivial. Here you can see an example https://github.com/Deci-AI/super-gradients/issues/1818
