### ISSUE TITLE
Can I use  Albumentations  library?

### ISSUE THREAD

**Issue by futurelee2** [Deci-AI/super-gradients#1815]
### 💡 Your Question

Hi 
i have problem for Augmentations
I would like to use 'Albumentations' instead of transforms set by default

default is :
DetectionMosaic
DetectionRandomAffine
DetectionMixup
DetectionHSV
DetectionHorizontalFlip
DetectionPaddedRescale
DetectionTargetsFormatTransform

**How do I modify the code to use this library?**

import albumentations as A

    transforms = A.Compose[
        A.Blur(p=0.01),
        A.MedianBlur(p=0.01),
        A.ToGray(p=0.01),
        A.CLAHE(p=0.01),
        A.RandomBrightnessContrast(p=0.0),
        A.RandomGamma(p=0.0),
        A.ImageCompression(quality_lower=75, p=0.0),
                ])

**Comment by BloodAxe** [comment]
Yes you can. Please check https://github.com/Deci-AI/super-gradients/blob/master/notebooks/albumentations_tutorial.ipynb
