### ISSUE TITLE
Call tensorrt plugin initializer before loading engine inference

### ISSUE THREAD

**Issue by nsabir2011** [Deci-AI/super-gradients#1816]
### 📚 Documentation Improvement

The demonstration on how to convert onnx to tensorrt engine and inference is in [this notebook](https://github.com/Deci-AI/super-gradients/blob/master/notebooks/YoloNAS_Inference_using_TensorRT.ipynb). While building the engine file, tensorrt creates the `EfficientNMS_TRT` plugin and it is not destroyed later on. So the inference work fine when anyone runs the notebook for the first time.

However, when I tried to load the saved engine file again in a new python session (which is the most common use case), it fails with the following errors:
```bash
[02/05/2024-21:55:33] [TRT] [I] Loaded engine size: 17 MiB
[02/05/2024-21:55:33] [TRT] [E] 3: getPluginCreator could not find plugin: EfficientNMS_TRT version: 1
[02/05/2024-21:55:33] [TRT] [E] 1: [pluginV2Runner.cpp::load::303] Error Code 1: Serialization (Serialization assertion creator failed.Cannot deserialize plugin since corresponding IPlugin
```
This issue has already been reported by another person #1814 .

There is a very simple fix for this. Add the following line just before loading the engine:
```python
trt.init_libnvinfer_plugins(trt_logger, "")    # <- this one
with open(engine_file_path, "rb") as f, trt.Runtime(trt_logger) as runtime:
    serialized_engine = f.read()
    engine = runtime.deserialize_cuda_engine(serialized_engine)
    return engine
```
Everything works as expected afterwards. Please add this information in the notebook.

**Comment by BloodAxe** [comment]
Thanks for the solution. We will update the notebook shortly ^_^
