### ISSUE TITLE
Predicted bbox coordinates printing

### ISSUE THREAD

**Issue by rabion1234** [Deci-AI/super-gradients#1833]
### 💡 Your Question

Currently I have trained my yolonas model for predicting classes using custom dataset. it is predicting classes perfectly. in my image now i want to fix my coordinates of bbox and it should be given class(i.e. i have only two class). and image position will be same. so how should i do it?

### Versions

Currently Working on Google Colab

**Comment by BloodAxe** [comment]
I'm not quite getting the question you are trying to ask. You can try reformulating your problem to make it more clear to follow what your intention is. 

But based on the title, this issue (answered) may be what you are looking for: https://github.com/Deci-AI/super-gradients/issues/1818

**Comment by rabion1234** [comment]
hello @BloodAxe ,
i want my class to be in specific labels and if they are in other labels i want to have error showing in prediction.

**Comment by BloodAxe** [comment]
You would have to write your own routine for this task.
1) take ground truth and prediction boxes and compute iou matrix [GT, Pred
2) solve assignment problem my matching predictions to gt (linear_sum_assignment). You would need some iou threshold to consider predicted box to be a "match" for a gt box
3) You now have indexes of matches (gt index, pred index) that you can use to iterate over box annotations and visualize them as you want
4) don't forget to also visualize FN and FP

Good luck with it!

**Comment by rabion1234** [comment]
is this you are telling

import cv2
import numpy as np


def yolo_to_absolute(yolo_box, img_width, img_height):
    x_center, y_center, width, height = yolo_box
    x_min = int((x_center - width / 2) * img_width)
    y_min = int((y_center - height / 2) * img_height)
    x_max = int((x_center + width / 2) * img_width)
    y_max = int((y_center + height / 2) * img_height)
    return [x_min, y_min, x_max, y_max]


def calculate_iou(box1, box2):
    x1 = max(box1[0], box2[0])
    y1 = max(box1[1], box2[1])
    x2 = min(box1[2], box2[2])
    y2 = min(box1[3], box2[3])

    intersection_area = max(0, x2 - x1 + 1) * max(0, y2 - y1 + 1)

    box1_area = (box1[2] - box1[0] + 1) * (box1[3] - box1[1] + 1)
    box2_area = (box2[2] - box2[0] + 1) * (box2[3] - box2[1] + 1)

    iou = intersection_area / float(box1_area + box2_area - intersection_area)

    return iou

# Example ground truth bounding boxes in YOLO format (format: [class_id, x_center, y_center, width, height])
ground_truth_bboxes_yolo = [[0, 0.5, 0.5, 0.2, 0.2],   # Example ground truth bounding box for class 0
                            [1, 0.8, 0.8, 0.2, 0.2]]   # Example ground truth bounding box for class 1

detected_bboxes_yolo = [[0, 0.5, 0.5, 0.25, 0.25],   # Example detected bounding box for class 0
                        [1, 0.7, 0.7, 0.2, 0.2]]   # Example detected bounding box for class 1

img_width = 800
img_height = 600


ground_truth_bboxes = [yolo_to_absolute(bbox, img_width, img_height) for bbox in ground_truth_bboxes_yolo]
detected_bboxes = [yolo_to_absolute(bbox, img_width, img_height) for bbox in detected_bboxes_yolo]

# Load image (optional, just for visualization)
image = cv2.imread("example_image.jpg")

# Draw ground truth bounding boxes
for bbox in ground_truth_bboxes:
    class_id, x_min, y_min, x_max, y_max = bbox
    color = (0, 255, 0) if class_id == 0 else (0, 0, 255)
    cv2.rectangle(image, (x_min, y_min), (x_max, y_max), color, 2)

# Draw detected bounding boxes
for bbox in detected_bboxes:
    class_id, x_min, y_min, x_max, y_max = bbox
    color = (255, 0, 0) if class_id == 0 else (0, 255, 255)
    cv2.rectangle(image, (x_min, y_min), (x_max, y_max), color, 2)

# Calculate IoU for each pair of bounding boxes
for ground_truth_bbox in ground_truth_bboxes:
    for detected_bbox in detected_bboxes:
        if ground_truth_bbox[0] == detected_bbox[0]:  # Check if classes match
            iou = calculate_iou(ground_truth_bbox[1:], detected_bbox[1:])
            print("IoU for class {}: {}".format(ground_truth_bbox[0], iou))

cv2.imshow("Bounding Boxes", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

in what format (i mean pixel or yolo) does code return coordinate from code you tagged me in discussion

**Comment by rabion1234** [comment]
can i just train my model for object to be in that bbox coordinates?
