### ISSUE TITLE
Perform inference on an opencv image loaded from memory

### ISSUE THREAD

**Issue by M3nxudo** [Deci-AI/super-gradients#1834]
### 💡 Your Question

Is it possible to perform inference on an image already in memory (through Opencv videocapture)?
I have tried to do so but get no detections when trying to perform inference in the following way:
1. Defining a class that has the model info and a method for performing the detection and returns the predictions
```
class objectNAS():
    def __init__(self, confThreshold):
        self.conf = confThreshold
        model_name = "yolo_nas_l"
        self.model =  super_gradients.training.models.get(model_name, pretrained_weights="coco").cuda()

    def detect(self,input_image): 
        model_prediction = self.model.predict(input_image, iou=0.5, conf=self.conf)
        prediction = model_prediction.prediction
        print ('Debugging prediction')
        print (prediction.bboxes_xyxy[0])
        return prediction
```
2. I create an object of the aforementioned class and then try to perform inference with it inside of an OpenCV Videocapture loop

```
self.capVideo = cv2.VideoCapture(self.videofile[0])
        count = 0
        while self.capVideo.isOpened():
            ret, image = self.capVideo.read()
            if (ret):
                image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                height, width, channel = image.shape
                step = channel * width
                result = objectNAS.detect(image)
```
In doing so and debugging the code i get an error in the line:
print (prediction.bboxes_xyxy[0]) with the following text:
  File "D:\source\repos\libMuinen_UI\nas_interface.py", line 26, in detect
    print (prediction.bboxes_xyxy[0])
IndexError: index 0 is out of bounds for axis 0 with size 0

Which if I understand correctly means that the prediction results are empty and can't access them but from the input image I know i should be getting at least some detections.
Would love to know if i'm using incorrectly the predict method or any tips to make my code work.

**Comment by BloodAxe** [comment]
The `model_prediction = self.model.predict(input_image, iou=0.5, conf=self.conf)` line looks legit.
You can pass your as RGB (not BGR as OpenCV reads) image as numpy array to predict().
It could be you are simply getting no detections (Maybe your confThreshold is too high?).
So if there are no boxes you would get an index error at `bboxes_xyxy[0]` which is expected.

A somewhat related issue where you can find a code snippet of printing all detections:
https://github.com/Deci-AI/super-gradients/issues/1818

**Comment by M3nxudo** [comment]
I double checked that i'm feeding the correct image type, tested with lower confidence (went from 0.7 down to 0.5), and even switched the loaded model to "yolo_nas_m" to make sure it wasn't the model itself and haven't been able to get any inferences working. I'm checking the size of prediction.bboxes_xyxy before accesing it so the program doesn't crush but every one of those is empty.
So still not sure what i'm doing wrong.
Additionally, checked issue #1818 as you suggested but that is working with image files not from images in memory.

**Comment by BloodAxe** [comment]
I don't see how it can be happening. Please double-check everything on your end. 
If you put this code to Colab with GPU and run you will get predictions as expected.

```
import cv2
import super_gradients

model_name = "yolo_nas_l"
model = super_gradients.training.models.get(model_name, pretrained_weights="coco").cuda()

image = cv2.imread(WHATEVER IMAGE)
image = image[:, :, ::-1]

model.predict(image).show()

```


Please share additional details what GPU you have and OS/python version you are using. If possible, provide a _minimal_ yet _complete_ code that reproduce your issue.

**Comment by BloodAxe** [comment]
Thanks for the detailed snippet to reproduce. Unfortunately I was not able to reproduce the issue yet. On my 4090 it works fine and predictions on CPU & GPU are identical. I will try later on 1070 which I happen to have and will let you know how it goes.

**Comment by BloodAxe** [comment]
Ok, probably this is where it all coming from https://github.com/pytorch/pytorch/issues/58123

**Comment by BloodAxe** [comment]
We have a workaround [PR](https://github.com/Deci-AI/super-gradients/pull/1881) to disable mixed precision used in `model.predict()` which hopefully should fix your issue. This will land in a next release of SG.
But if you are really eager to try it out you can install development version of SG from feature branch using this command:
`pip install -U git+https://github.com/Deci-AI/super-gradients@feature/SG-000-introduce-fp16-flag-to-predict`

**Comment by M3nxudo** [comment]
By changing line 24 of the snippet to:
    resultsgpu = modelgpu.predict(img, fp16=False)
Everything is working as expected now (detections on gpu are finally up and running)
Thanks for the solution, awesome to see the Deci team continuously improving the super-gradients repo.
