### ISSUE TITLE
How to generate a network model using Python code from arch_params instead of using a YAML file.

### ISSUE THREAD

**Issue by ZYX-MLer** [Deci-AI/super-gradients#1857]
### 💡 Your Question

I have designed my own network architecture, hence it not include in models/ALL_ARCHITECTURES and can not using model.get to instance the model.

How can I use Python code to generate the network model from arch_params instead of using a YAML file?

**Comment by shaydeci** [comment]
@ZYX-MLer In case you mean that you wish to train with yaml files using your own custom model you can register it as described [here](https://docs.deci.ai/super-gradients/latest/documentation/source/Recipes_Factories.html#registering-a-class).
You can also simply pass it through the model arg in Trainer.train() if you are using python coded training (i.e like in our example notebooks).
