### ISSUE TITLE
  ERROR: Failed building wheel for pycocotools

### ISSUE THREAD

**Issue by tianw6** [Deci-AI/super-gradients#1891]
### 💡 Your Question

Hi, I'm trying to install super-gradients on Linux ubuntu 20.04 with python 3.8. When I pip install super-gradients, it showed: 
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects. I have no idea how to deal with it. Any help is appreciated.

**Comment by BloodAxe** [comment]
Have you tried searching over issues by "pycocotools" keyword in our repo? Like [this](https://github.com/Deci-AI/super-gradients/issues?q=is%3Aissue+pycocotools) ?

Regardless, in the upcoming 3.6.1 release we will be dropping pycocotools dependency and installation of SG should be more streamlined. Stay tuned for that, it should land in a next few days
