### ISSUE TITLE
import super_gradients error in jupyter notebook while working fine in commmand line

### ISSUE THREAD

**Issue by randubin** [Deci-AI/super-gradients#1902]
### 🐛 Describe the bug

While working on this notebook: https://github.com/Deci-AI/super-gradients/blob/master/notebooks/yolo_nas_custom_dataset_fine_tuning_with_qat.ipynb
simple import super_gradients  gived no moule found.
But when opening the same virtual enviroment and  executing the same import it works.
This sounds similar to this closed case: https://github.com/Deci-AI/super-gradients/issues/1294

### Versions

Collecting environment information...
PyTorch version: 2.2.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.29.0-rc3
Libc version: N/A

Python version: 3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3301
DeviceID=CPU0
Family=107
L2CacheSize=8192
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3301
Name=AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics
ProcessorType=3
Revision=29697

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.15.0
[pip3] onnxsim==0.4.36
[pip3] pytorch-quantization==2.1.2
[pip3] torch==2.2.1
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.17.1
[conda] numpy                     1.23.0                   pypi_0    pypi
[conda] pytorch-quantization      2.1.2                    pypi_0    pypi
[conda] torch                     2.2.1                    pypi_0    pypi
[conda] torchmetrics              0.8.0                    pypi_0    pypi
[conda] torchvision               0.17.1                   pypi_0    pypi

**Comment by BloodAxe** [comment]
Could be ipykernel mismatch.
Make sense to check that first. Please check documentation of Jupyter how to ensure it uses python from correct environment.
