### ISSUE TITLE
Error when trying downgrading super-gradients version

### ISSUE THREAD

**Issue by ikmal-asraf** [Deci-AI/super-gradients#1913]
### 💡 Your Question

Currently using super-gradients version 3.6.1 , successfully installed . Now I want to downgrade to version 3.1.0 or 3.5.0 but getting error . What confuse me is I managed to install latest one , but face problem when use later versions

Python version = 3.8.9 

  Obtaining dependency information for super-gradients==3.1.0 from https://files.pythonhosted.org/packages/ff/08/65c410feaa9dbe47d4cd351d775f0806a2f5ffd005ffc9ce415c68b03e46/super_gradients-3.1.0-py3-none-any.whl.metadata
  Using cached super_gradients-3.1.0-py3-none-any.whl.metadata (36 kB)
Collecting torch<1.14,>=1.9.0 (from super-gradients==3.1.0)
  Obtaining dependency information for torch<1.14,>=1.9.0 from https://files.pythonhosted.org/packages/a6/41/122f37c99422566ea74b9cce90eb9218f5e8fb2582466da220f95842a0a0/torch-1.13.1-cp38-cp38-win_amd64.whl.metadata
  Using cached torch-1.13.1-cp38-cp38-win_amd64.whl.metadata (23 kB)
Requirement already satisfied: tqdm>=4.57.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (4.66.2)
Requirement already satisfied: boto3>=1.17.15 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (1.34.60)
Requirement already satisfied: jsonschema>=3.2.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (4.21.1)
Requirement already satisfied: Deprecated>=1.2.11 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (1.2.14)
Requirement already satisfied: opencv-python>=4.5.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (4.9.0.80)
Requirement already satisfied: scipy>=1.6.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (1.10.1)
Requirement already satisfied: matplotlib>=3.3.4 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (3.7.5)
Requirement already satisfied: psutil>=5.8.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (5.9.8)
Requirement already satisfied: tensorboard>=2.4.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (2.14.0)
Requirement already satisfied: setuptools>=21.0.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (68.2.0)
Requirement already satisfied: coverage~=5.3.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (5.3.1)
Requirement already satisfied: torchvision>=0.10.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (0.17.1)
Requirement already satisfied: sphinx~=4.0.2 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (4.0.3)
Requirement already satisfied: sphinx-rtd-theme in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (1.3.0)
Requirement already satisfied: torchmetrics==0.8 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (0.8.0)
Requirement already satisfied: pillow>=9.2.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (10.2.0)
Requirement already satisfied: hydra-core>=1.2.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (1.3.2)
Requirement already satisfied: omegaconf in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (2.3.0) 
Collecting onnxruntime==1.13.1 (from super-gradients==3.1.0)
  Obtaining dependency information for onnxruntime==1.13.1 from https://files.pythonhosted.org/packages/9f/97/0f45828b2bcd6dc7fa46707c48826ea588b7639f64291e80e491050c0c94/onnxruntime-1.13.1-cp38-cp38-win_amd64.whl.metadata
  Using cached onnxruntime-1.13.1-cp38-cp38-win_amd64.whl.metadata (3.8 kB)
Collecting onnx==1.13.0 (from super-gradients==3.1.0)
  Obtaining dependency information for onnx==1.13.0 from https://files.pythonhosted.org/packages/2c/4a/d46f2e9fab103e59f575590e051bfbf04c2ca52c1bc60b86bad004e2dd9b/onnx-1.13.0-cp38-cp38-win_amd64.whl.metadata
  Using cached onnx-1.13.0-cp38-cp38-win_amd64.whl.metadata (14 kB)
Requirement already satisfied: pip-tools>=6.12.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (7.4.1)
Requirement already satisfied: pyparsing==2.4.5 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (2.4.5)
Requirement already satisfied: einops==0.3.2 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (0.3.2)
Collecting pycocotools==2.0.4 (from super-gradients==3.1.0)
  Using cached pycocotools-2.0.4.tar.gz (106 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: protobuf==3.20.3 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (3.20.3)
Requirement already satisfied: treelib==1.6.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (1.6.1)
Requirement already satisfied: termcolor==1.1.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (1.1.0)
Requirement already satisfied: packaging>=20.4 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (24.0)
Requirement already satisfied: wheel>=0.38.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (0.41.2)
Requirement already satisfied: pygments>=2.7.4 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (2.17.2)
Requirement already satisfied: stringcase>=1.2.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (1.2.0)
Requirement already satisfied: numpy<=1.23 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (1.23.0)
Requirement already satisfied: rapidfuzz in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (3.6.2) 
Requirement already satisfied: json-tricks==3.16.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from super-gradients==3.1.0) (3.16.1)
Collecting onnx-simplifier<1.0,>=0.3.6 (from super-gradients==3.1.0)
  Obtaining dependency information for onnx-simplifier<1.0,>=0.3.6 from https://files.pythonhosted.org/packages/3b/63/496174583084c9227b630ea1fcf044da6abce7657b0d4c767f15cbf8fa85/onnx_simplifier-0.4.36-cp38-cp38-win_amd64.whl.metadata
  Using cached onnx_simplifier-0.4.36-cp38-cp38-win_amd64.whl.metadata (4.4 kB)
Requirement already satisfied: typing-extensions>=3.6.2.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from onnx==1.13.0->super-gradients==3.1.0) (4.10.0)
Requirement already satisfied: coloredlogs in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from onnxruntime==1.13.1->super-gradients==3.1.0) (15.0.1)
Requirement already satisfied: flatbuffers in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from onnxruntime==1.13.1->super-gradients==3.1.0) (24.3.7)
Requirement already satisfied: sympy in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from onnxruntime==1.13.1->super-gradients==3.1.0) (1.12)
Requirement already satisfied: pyDeprecate==0.3.* in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from torchmetrics==0.8->super-gradients==3.1.0) (0.3.2)
Requirement already satisfied: future in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from treelib==1.6.1->super-gradients==3.1.0) (1.0.0)
Requirement already satisfied: botocore<1.35.0,>=1.34.60 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from boto3>=1.17.15->super-gradients==3.1.0) (1.34.60)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from boto3>=1.17.15->super-gradients==3.1.0) (1.0.1)
Requirement already satisfied: s3transfer<0.11.0,>=0.10.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from boto3>=1.17.15->super-gradients==3.1.0) (0.10.0)
Requirement already satisfied: wrapt<2,>=1.10 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from Deprecated>=1.2.11->super-gradients==3.1.0) (1.16.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from hydra-core>=1.2.0->super-gradients==3.1.0) (4.9.3)
Requirement already satisfied: importlib-resources in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from hydra-core>=1.2.0->super-gradients==3.1.0) (6.1.3)
Requirement already satisfied: attrs>=22.2.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from jsonschema>=3.2.0->super-gradients==3.1.0) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from jsonschema>=3.2.0->super-gradients==3.1.0) (2023.12.1)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from jsonschema>=3.2.0->super-gradients==3.1.0) (1.3.10)
Requirement already satisfied: referencing>=0.28.4 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from jsonschema>=3.2.0->super-gradients==3.1.0) (0.33.0)
Requirement already satisfied: rpds-py>=0.7.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from jsonschema>=3.2.0->super-gradients==3.1.0) (0.18.0)
Requirement already satisfied: contourpy>=1.0.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from matplotlib>=3.3.4->super-gradients==3.1.0) (1.1.1)
Requirement already satisfied: cycler>=0.10 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from matplotlib>=3.3.4->super-gradients==3.1.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from matplotlib>=3.3.4->super-gradients==3.1.0) (4.49.0)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from matplotlib>=3.3.4->super-gradients==3.1.0) (1.4.5)
Requirement already satisfied: python-dateutil>=2.7 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from matplotlib>=3.3.4->super-gradients==3.1.0) (2.9.0.post0)
Requirement already satisfied: PyYAML>=5.1.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from omegaconf->super-gradients==3.1.0) (6.0.1)
Requirement already satisfied: rich in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from onnx-simplifier<1.0,>=0.3.6->super-gradients==3.1.0) (13.7.1)
Requirement already satisfied: build>=1.0.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from pip-tools>=6.12.1->super-gradients==3.1.0) (1.1.1)
Requirement already satisfied: click>=8 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from pip-tools>=6.12.1->super-gradients==3.1.0) (8.1.7)
Requirement already satisfied: pip>=22.2 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from pip-tools>=6.12.1->super-gradients==3.1.0) (23.2.1)
Requirement already satisfied: pyproject-hooks in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from pip-tools>=6.12.1->super-gradients==3.1.0) (1.0.0)
Requirement already satisfied: tomli in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from pip-tools>=6.12.1->super-gradients==3.1.0) (2.0.1)
Requirement already satisfied: sphinxcontrib-applehelp in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (1.0.4)
Requirement already satisfied: sphinxcontrib-devhelp in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (1.0.2)
Requirement already satisfied: sphinxcontrib-jsmath in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (2.0.1)
Requirement already satisfied: sphinxcontrib-serializinghtml in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (1.1.5)
Requirement already satisfied: sphinxcontrib-qthelp in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (1.0.3)
Requirement already satisfied: Jinja2>=2.3 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (3.1.3)
Requirement already satisfied: docutils<0.18,>=0.14 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (0.17.1)
Requirement already satisfied: snowballstemmer>=1.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (2.2.0)
Requirement already satisfied: babel>=1.3 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (2.14.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (0.7.13)
Requirement already satisfied: imagesize in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (1.4.1)
Requirement already satisfied: requests>=2.5.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (2.31.0)
Requirement already satisfied: colorama>=0.3.5 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx~=4.0.2->super-gradients==3.1.0) (0.4.6)
Requirement already satisfied: absl-py>=0.4 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from tensorboard>=2.4.1->super-gradients==3.1.0) (2.1.0)
Requirement already satisfied: grpcio>=1.48.2 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from tensorboard>=2.4.1->super-gradients==3.1.0) (1.62.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from tensorboard>=2.4.1->super-gradients==3.1.0) (2.28.2)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from tensorboard>=2.4.1->super-gradients==3.1.0) (1.0.0)
Requirement already satisfied: markdown>=2.6.8 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from tensorboard>=2.4.1->super-gradients==3.1.0) (3.5.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from tensorboard>=2.4.1->super-gradients==3.1.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from tensorboard>=2.4.1->super-gradients==3.1.0) (3.0.1)
INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
Collecting torchvision>=0.10.0 (from super-gradients==3.1.0)
  Obtaining dependency information for torchvision>=0.10.0 from https://files.pythonhosted.org/packages/d2/08/c438a422459d0d8ffd111590c3f49cc8eced15900412cb9449ec13d929be/torchvision-0.17.0-cp38-cp38-win_amd64.whl.metadata
  Using cached torchvision-0.17.0-cp38-cp38-win_amd64.whl.metadata (6.6 kB)
  Obtaining dependency information for torchvision>=0.10.0 from https://files.pythonhosted.org/packages/54/4b/b0861005f5d4370b3529f31d5e6461c4faf9bbbcbe916480cceebc885aa8/torchvision-0.16.2-cp38-cp38-win_amd64.whl.metadata
  Using cached torchvision-0.16.2-cp38-cp38-win_amd64.whl.metadata (6.6 kB)
  Obtaining dependency information for torchvision>=0.10.0 from https://files.pythonhosted.org/packages/fc/27/d16f6210d20c98fbc33809e06340a8fbdc283857be7644772c18242aec14/torchvision-0.16.1-cp38-cp38-win_amd64.whl.metadata
  Using cached torchvision-0.16.1-cp38-cp38-win_amd64.whl.metadata (6.6 kB)
  Obtaining dependency information for torchvision>=0.10.0 from https://files.pythonhosted.org/packages/cc/1b/d781261269b3d0a5da35feda8e0b5ca7d25f5d08945bc6fba809e8cb7cbc/torchvision-0.16.0-cp38-cp38-win_amd64.whl.metadata
  Using cached torchvision-0.16.0-cp38-cp38-win_amd64.whl.metadata (6.6 kB)
  Obtaining dependency information for torchvision>=0.10.0 from https://files.pythonhosted.org/packages/e0/05/8264dffad43c6a785787515db6d9af2ca80ec2d2c16a0be9968f755a3c8b/torchvision-0.15.2-cp38-cp38-win_amd64.whl.metadata
  Using cached torchvision-0.15.2-cp38-cp38-win_amd64.whl.metadata (11 kB)
  Obtaining dependency information for torchvision>=0.10.0 from https://files.pythonhosted.org/packages/0e/2f/bfd590bf3bfd4cb326cdd6bd81600f77e5eaddad718f1dc87e2ca9312582/torchvision-0.15.1-cp38-cp38-win_amd64.whl.metadata
  Using cached torchvision-0.15.1-cp38-cp38-win_amd64.whl.metadata (11 kB)
  Obtaining dependency information for torchvision>=0.10.0 from https://files.pythonhosted.org/packages/3a/e6/b631892eca70acccd4b86b1dcee4fd23347293e6a231de72af3eb464b1a0/torchvision-0.14.1-cp38-cp38-win_amd64.whl.metadata
  Using cached torchvision-0.14.1-cp38-cp38-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sphinx-rtd-theme->super-gradients==3.1.0) (4.1)
Requirement already satisfied: pytz>=2015.7 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from babel>=1.3->sphinx~=4.0.2->super-gradients==3.1.0) (2024.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from botocore<1.35.0,>=1.34.60->boto3>=1.17.15->super-gradients==3.1.0) (1.26.18)
Requirement already satisfied: importlib-metadata>=4.6 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from build>=1.0.0->pip-tools>=6.12.1->super-gradients==3.1.0) (7.0.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->super-gradients==3.1.0) (5.3.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->super-gradients==3.1.0) (0.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->super-gradients==3.1.0) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard>=2.4.1->super-gradients==3.1.0) (1.4.0)
Requirement already satisfied: zipp>=3.1.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from importlib-resources->hydra-core>=1.2.0->super-gradients==3.1.0) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from Jinja2>=2.3->sphinx~=4.0.2->super-gradients==3.1.0) (2.1.5)
Requirement already satisfied: six>=1.5 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.4->super-gradients==3.1.0) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from requests>=2.5.0->sphinx~=4.0.2->super-gradients==3.1.0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from requests>=2.5.0->sphinx~=4.0.2->super-gradients==3.1.0) (3.6)
Requirement already satisfied: certifi>=2017.4.17 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from requests>=2.5.0->sphinx~=4.0.2->super-gradients==3.1.0) (2024.2.2)
Requirement already satisfied: humanfriendly>=9.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from coloredlogs->onnxruntime==1.13.1->super-gradients==3.1.0) (10.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from rich->onnx-simplifier<1.0,>=0.3.6->super-gradients==3.1.0) (3.0.0)
Requirement already satisfied: mpmath>=0.19 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from sympy->onnxruntime==1.13.1->super-gradients==3.1.0) (1.3.0)
Requirement already satisfied: pyreadline3 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime==1.13.1->super-gradients==3.1.0) (3.4.1)
Requirement already satisfied: mdurl~=0.1 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from markdown-it-py>=2.2.0->rich->onnx-simplifier<1.0,>=0.3.6->super-gradients==3.1.0) (0.1.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.4.1->super-gradients==3.1.0) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in e:\fyp_project\drowning2.0\pythonproject1\.venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard>=2.4.1->super-gradients==3.1.0) (3.2.2)
Using cached super_gradients-3.1.0-py3-none-any.whl (965 kB)
Using cached onnx-1.13.0-cp38-cp38-win_amd64.whl (12.2 MB)
Using cached onnxruntime-1.13.1-cp38-cp38-win_amd64.whl (5.9 MB)
Using cached onnx_simplifier-0.4.36-cp38-cp38-win_amd64.whl (1.3 MB)
Using cached torch-1.13.1-cp38-cp38-win_amd64.whl (162.6 MB)
Using cached torchvision-0.14.1-cp38-cp38-win_amd64.whl (1.1 MB)
Building wheels for collected packages: pycocotools
  Building wheel for pycocotools (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycocotools (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\pycocotools
      copying pycocotools\coco.py -> build\lib.win-amd64-cpython-38\pycocotools
      copying pycocotools\cocoeval.py -> build\lib.win-amd64-cpython-38\pycocotools
      copying pycocotools\mask.py -> build\lib.win-amd64-cpython-38\pycocotools
      copying pycocotools\__init__.py -> build\lib.win-amd64-cpython-38\pycocotools
      running build_ext
      Compiling pycocotools/_mask.pyx because it changed.
      [1/1] Cythonizing pycocotools/_mask.pyx
      building 'pycocotools._mask' extension
      C:\Users\User\AppData\Local\Temp\pip-build-env-kmy38l9l\overlay\Lib\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive
 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\User\AppData\Local\Temp\pip-install-n9sy1526\pycocotools_48c02856ea744f0da091a19705728416\pycocotools\_mask.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
Failed to build pycocotools
ERROR: Could not build wheels for pycocotools, which is required to install pyproject.toml-based projects

### Versions

PyTorch version: 2.2.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce MX230
Nvidia driver version: 546.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:

Revision=

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.15.0
[pip3] onnxsim==0.4.36
[pip3] torch==2.2.1
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.17.1
[conda] Could not collect

**Comment by ikmal-asraf** [comment]
PyTorch version: 2.2.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 14:02:34) [MSC v.1928 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce MX230
Nvidia driver version: 546.17
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:










Revision=

Versions of relevant libraries:
[pip3] numpy==1.23.0
[pip3] onnx==1.15.0
[pip3] onnxruntime==1.15.0
[pip3] onnxsim==0.4.36
[pip3] torch==2.2.1
[pip3] torchmetrics==0.8.0
[pip3] torchvision==0.17.1
[conda] Could not collect

**Comment by BloodAxe** [comment]
As the error log suggest - your installation fails since your environment does not have build tools to compile a `pycocotools` package which older SG versions depends on.
And there are two options:
1) Get build tools from the suggestion: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
2) Install pycocotools from conda which usually have prebuild wheels for windows.
