### ISSUE TITLE
Using class specific score threshold given during training for inference

### ISSUE THREAD

**Issue by james-imi** [Deci-AI/super-gradients#1921]
### 💡 Your Question

So when training, YOLO-NAS gives you `Best_score_threshold_<CLASS>`. Is there a way to use this on `predict` function instead of a generic conf?

**Comment by BloodAxe** [comment]
No it's not supported

**Comment by james-imi** [comment]
@BloodAxe I assume that the `best score threshold` during training are the recommended scores during training, isn't it? Would it be better then if we can use that during `predict`? because if we filter predictions right after `predict` we will still need another round of NMS.

**Comment by BloodAxe** [comment]
Now sure I'm following regarding second round of NMS. 

> Would it be better then if we can use that during predict?

IDK. From the standpoint of maximizing F1 score - perhaps yes. Keep in mind - `model.predict` was introduced for a sole purpose to provide quick & simple means to run predictions & get the result for debugging/visualization purposes. It is optimized neither for latency nor for granular control of postprocessing.

But I suggest you to try adding support of confidence threshold as a vector of [N] if you are in need, and who knows - maybe making a PR afterwards.

**Comment by james-imi** [comment]
> . It is optimized neither for latency nor for granular control of postprocessing.

Do you have any function or example for using the outputs from ONNX model without postprocesisng?
