### ISSUE TITLE
How to improve api access speed

### ISSUE THREAD

**Issue by mymuse77** [Deci-AI/super-gradients#1937]
### 💡 Your Question

![image](https://github.com/Deci-AI/super-gradients/assets/128689058/40da5ece-e252-45f2-b8f3-c2dc539bafe7)

I am using Api to call the api exposed by flask, but the response time is not good when calling. How can I fix it, please?
Here is my code

``` python
def predict(filePath,threshold):

    print(filePath)

    dataset_params = {'classes': ['fire']}
    
    best_model = models.get('yolo_nas_m',num_classes=len(dataset_params['classes']),checkpoint_path='yolo_nas_m_model.pth')

    result = best_model.predict(filePath, conf=threshold,fuse_model=False)

    return result

@app.route('/predict_img', methods=['POST'])
def predict_img():
    ...
```

**Comment by 23pointsNorth** [comment]
Load the model on startup (and not in the call for inference).
Or you can use something like Ray Serve - https://docs.ray.io/en/latest/serve/index.html

**Comment by BloodAxe** [comment]
As @23pointsNorth suggested you definitely want to load a model once at startup. 
Additionally you may benefit from storing inference pipeline instance result `pipeline = model._get_pipeline(...)` and using `pipeline(image)` to get predictions from an image.

But please read this post on reddit on why you shouldn't be using `model.predict` for production use:
https://www.reddit.com/r/computervision/comments/1bp96ng/comment/kwxdbk8/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by mymuse77** [comment]
@23pointsNorth @BloodAxe tks，Already following the prompts
