### ISSUE TITLE
yolo-nas performace

### ISSUE THREAD

**Issue by achen1959** [Deci-AI/super-gradients#1939]
### 💡 Your Question

Dear HARPREET SAHOTA
          I have been using yolov5 and yolov8. I installed yolo-nas and trained the model on our customer data. Because they use different metric I can’t compare them. But yolo-nas model perform poorly on our customer data by yolov5 and yolov8 standard. I train yolov5 model with epoch=120. yolo-nas model with epoch=40. Do you have an idea about it? I expect 1) The new YOLO-NAS delivers state-of-the-art (SOTA) performance with the unparalleled accuracy-speed performance, outperforming other models such as YOLOv5, YOLOv6, YOLOv7 and YOLOv8. 2) In terms of pure numbers, YOLO-NAS is ~0.5 mAP point more accurate and 10-20% faster than equivalent variants of YOLOv8 and YOLOv7.
Thanks

### Versions

super-gradients=3.1.3

**Comment by BloodAxe** [comment]
It would be great to see some numbers of those trained models.

But from top of my head:

1) try with latest SG release. 3.1.3 is pretty old and there were number of bug fixes / improvements 

2) double check that datasets you are using for training YoloNAS and yolov5 are actually identical and if you are using custom metric - that implementation are identical

**Comment by achen1959** [comment]
both yoloNAS model and yolov5 model are use same datasets for training.  I run both yoloNAS model and yolov5 model  on same test dataset.

**Comment by achen1959** [comment]
Here is yolo-nas model's result
NumBags: 211
NumThreatBags: 211
NumCleanBags: 0
NumDetectedThreatBags: 145
NumAlarmingCleanBags: 0
NumThreatObjects: 211
NumDetectedThreatObjects: 145
NumAlarmingFAObjects: 0
NumAlarms: 366
Bag PD: 0.687204
Bag PFA: 0
Here is yolov5 model's result
NumBags: 211
NumThreatBags: 211
NumCleanBags: 0
NumDetectedThreatBags: 185
NumAlarmingCleanBags: 0
NumThreatObjects: 211
NumDetectedThreatObjects: 185
NumAlarmingFAObjects: 0
NumAlarms: 428
Bag PD: 0.876777
Bag PFA: 0

**Comment by BloodAxe** [comment]
Would be great to understand what these numbers indicate. I imagine there are TP per each class.
However you should also look and compare number of FN/FNs for each model and tune the confidence threshold if necessary. In other works, without seeing precision/recall rates it is simply incorrect to claim some model is better that the other.
