### ISSUE TITLE
How to set the lr_warmup_epochs to be greater than 10 ?

### ISSUE THREAD

**Issue by AlfredQin** [Deci-AI/super-gradients#1961]
### 💡 Your Question

Setting the lr_warmup_epochs > 10 will raise an error since the predefined content in TRAINING_PARAM_SCHEMA is : `"lr_warmup_epochs": {"type": "number", "minimum": 0, "maximum": 10}`.  Could you please help tell me how to fix it if I want to use lr_warmup_epochs greater than 10 ? Thank you !

**Comment by ofrimasad** [comment]
Hi @AlfredQin .
This setting was designed to prevent mistakes. More than 10 warmup epochs are very untraditional. 
With that said, if you are using SG by cloning the SG repo, you can simply go to `src/super_gradients/training/params.py (line 130)` and change that setting.

If you are using SG as an installed library, you can work around this by changing the schema before loading any hyper params. 

``` Python
import super_gradients
from super_gradients.training.params import TRAINING_PARAM_SCHEMA
super_gradients.training.params.TRAINING_PARAM_SCHEMA = {}

# The rest of your code
```
Not that this will disable all other training parameters validations. You can also set  TRAINING_PARAM_SCHEMA to the original dictionary with only the required modifications

``` Python
import super_gradients
from super_gradients.training.params import TRAINING_PARAM_SCHEMA
super_gradients.training.params.TRAINING_PARAM_SCHEMA = {
    "type": "object",
    "properties": {
        "max_epochs": {"type": "number", "minimum": 1},
        # FIXME: CHECK THE IMPORTANCE OF THE COMMENTED SCHEMA- AS IT CAUSES HYDRA USE TO CRASH
        # "lr_updates": {"type": "array", "minItems": 1},
        "lr_decay_factor": {"type": "number", "minimum": 0, "maximum": 1},
        "lr_warmup_epochs": {"type": "number", "minimum": 0, "maximum": 100},
        "initial_lr": {
            "anyOf": [
                {"type": ["number", "string", "boolean", "null"]},
                {"type": "object", "patternProperties": {"^[a-zA-Z0-9_.]+$": {"type": "number"}}, "additionalProperties": False},
            ]
        },
    },
    "if": {"properties": {"lr_mode": {"const": "StepLRScheduler"}}},
    "then": {"required": ["lr_updates", "lr_decay_factor"]},
    "required": ["max_epochs", "lr_mode", "initial_lr", "loss"],
}

# The rest of your code
```

Hope that helps

**Comment by AlfredQin** [comment]
Thank you very much @ofrimasad , it is now working well by using your provided methods.
