### ISSUE TITLE
Change Quantization Precision

### ISSUE THREAD

**Issue by Halafz7** [Deci-AI/super-gradients#1991]
### 💡 Your Question

Dear Author @BloodAxe 

So I've read the PTQ and QAT for Classification README and I found about QuantDescriptor
![image](https://github.com/Deci-AI/super-gradients/assets/79700580/071674fb-4602-49d3-a302-7b2f4f57bf9a)

I want to use PTQ_and_QAT_for_classification.ipynb file to produce vary quantized model with custom precision (4-bit, 8-bit, 16-bit). On what file I should declare the num_bits of QuantDescriptor's args so I can produce the quantized model?

Thank you

**Comment by BloodAxe** [comment]
At this moment, changing precision is not supported and is not anywhere on the roadmap.
