### ISSUE TITLE
Advanced training recipes for ddrnet

### ISSUE THREAD

**Issue by ydhongHIT** [Deci-AI/super-gradients#202]
Thanks for your great works. Do you have the plan to apply more advanced training recipes for ddrnet_23_slim and ddrnet_23? The paddleseg version ddrnet_23 has achieved 79.85%mIoU.

**Comment by oferbaratz** [comment]
Hi Yuanduo,
In the next few days, we will upload new recipes and checkpoints for ddrnet_23 and ddrnet_23_slim with higher mIoU and better runtime performance.
we received on cityscapes these results
ddrnet23: 79.7%
ddrnet23slim: 77.99%

**Comment by ydhongHIT** [comment]
> Hi Yuanduo, In the next few days, we will upload new recipes and checkpoints for ddrnet_23 and ddrnet_23_slim with higher mIoU and better runtime performance. we received on cityscapes these results ddrnet23: 79.7% ddrnet23slim: 77.99%

Thanks for your great work and efforts. Look forward to the new model and hope it can help semantic segmentation in self-driving.
