### ISSUE TITLE
Path for test is no longer valid and returns a 404 for yolo_nas_s

### ISSUE THREAD

**Issue by The1Percent** [Deci-AI/super-gradients#2058]
https://github.com/Deci-AI/super-gradients/blame/e0ccacf8868ffa1296fa4f8407c03d2bc227312c/tests/unit_tests/load_checkpoint_test.py#L35

The actual model file listed is correct but notebooks are failing from this test which references the old site for the pth file.

**Comment by BloodAxe** [comment]
Yes old S3 bucket was taken down.
For not the workaround is to pip install from the master:

```
pip install -U git+https://github.com/Deci-AI/super-gradients@e0ccacf8868ffa1296fa4f8407c03d2bc227312c
```

Sorry for the inconvenience.
