### ISSUE TITLE
Add a `conda` install option for `super-gradients`

### ISSUE THREAD

**Issue by sugatoray** [Deci-AI/super-gradients#329]
It will be helpful to have `super-gradients` added to conda-forge channel. I have started the work already in the following PR.

- https://github.com/conda-forge/staged-recipes/pull/20167

But there seems to be a problem with one of its dependencies:

- `deci-lab-client` [PyPI](https://pypi.org/project/deci-lab-client)

  > Neither does it have any source file (`*.tar.gz`) on PyPI, nor any release on a public GitHub repository.

Please provide (preferably) the source file for `deci-lab-client` on PyPI.

:fire: `CONSTRAINT`: **To add any package on conda-forge channel, you need ALL its dependencies on conda-forge as well**

**Comment by sugatoray** [comment]
cc: @shaydeci @oferbaratz

**Comment by shaydeci** [comment]
@sugatoray Looking into it, and will get back to you ASAP.

**Comment by sugatoray** [comment]
Any updates?

**Comment by sugatoray** [comment]
Thank you for the update.

**Comment by shaydeci** [comment]
@sugatoray deci-lab-client is no longer a requirement. Closing this issue down.

**Comment by sugatoray** [comment]
@shaydeci  Thank you for the update.

**Comment by andrewvarga** [comment]
Sorry if this is a newbie question. I'm getting this error when trying to install supergradients on a mac (m2):
```
PackagesNotFoundError: The following packages are not available from current channels:

  - supergradients

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
```

I'm doing `conda install supergradients` in a virtual env, I've added the `conda-forge` channel.

Do you have some ideas what I'm doing wrong?
