### ISSUE TITLE
CoCoSegmentationDataSet._generate_samples_and_targets() doesn't call super (= no caching)

### ISSUE THREAD

**Issue by michaelitvin** [Deci-AI/super-gradients#351]
### Describe the bug
`CoCoSegmentationDataSet._generate_samples_and_targets()` doesn't call the corresponding parent class method, and therefore image and label caching is doesn't work for this class.
The solution is to add `super()._generate_samples_and_targets()` as the last line in `CoCoSegmentationDataSet._generate_samples_and_targets()`.
Excuse me for not making this as a pull request this time.

**Comment by shaydeci** [comment]
@michaellitvin I will merge a fix and release a version soon, thanks !

**Comment by shaydeci** [comment]
Fixed in latest release (3.0.0)
