### ISSUE TITLE
assert self.lr_schedule_function is callable called before its initialization

### ISSUE THREAD

**Issue by pasqualedem** [Deci-AI/super-gradients#674]
As can be seen in the following link, the assert is called before the initialization causing an AttributeError

https://github.com/Deci-AI/super-gradients/blob/21fa8ae8f03d9410730ade40aecea32e4bd442ad/src/super_gradients/training/utils/callbacks/callbacks.py#L475

**Comment by shaydeci** [comment]
Thank you for opening up this issue (:
Fix has been merged and will be available in the upcoming 3.0.7 release.
Note that this class is deprecated, and will be removed in 4.0.0 (an alternative will be supplied of course).
