### ISSUE TITLE
Kernel Dead Issue

### ISSUE THREAD

**Issue by sivaji123256** [Deci-AI/super-gradients#891]
Hi @BloodAxe @ofrimasad @jonathan-sha @spsancti @yurkovak ,
Thanks for the cool work. I was trying with the quick notebook on 5 min video.But the kernel was dead issue was rising.I couldn't run the inference. Any idea on why is happening ?

**Comment by BloodAxe** [comment]
My guess that it is OOM error. In theory if the video has high resolution frames that we accumulate during processing may sum up and take all system memory. Do you mind sharing a video (or at least it's dimensions) you're trying to process?

**Comment by Lifeguard-alex** [comment]
i get the same problem on 
yolo_nas_l.to(device).predict(input_video_path).save(output_video_path)
memory get all 125gb i have and crash + 2 gb of swap

i get this working ok on the same video on yolo 7 and 8 and yolox

i am infer on yolo_nas_l

**Comment by Louis-Dupont** [comment]
Hi @sivaji123256 and @Lifeguard-alex ,
Please check out https://github.com/Deci-AI/super-gradients/issues/976, does this solve your issue ?

**Comment by BloodAxe** [comment]
We have implemented memory-efficient predict for video in super-gradients 3.5.0.
So you are welcome to upgrade to a new version of SG which should not have this issue.
