### ISSUE TITLE
Bug in super-gradients in Linux ubuntu and google colab

### ISSUE THREAD

**Issue by Thecoder1012** [Deci-AI/super-gradients#895]
You'll use yolo_nas_l throughout this notebook. Because you should always go big, or go home.

It's a good life philosophy.

But your fine tuning notebook seems to be not working, I tried to rerun your notebook and in the second cell it is showing me error.
Here is a screenshot of error.
![Screenshot from 2023-05-04 11-02-37](https://user-images.githubusercontent.com/47769368/236119593-080bc60a-eee3-4132-978f-add3f1d452a9.png)

Also following your code into linux env I am facing certain errors while installing super-gradients.

Building wheels for collected packages: pycocotools, stringcase, termcolor, treelib, antlr4-python3-runtime, future
  Building wheel for pycocotools (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/soumyadeep/mmaction_custom/ava_custom_v2/Yolo_train/YOLO-NAS/yolonas_env/bin/python3 /tmp/tmpxprr4m03 build_wheel /tmp/tmp5_axaif9
       cwd: /tmp/pip-install-n3xzz9vp/pycocotools
  Complete output (67 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-38
  creating build/lib.linux-x86_64-cpython-38/pycocotools
  copying pycocotools/__init__.py -> build/lib.linux-x86_64-cpython-38/pycocotools
  copying pycocotools/mask.py -> build/lib.linux-x86_64-cpython-38/pycocotools
  copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-cpython-38/pycocotools
  copying pycocotools/coco.py -> build/lib.linux-x86_64-cpython-38/pycocotools
  running build_ext
  skipping 'pycocotools/_mask.c' 

and more.

Is there any soluiton into it?

**Comment by shaydeci** [comment]
Hey @Thecoder1012,

Regarding the first problem- it is a known issue with PIL and colan, we state inside the notebooks top cell to restart runtime and run the cells again:

🚨 Note: after installation is complete (it make take a few minutes), you'll need to restart the runtime after installation completes.
This is a known [issue](https://github.com/obss/sahi/discussions/781) that is on our roadmap.

Regarding the second issue, can you provide additional details about your environment? installed packages etc.
See our issue template.

**Comment by BloodAxe** [comment]
Fixed in https://github.com/Deci-AI/super-gradients/pull/908 and will be available in next release
