### ISSUE TITLE
Error in building wheels

### ISSUE THREAD

**Issue by soumyadbanik** [Deci-AI/super-gradients#898]
Getting errors while building wheels for collected packages: 

`> treelib, stringcase, pycocotools, termcolor, future, antlr4-python3-runtime`.

I think, `setup.py` needs to be revised.

Tried with `pip install super-gradients` and `pip install git+https://github.com/Deci-AI/super-gradients.git@stable` both

![image](https://user-images.githubusercontent.com/46336023/236133453-8d9ef8ea-a073-46d3-aeb0-ec6c4ac64267.png)

**Comment by ofrimasad** [comment]
Hi @soumyadbanik .

Can you provide some environment details? 
OS, Conda (?), python version, installed packages

Thanks

**Comment by soumyadbanik** [comment]
> Hi @soumyadbanik .
> 
> Does this happen on building wheels or on `pip install super-gradients` ? Can you provide some environment details? OS, Conda (?), python version, installed packages
> 
> Thanks

Hi @ofrimasad,
I created a python environment and did `pip install super-gradients`. Then only it was coming.


OS--
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
-----------------
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          On   | 00000000:01:01.0 Off |                    0 |
|  0%   29C    P8    31W / 300W |   1490MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A40          On   | 00000000:01:02.0 Off |                    0 |
|  0%   28C    P8    30W / 300W |      2MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      6091      C   python3                          1488MiB |
+-----------------------------------------------------------------------------+

Python 3.8.10

Package       Version
------------- -------
pip           20.0.2 
pkg-resources 0.0.0  
setuptools    44.0.0

**Comment by spsancti** [comment]
Try to `pip install wheel` in this environment before installing SuperGradients, looks like it's lacking there

**Comment by soumyadbanik** [comment]
> 

I actually created a conda env and installed super-gradients. It installed successfully.
