### ISSUE TITLE
How can i see the prediction result of a frame/image as bbox coordinates ?

### ISSUE THREAD

**Issue by ngocnd2402** [Deci-AI/super-gradients#907]
I want to combine yolo-nas with deepsort for object tracking problem, so I need to get the bbox of each object.

**Comment by Louis-Dupont** [comment]
[Tutorial](https://docs.deci.ai/super-gradients/documentation/source/ModelPredictions.html) was released with answers to the questions mentioned in this issue, so I'm closing it :)
