### ISSUE TITLE
Integrating custom models into backbone

### ISSUE THREAD

**Issue by mustafaAlgun** [Deci-AI/super-gradients#910]
Hello there!

I loved your work, keep it up!

I'd like to integrate a custom attention model as backbone model for an object detection task and test it out. Is there any documentation or tutorial that you can provide so that I can follow? Or any help would be appreciated!

**Comment by shaydeci** [comment]
Hey @mustafaAlgun,

We have yet to add a tutorial on customizing the YoloNAS backbone. We do plan on making customiaztion easier though.
In the meanwhile, you can check our [CustomizableDetector](https://docs.deci.ai/super-gradients/docstring/training/models.html#training.models.detection_models.customizable_detector.CustomizableDetector class docs] which is the parent class for YoloNAS to see how you can adapt your backbone code so it would fit there.
I am here to help if any question arises (:
