### ISSUE TITLE
python TFlite or onnx inference script

### ISSUE THREAD

**Issue by ajithvallabai** [Deci-AI/super-gradients#911]
### Is your feature request related to a problem? 
No. i am able to convert .pth to tflite models i need a starter script which can be used for tflite inference

### Describe the solution you'd like
A standalone python inference script 

### Describe alternatives you've considered
if you have onnx inference script also it would be helpful

**Comment by avideci** [comment]
Hi @ajithvallabai,
Infery - Deci's runtime inference engine for Python - is capable of performing inference using few lines of code, in any framework.

The official examples are at https://github.com/Deci-AI/infery-examples.

Your can find the TFlite example here: <a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_tflite.py">
    <img src="https://img.shields.io/badge/-TFLite-blue">
</a>

### Basic Examples (Copy-Paste scripts)

<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_tensorrt.py">
    <img src="https://img.shields.io/badge/-TensorRT-blue">
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_onnx.py">
    <img   src="https://img.shields.io/badge/-ONNX-blue">
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_tensorflow.py">
    <img src="https://img.shields.io/badge/-TensorFlow-blue">
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_openvino.py">
    <img src="https://img.shields.io/badge/-OpenVino-blue"> 
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_torch.py">
    <img src="https://img.shields.io/badge/-PyTorch-blue">
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_tflite.py">
    <img src="https://img.shields.io/badge/-TFLite-blue">
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_coreml.py">
    <img src="https://img.shields.io/badge/-CoreML-blue">
</a>

### Advanced Examples
<a href="https://github.com/Deci-AI/infery-examples/blob/master/advanced/concurrent_inference_trt.ipynb">
<img src="https://img.shields.io/badge/TensorRT-Async Inference-teal"> 
</a>

<a href="https://github.com/Deci-AI/infery-examples/blob/master/advanced/tensorrt_layers_profiling.py">
<img src="https://img.shields.io/badge/TensorRT-Layers Profiling-teal"> 
</a>

<a href="https://github.com/Deci-AI/infery-examples/blob/master/advanced/onnx_layers_profiling.py">
<img src="https://img.shields.io/badge/ONNX-Layers Profiling-teal"> 
</a>

<a href="https://github.com/Deci-AI/infery-examples/blob/master/advanced/model_inspection.ipynb">
<img src="https://img.shields.io/badge/TRT+ONNX-Model Inspection-teal"> 
</a>

<a href="https://github.com/Deci-AI/infery-examples/blob/master/advanced/async_gpu_output.py">
<img src="https://img.shields.io/badge/TensorRT-Async GPU Output-teal"> 
</a>

### Application Examples
<a href="https://colab.research.google.com/github/Deci-AI/infery-examples/blob/master/task_specific_notebooks/nlp/bert_sentiment_analysis.ipynb">
    <img src="https://img.shields.io/badge/BERT-Sentiment Analysis-orange">
</a>
<a href="https://colab.research.google.com/github/Deci-AI/infery-examples/blob/master/task_specific_notebooks/vision/classification/resnet_classification.ipynb">
    <img src="https://img.shields.io/badge/ResNet50-Imagenet Classification-orange">
</a>
<a href="https://colab.research.google.com/github/Deci-AI/infery-examples/blob/master/task_specific_notebooks/vision/detection/yolox_detection.ipynb">
    <img src="https://img.shields.io/badge/YOLOX-COCO Object Detection-orange">
</a>


### Custom Hardware Examples
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_tensorrt.py">
<img src="https://img.shields.io/badge/Jetson-Orin AGX-green">
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_tensorrt.py">
<img src="https://img.shields.io/badge/Jetson-Xavier AGX-green">
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_tensorrt.py">
<img src="https://img.shields.io/badge/Jetson-Nano-green">
</a>
<br>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_tensorrt.py">
<img src="https://img.shields.io/badge/Nvidia-T4-green">
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_tensorrt.py">
<img src="https://img.shields.io/badge/Nvidia-V100-green">
</a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_openvino.py"><img src="https://img.shields.io/badge/Intel-CPU-teal"></a>
<a href="https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_coreml.py">
    <img src="https://img.shields.io/badge/Apple-CoreML-blue">
</a>

**Comment by ajithvallabai** [comment]
hi @avideci ,
Thanks for the suggestion i was able get predictions using infery(), could you give me any reference for postprocessing step for below script. I know that i can use `model.predict()` and get the output bboxes etc.. but i want to go by this method because i need to write postprocessing for tflite, onnx model 
While using below method i get raw_predictions[0][0] and raw_predictions[0][1] of shapes (1,8400,4),(1,8400,80) how to do postprocessing for this ? should i use `YoloPostPredictionCallback()` if so how to use it for below case i am getting
```
import requests
from PIL import Image
from io import BytesIO
import numpy as np

# Get PIL image
image = Image.open("./img.jpg")

import torchvision.transforms as transforms
import torch

preprocess = transforms.Compose([
    transforms.Resize([640, 640]),
    transforms.PILToTensor()
])

# Run preprocess on image. unsqueeze for [Batch x Channels x Width x Height] format
transformed_image = preprocess(image).float().unsqueeze(0)
# print(transformed_image)
transformed_image

from super_gradients.training import models
from super_gradients.common.object_names import Models

# Get pretrained model from super-gradients repository.
model = models.get(Models.YOLO_NAS_S, pretrained_weights="coco", num_classes=80)

model.eval()

# Predict using SG model
with torch.no_grad():
  raw_predictions = model(transformed_image)

print(raw_predictions[0][0].shape)
print(raw_predictions[0][1].shape)
print(raw_predictions)


from super_gradients.training.models.detection_models.yolo_base import YoloPostPredictionCallback
predictions = YoloPostPredictionCallback(conf=0.1, iou=0.4)(raw_predictions)[0].numpy()
```

error:
```
File "~/yolo_pretrained_model_predict.py", line 40, in <module>
    predictions = YoloPostPredictionCallback(conf=0.1, iou=0.4)(raw_predictions)[0].numpy()
  File "/home/mcw/anaconda3/envs/yolo_nas/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/site-packages/super_gradients/training/models/detection_models/yolo_base.py", line 96, in forward
    nms_result = non_max_suppression(x[0], conf_thres=self.conf, iou_thres=self.iou, with_confidence=self.with_confidence)
  File "~/site-packages/super_gradients/training/utils/detection_utils.py", line 249, in non_max_suppression
    candidates_above_thres = prediction[..., 4] > conf_thres  # filter by confidence
TypeError: tuple indices must be integers or slices, not tuple
```

**Comment by NatanBagrov** [comment]
Hi, @ajithvallabai ,

I'll first elaborate on the shapes you get, then discuss on how to run e2e procedure.
Given 2 tensors of shapes `(1, 8400, 4), (1, 8400, 80)`, these tensors correspond to the box coords (4), and classes probability (80 classes).
The number 8400, is actually a sum of 3 different grid resolutions (640/8, 640/16, 640/32), where each grid gives a prediction, that is: `640/8 ^ 2 + 640/16 ^ 2 + 640/32 ^ 2 = 8400`. Hope that makes sense.

The suggested way to do end-to-end predictions is by using: `model.predict(...)` method. Please read more [in the quickstart](https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/YoloNASQuickstart.md#predict).


Let me know if that helps!

**Comment by ajithvallabai** [comment]
thanks for the explanation

**Comment by mazatov** [comment]
@ajithvallabai , @NatanBagrov , I was following the colab notebook provided and ran into the same error in the last cell. 

https://colab.research.google.com/drive/1y3WizmNlta6J6BWm46ZfFw1fqpFBSyYM?usp=sharing#scrollTo=Bgn2r7ycaIML

Is `YoloPostPredictionCallback` not to be used anymore?
