### ISSUE TITLE
Select which gpu to train on

### ISSUE THREAD

**Issue by eroshacinas** [Deci-AI/super-gradients#913]
### Is your feature request related to a problem? Please describe.
I am trying to train yolo-nas in an environment with multiple gpus (device=0 and 1), but I only want to use 1. Is there a way to train the model specifically in the 2nd gpu (device=1)

### Describe the solution you'd like
Train the model by only using the 2nd gpu

### Describe alternatives you've considered
Nothing really.

**Comment by BloodAxe** [comment]
`export CUDA_VISIBLE_DEVICES=0 python -m super_gradients.train_from_recipe ...`

**Comment by BloodAxe** [comment]
You can always pass target device to instance of Trainer manually if you want:
`trainer = Trainer(..., device = "cuda:1")`

**Comment by Louis-Dupont** [comment]
You can set it with env variables at the beginning of your script
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = "0,3,4,5"

... # Script you are using 
```

**Comment by Louis-Dupont** [comment]
> Already tried, but it's giving me a `KeyError: "Trainer does not accept anymore 'device' and 'multi_gpu' as argument. Both should instead be passed to super_gradients.setup_device(device=..., multi_gpu=..., num_gpus=...)"`

`Trainer(device=...)` is legacy and will soon be removed from SG.

The same can be done with
```python
from super_gradients.training.utils.distributed_training_utils import setup_device

setup_device(device=...)
```

But this is only useful if you want to train on cpu, or with multiple gpus (DP/DDP). The default behavior is single GPU so you don't need to call it in your case
