### ISSUE TITLE
Need a inference code for yolo-nas , so that i can get output in x1,y1,x2,y2 in terms of bounding box , along with the conf 

### ISSUE THREAD

**Issue by abhinavisgood** [Deci-AI/super-gradients#914]
I'm using Opencv , and i need to be able to put my image frame from the opencv which ofcourse is in numpy.

But the abstracted code you provide don't seem to give an option to get output in the form of x's and y's and conf score ,

Or it might be hiden in some different Class hiearchy , i'm not sure , cause i could not find it . would be very helpful if you could 
 
help with it .

Arigato

**Comment by Louis-Dupont** [comment]
Hi @abhinavisgood, it sounds similar to [this issue](https://github.com/Deci-AI/super-gradients/issues/907), am I right? 

Feel free if you have more questions :)

**Comment by ranrubin** [comment]
duplicated #907
