### ISSUE TITLE
PIP package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by ganymedenet** [Deci-AI/super-gradients#919]
Hey,

I have some conflicts during `pip install`

![image](https://user-images.githubusercontent.com/51125243/236326930-1ebcdd92-9e7f-4507-9f42-c6eeeb2ff116.png)

My requirements.txt
```
aiohttp
sqlalchemy
pandas
aiosqlite
matplotlib
super_gradients
```

**Comment by lucasjinreal** [comment]
I would suggest remove forcely torch requirements when install, let users to define which version they want use, in 2023, mostly users are using torch2.0 (which is also stable for now).
You should eventually and actually ASAP upgrade to torcrh2.0 rather than forcely less than 1.14

**Comment by BloodAxe** [comment]
I agree, that's quite restricting. Hopefully that would be resolved in a next feature update.

**Comment by BloodAxe** [comment]
This is fixed in master branch already and will be available in the next version release
https://github.com/Deci-AI/super-gradients/pull/944
https://github.com/Deci-AI/super-gradients/pull/908
