### ISSUE TITLE
How can I enable multigpu training

### ISSUE THREAD

**Issue by Nuwan1654** [Deci-AI/super-gradients#921]

**Comment by BloodAxe** [comment]
You can either edit recipe YAML to use multi GPU:
https://github.com/Deci-AI/super-gradients/src/super_gradients/recipes/roboflow_yolo_nas_m.yaml
```
multi_gpu: DDP
num_gpus: 8
```

Or pass them via command line:
```
python -m super_gradients.train_from_recipe --config-name=roboflow_yolo_nas_m dataset_name=digits-t2eg6 multi_gpu=DDP num_gpus=8
```

**Comment by Nuwan1654** [comment]
are there any recipes for yolo nas large model
