### ISSUE TITLE
issue with train 

### ISSUE THREAD

**Issue by sachinbisht1** [Deci-AI/super-gradients#931]
So, I created a train to train the model but it is not working
![Screenshot 2023-05-05 190200](https://user-images.githubusercontent.com/88220453/236471351-4dcb7f93-60f2-4634-940b-dfb4c41f54da.jpg)
I am getting an error 
![Screenshot 2023-05-05 190221](https://user-images.githubusercontent.com/88220453/236471458-162dd451-0709-4203-91c7-e1042dcc1ad8.jpg)
if I am trying to solve this issue I am getting another issue 
![Screenshot 2023-05-05 190232](https://user-images.githubusercontent.com/88220453/236471564-984db684-3b99-4fa4-838c-2222621a9f2f.jpg)

**Comment by Louis-Dupont** [comment]
That's weird, what SG version are you using?
Also, can you try to import high-level modules (line 2 and 6) first?

If this doesn't solve it, could you please provide the code snippet (not picture) to allow me to test it?

**Comment by Louis-Dupont** [comment]
@sachinbisht1 did you fix it ?

**Comment by sachinbisht1** [comment]
> @sachinbisht1 did you fix it ?

yes it is resolved
