### ISSUE TITLE
How to reduce the number of layers of yolo small model

### ISSUE THREAD

**Issue by ajithkumarmcw** [Deci-AI/super-gradients#932]
I want to make a light version of yolo-nas less than yolo small model . In YoloV8 we can change the depth, width parameter in yolov8.yaml file , similarly could i adjust hidden_channels and width_mult in [this file](https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/recipes/arch_params/yolo_nas_s_arch_params.yaml) to achieve it. 

Also another question is [this file](https://github.com/Deci-AI/super-gradients/blob/master/src/super_gradients/recipes/arch_params/yolo_arch_params.yaml) base for only Yolov1 to Yolov8 only or else is it base for yolo-nas also

**Comment by NatanBagrov** [comment]
Hello, please refer to 3 files [here](https://github.com/Deci-AI/super-gradients/tree/master/src/super_gradients/recipes/arch_params): `yolo_nas_{s,m,l}_arch_params.yaml`.
There are many parameters there, together with `depth_mult`, and `width_mult`.
