### ISSUE TITLE
PP_LITE_T_SEG inference

### ISSUE THREAD

**Issue by MaxEAB** [Deci-AI/super-gradients#936]
Hi, I was trying to test the semantic segmentation performance using this model:

`model = models.get(Models.PP_LITE_T_SEG50, pretrained_weights="cityscapes")
`

This loads fine, but the following fails with a numpy error:

```
# Run pre-proccess - transforms to tensor and apply normalizations.
img = pre_proccess(img).unsqueeze(0).cuda()

# Run inference
model = model.eval()
mask = model(img)
```

Does anyone have any pointers?

**Comment by Louis-Dupont** [comment]
Hi @MaxEAB, 
If your tensor is converted to torch I don't really see why it would raise a numpy error.
Could you please provide the full traceback and full code snippet to reproduce?

**Comment by MaxEAB** [comment]
Hi, thanks for the reply. Here is the full code snippet:

```
import super_gradients
import os
from super_gradients.common.object_names import Models
from torchvision.transforms import Compose, ToTensor, Resize, Normalize, ToPILImage
from PIL import Image
import torch

os.chdir("D:\Segment")
os.getcwd()

model = models.get(Models.PP_LITE_T_SEG50, pretrained_weights="cityscapes")

pre_proccess = Compose([
    ToTensor(),
    Normalize([.485, .456, .406], [.229, .224, .225])
])

demo_img_path = "kr-seoul_canal_1000x667.jpg"
img = Image.open(demo_img_path)
# Resize the image and display
img = Resize(size=(480, 320))(img)
display(img)

# Run pre-proccess - transforms to tensor and apply normalizations.
img = pre_proccess(img).unsqueeze(0).cuda()

# Run inference
model = model.eval()
mask = model(img)
```

Traceback:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
**Input In [9], in <cell line: 26>()**
     23 display(img)
     25 # Run pre-proccess - transforms to tensor and apply normalizations.
**---> 26 img = pre_proccess(img).unsqueeze(0).cuda()**
     28 # Run inference
     29 model = model.eval()

File C:\Program Files\Python310\lib\site-packages\torchvision\transforms\transforms.py:95, in Compose.__call__(self, img)
     93 def __call__(self, img):
     94     for t in self.transforms:
---> 95         img = t(img)
     96     return img

File C:\Program Files\Python310\lib\site-packages\torchvision\transforms\transforms.py:135, in ToTensor.__call__(self, pic)
    127 def __call__(self, pic):
    128     """
    129     Args:
    130         pic (PIL Image or numpy.ndarray): Image to be converted to tensor.
   (...)
    133         Tensor: Converted image.
    134     """
--> 135     return F.to_tensor(pic)

File C:\Program Files\Python310\lib\site-packages\torchvision\transforms\functional.py:163, in to_tensor(pic)
    161 # handle PIL Image
    162 mode_to_nptype = {"I": np.int32, "I;16": np.int16, "F": np.float32}
--> 163 img = torch.from_numpy(np.array(pic, mode_to_nptype.get(pic.mode, np.uint8), copy=True))
    165 if pic.mode == "1":
    166     img = 255 * img

RuntimeError: **Numpy is not available**

**Comment by Louis-Dupont** [comment]
As I thought this is not due to SG, this happens when calling `img = pre_proccess(img).unsqueeze(0).cuda()`, which is only pytorch.

You can try to upgrade numpy (see: https://stackoverflow.com/questions/71689095/how-to-solve-the-pytorch-runtimeerror-numpy-is-not-available-without-upgrading)

**Comment by MaxEAB** [comment]
Hi, Thanks, updating numpy fixed it. Is there a sample code available for overlaying the mask on the image for a visual verification?
