### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by onurcaydere** [Deci-AI/super-gradients#939]
![Screenshot 2023-05-06 095620](https://user-images.githubusercontent.com/63595177/236608571-796ca7e5-5df4-41d2-bbfe-b076cc463e75.png)

Can you help me ?

**Comment by Louis-Dupont** [comment]
Hi, can you provide the code snippet to reproduce this? Also, can you please provide full traceback to see what function call leads to this?
Please provide both with the "add code" functionality because it allows us to copy, unlike pictures :)
Thanks
