### ISSUE TITLE
Adding Performance Metrics Plots at the End of Training Process

### ISSUE THREAD

**Issue by hamedgorji** [Deci-AI/super-gradients#942]
Hi,
I'd like to request adding plots for performance metrics (precision, recall, map50, map50-95, PR_curve, etc) at the end of the training process.
Thanks

**Comment by shaydeci** [comment]
Hey @hamedgorji ,

Plots are available throughout training, including the end of it through tensorboards (see [here](https://github.com/Deci-AI/super-gradients/blob/master/documentation/source/experiment_monitoring.md))
