### ISSUE TITLE
Getting this error: cannot import name 'is_directory' from 'PIL._util' (/usr/local/lib/python3.10/dist-packages/PIL/_util.py)

### ISSUE THREAD

**Issue by vijay2712** [Deci-AI/super-gradients#950]
# from super_gradients.training import models

# yolo_nas_l = models.get("yolo_nas_s", pretrained_weights="coco")

ImportError                               Traceback (most recent call last)
[<ipython-input-17-e588e267cef5>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 # Load model with pretrained weights
----> 6 from super_gradients.training import models
      7 from super_gradients.common.object_names import Models
      8 

13 frames
[/usr/local/lib/python3.10/dist-packages/PIL/ImageFont.py](https://localhost:8080/#) in <module>
     36 from . import Image
     37 from ._deprecate import deprecate
---> 38 from ._util import is_directory, is_path
     39 
     40 

ImportError: cannot import name 'is_directory' from 'PIL._util' (/usr/local/lib/python3.10/dist-packages/PIL/_util.py)

**Comment by BloodAxe** [comment]
Fixed in this [PR](https://github.com/Deci-AI/super-gradients/pull/908). This will become available in the next release.
Nightly version can be installed via ~pip install -U git+https://github.com/Deci-AI/super-gradients@master`

**Comment by VHIT-management** [comment]
Hello, I have an error 'Pil has no attirbute Image' while import supr_gradients. Can you tell me how ti fix it?
