### ISSUE TITLE
`ImagesDetectionPrediction._images_prediction_lst` is not `List`. It is `Generator`. 

### ISSUE THREAD

**Issue by SkalskiP** [Deci-AI/super-gradients#956]
### Describe the bug

Just as in the title: `ImagesDetectionPrediction._images_prediction_lst` is not `List`. It is `Generator`. 

### To Reproduce

```python
>>> import torch
>>> from super_gradients.training import models

>>> DEVICE = 'cuda' if torch.cuda.is_available() else "CPU"
>>> VERSION = 'yolo_nas_l'
>>> model = models.get(VERSION, pretrained_weights="coco").to(DEVICE)

>>> SOURCE_IMAGE_PATH = f"{HOME}/data/dog-3.jpeg"
>>> result = model.predict(SOURCE_IMAGE_PATH, conf=0.25)
>>> type(result._images_prediction_lst)
generator
```

### Expected behavior

`ImagesDetectionPrediction._images_prediction_lst` should be a list, not a generator. 

### Additional context

That leads to many weird/unwanted interactions:

- **Can't access prediction by index** - `ImagesPredictions` - parent class for `ImagesDetectionPrediction` provide `__getitem__` implementation but because `_images_prediction_lst` is a generator it does not work.

```python
>>> result = model.predict(SOURCE_IMAGE_PATH, conf=0.25)
>>> result[0]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-34-2c43f6f8ed53>](https://localhost:8080/#) in <cell line: 1>()
----> 1 result[0]

[/usr/local/lib/python3.10/dist-packages/super_gradients/training/models/prediction_results.py](https://localhost:8080/#) in __getitem__(self, index)
    122 
    123     def __getitem__(self, index: int) -> ImagePrediction:
--> 124         return self._images_prediction_lst[index]
    125 
    126     def __iter__(self) -> Iterator[ImagePrediction]:

TypeError: 'generator' object is not subscriptable
```

- **Can't get predictions count** - `ImagesPredictions` - parent class for `ImagesDetectionPrediction` provide `__len__` implementation but because `_images_prediction_lst` is a generator it does not work.

```python
>>> result = model.predict(SOURCE_IMAGE_PATH, conf=0.25)
>>> len(result)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-35-69290ace8698>](https://localhost:8080/#) in <cell line: 1>()
----> 1 len(result)

[/usr/local/lib/python3.10/dist-packages/super_gradients/training/models/prediction_results.py](https://localhost:8080/#) in __len__(self)
    119 
    120     def __len__(self) -> int:
--> 121         return len(self._images_prediction_lst)
    122 
    123     def __getitem__(self, index: int) -> ImagePrediction:

TypeError: object of type 'generator' has no len()
```

- **After you call `show` you loose your predictions**

```python
>>> result = model.predict(SOURCE_IMAGE_PATH, conf=0.25)
>>> result.show()
>>> list(result)
[]
```

**Comment by Louis-Dupont** [comment]
Hi @SkalskiP ,
We fixed it in this [PR](https://github.com/Deci-AI/super-gradients/pull/945), which will be available in the next release.
The nightly version can be installed via `pip install -U git+https://github.com/Deci-AI/super-gradients@master`.

If you don't want to change for nightly version, you can always cast it as a list (not tested but should work):
```python
result = model.predict(SOURCE_IMAGE_PATH, conf=0.25)
result._images_prediction_lst = list(result._images_prediction_lst)
```

Hoping this helps

**Comment by SkalskiP** [comment]
Yup that's what I did `result = list(model.predict(image, conf=0.35))[0]` :)

**Comment by Alberto1404** [comment]
> 
HI @SkalskiP , what other parameters rather than iou are available to customize for inference? I can't find it in the docs
