### ISSUE TITLE
How can i solve this warning that appear during inference 

### ISSUE THREAD

**Issue by Mohamed2519** [Deci-AI/super-gradients#971]
these warnings appear during inference.  How can I solve it?
![Screenshot 2023-05-10 162106](https://github.com/Deci-AI/super-gradients/assets/42303826/768adc5c-f699-45eb-89a9-b2fa8eed2a61)

**Comment by Louis-Dupont** [comment]
Hi @Mohamed2519 

You can set the environment variable `CONSOLE_LOG_LEVEL` to control it.

``` python
import os

os.environ["CONSOLE_LOG_LEVEL"] = "ERROR"

from super_gradients.common.object_names import Models
from super_gradients.training import models

# Note that currently only YoloX, PPYoloE and YOLO-NAS are supported.
model = models.get(Models.YOLO_NAS_L, pretrained_weights="coco")
```
