### ISSUE TITLE
Predict for video with long playback time

### ISSUE THREAD

**Issue by momonoki3nenn** [Deci-AI/super-gradients#976]
Here is what happened.
When predicting a large capacity video, RAM usage reaches 100% and the vscode window is broken.

Here is my environment.
- OS : Windows11
- RAM : 64GB
- GPU : RTX3080
- vscode : 1.78.1
- python : 3.9.13
- super-gradient : 3.1.0
- pytorch : 1.13.1+cu117

Video information generated.
- size : 2.22GB
- frame-width : 3840
- frame-height : 2160
- Replay time : 00:01:57
- fps : 60

I expect it is caused by too much cache in memory.
In YOLOv8, there is a workaround. [Example YOLOv8](https://github.com/ultralytics/ultralytics/issues/1123)

Is there a workaround in YOLO-NAS

I often use videos with long playback times, so I would very much like to know a workaround!

It's part of my code.
![one_part](https://github.com/Deci-AI/super-gradients/assets/105626505/b8672553-c822-487a-8f1d-038e00a18ad8)

**Comment by Louis-Dupont** [comment]
Hi @momonoki3nenn ,

This is a feature that is in our backlog, but meanwhile, you will have to load/write the video manually.
Here is a script that should do the job until it is added to SG.
``` python
def process_video(input_file: str, output_file: str, batch_size: int) -> None:
    # Initialize video capture object
    cap = cv2.VideoCapture(input_file)

    # Get video properties
    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # Create video writer object
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_file, fourcc, fps, (frame_width, frame_height))

    while True:

        # Load frames by batch to increase performance
        frames = []
        for _ in range(batch_size):
            ret, frame = cap.read()
            if not ret:
                break
            frames.append(frame)

        if not frames:
            break

        frames_predictions = model.predict(frames)

        for frame_prediction in frames_predictions:
            out.write(frame_prediction.draw())

    # Release video capture and writer objects
    cap.release()
    out.release()
```
Make sure to set `batch_size` high enough to increase inference speed. Hoping this helps.

**Comment by BloodAxe** [comment]
We have implemented memory-efficient predict for video in super-gradients 3.5.0.
So you are welcome to upgrade to a new version of SG which should not have this issue.
