### ISSUE TITLE
SystemError: new style getargs format but argument is not a tuple

### ISSUE THREAD

**Issue by janardan-ds** [Deci-AI/super-gradients#979]
While doing train_data.dataset.plot() getting the system error :

SystemError                               Traceback (most recent call last)
Cell In[42], line 1
----> 1 train_data.dataset.plot()

File ~/anaconda3/lib/python3.8/site-packages/super_gradients/training/datasets/detection_datasets/detection_dataset.py:463, in DetectionDataset.plot(self, max_samples_per_plot, n_plots, plot_transformed_data)
    460 index = img_i + plot_i * 16
    462 if plot_transformed_data:
--> 463     image, targets, *_ = self[img_i + plot_i * 16]
    464     image = image.transpose(1, 2, 0).astype(np.int32)
    465 else:
SystemError: new style getargs format but argument is not a tuple

<Figure size 1000x1000 with 0 Axes>

And also during traing getting the runtime error

RuntimeError: DataLoader worker (pid(s) 1762330) exited unexpectedly

**Comment by BloodAxe** [comment]
It is hard to tell exactly what cause this problem. 

Can you please provide more information about your issue:
- Link to colab if possible
- What dataset are you using and dataset params you've used to instantiate it?
- What is the number of samples in the dataset 
- Version of SuperGradients you're using

**Comment by janardan-ds** [comment]
=> What dataset are you using and dataset params you've used to instantiate it? --> jpg and txt (yolo format)
=> What is the number of samples in the dataset --> around 4k in train (images and labels), 1k in val and 200 in test.
=> Version of SuperGradients you're using --> latest 3.1.1

**Comment by Louis-Dupont** [comment]
Hi @janardan-ds 

Concerning the Dataset plot, it is a little buggy and we will fix it soon, but until then I don't have a quick workaround for that.

Concerning the error you got in training, this is a known pytorch issue (https://github.com/pytorch/pytorch/issues/5301), I'm not sure why it happens, but usually setting `num_workers` to 0 solves it, you can try this out:

``` python
train_data = coco_detection_yolo_format_train(
    dataset_params={
        'data_dir': dataset_params['data_dir'],
        'images_dir': dataset_params['train_images_dir'],
        'labels_dir': dataset_params['train_labels_dir'],
        'classes': dataset_params['classes']
    },
    dataloader_params={
        'batch_size':16,
        'num_workers': 0 # instead of 2
    }
)
```

Let me know if this works for you :)
