### ISSUE TITLE
Do you have Docker image work in arm64 platorm?

### ISSUE THREAD

**Issue by storm12t48** [Deci-AI/super-gradients#987]
Hello 

Do you have a docker image for arm64 like the one on amd64 ? [here](https://docs.deci.ai/super-gradients/documentation/source/SGDocker.html#instructions-and-recommended-practices)

**Comment by BloodAxe** [comment]
No we don't have them.

But probably you can start with https://github.com/dusty-nv/jetson-containers and build one from there.

**Comment by storm12t48** [comment]
thx
