### ISSUE TITLE
bug while importing models

### ISSUE THREAD

**Issue by PraneethaB22** [Deci-AI/super-gradients#988]
### Describe the bug
bug while importing models from super_gradient.training import models

### To Reproduce
1. Train recipe
```
from super_gradients.training import models
```
3. Change param (None Changed)
```
ImportError: cannot import name 'OrderedDict' from 'typing' ([c:\Users\..\anaconda3\envs\yolo-nas\lib\typing.py](file:///C:/Users/../anaconda3/envs/yolo-nas/lib/typing.py))
```

### Expected behavior
I expected successful implementation of the quickstart code

### Screenshots
![MicrosoftTeams-image (10)](https://github.com/Deci-AI/super-gradients/assets/116703923/aae67b5a-9352-4243-90b7-555154909f8f)

### Environment:
 - Windows 11 OS 
 - Super Gradients version = 3.1.0
 - Python environment [e.g. pip freeze] = 3.7

**Comment by danbochman** [comment]
Hi @PraneethaB22 

`typing` is a standard built-in Python library. 
Can you try running `from typing import OrderedDict` in a standalone script? Or just try running simple Python scripts in your environment? 
I suspect your Python environment isn't installed correctly.

**Comment by BloodAxe** [comment]
It seems you need python of version 3.7.2 and higher in order for `from typing import OrderedDict` to work:
https://docs.python.org/3.7/library/typing.html#typing.OrderedDict
https://stackoverflow.com/questions/75529492/importerror-cannot-import-name-ordereddict-from-typing

So the quick solution for you would be to install newer Python and for us - use `collections.OrderedDict` instead, but that would be available only in the next release.
