### ISSUE TITLE
How to export model to torchscripts and tflite?

### ISSUE THREAD

**Issue by srn-source** [Deci-AI/super-gradients#994]
I have found that Yolo Nas support exporting Onnx but dont have the method to export torchscripts and tflite which is important to use inference on Mobile phone. Do anyone suggest me how to do that?

**Comment by BloodAxe** [comment]
Yolo NAS supports export via [torch.jit.trace](https://pytorch.org/docs/stable/generated/torch.jit.trace.html) (Not torch.jit.script, pay attention to that!).
Just follow guidelines and you should be good:
```python
yolo_nas = models.get(Models.YOLO_NAS_S, pretrained_weights="coco").cuda().eval()
yolo_nas.prep_model_for_conversion(input_size=[1, 3, 640, 640])
   
traced_model = torch.jit.trace(yolo_nas, torch.randn(1,3,640,640).cuda())
```

You still would have to do predictions decoding and NMS. But hopefully this should give you a good starting point.

Regarding tflite I can't help you here as we do not provide support for this backend.
